### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by No9** [Level/leveldown#102]
So I was talking to @dominictarr earlier this week at decent camp and we are both interested in node-android. 
Currently testing out these build instructions 
https://gist.github.com/modeswitch/114c9bd55d800df242a2 

But according to this issue it should just work: 
https://github.com/joyent/node/pull/5514 

Talking to @mafintosh it shouldn't be to hard to put into the 'prebuilt' stuff but we need to workout the build. 

@rvagg at peerconf last year you mentioned your were doing some android build magic. Do you have anything to drop into this? 

FYI other people are starting to look at node-android and they are looking for dbs.
https://groups.google.com/forum/#!topic/Nodejs/36gLW3O_394

**Comment by ralphtheninja** [comment]
See https://github.com/level/leveldown-mobile
