### ISSUE TITLE
asBuffer does not default to true

### ISSUE THREAD

**Issue by nolanlawson** [Level/leveldown#119]
I was using `level` to store some Buffers, and I noticed that by default, if you put in a Buffer, you actually get back a string. I tried setting `{asBuffer: true}` (although the docs say it's the default), and that still didn't work. In the end, I had to set `{asBuffer: true, valueEncoding: 'binary'}`, the latter of which does not seem to be documented.

Script to repro:

```js
var level = require('level');

var db = new level('./mydb');

var buff = new Buffer('some text');

db.put('id', buff, function (err) {
  console.log('trying plain get()');
  db.get('id', function (err, resp) {
    console.log('response type is: ' + (typeof resp));
    console.log('response is: ' + JSON.stringify(resp));
    
    console.log('\ntrying get() with asBuffer:true');
    db.get('id', {asBuffer: true}, function (err, resp) {
      console.log('response type is: ' + (typeof resp));
      console.log('response is: ' + JSON.stringify(resp));
      
      console.log('\ntrying get() with asBuffer and valueEncoding set');
      db.get('id', {asBuffer: true, valueEncoding: 'binary'}, function (err, resp) {
        console.log('response type is: ' + (typeof resp));
        console.log('response is: ' + JSON.stringify(resp));
      })
    });
  })
});
```
Output:

```
trying plain get()
response type is: string
response is: "some text"

trying get() with asBuffer:true
response type is: string
response is: "some text"

trying get() with asBuffer and valueEncoding set
response type is: object
response is: [115,111,109,101,32,116,101,120,116]
```

**Comment by ralphtheninja** [comment]
@nolanlawson Is this still a documentation issue in your opinion?

**Comment by nolanlawson** [comment]
@ralphtheninja I'd say so, yeah. It's just a bit unintuitive I think. I think we can safely close this issue.

**Comment by ralphtheninja** [comment]
@nolanlawson I'd be happy to update the docs. Any suggestions to better wording?

**Comment by nolanlawson** [comment]
I actually don't see `asBuffer` documented anywhere on https://github.com/rvagg/node-levelup, but I'd say it just should specify that if you really want a `Buffer`, you have to set `valueEncoding` to `'binary'`.

**Comment by ralphtheninja** [comment]
@nolanlawson Does this look ok? https://github.com/ralphtheninja/levelup/commit/50ba1fef33837d836310c6bbab76101fa567af02
