### ISSUE TITLE
Upgrade to LevelDB@1.18.0

### ISSUE THREAD

**Issue by rvagg** [Level/leveldown#129]
See https://github.com/google/leveldb/releases/tag/v1.18

A job for somebody with some spare time on their hands one weekend. Will justify a minor version bump.

**Comment by ralphtheninja** [comment]
We have two PRs https://github.com/Level/leveldown/pull/174 and https://github.com/Level/leveldown/pull/132 to select from. I haven't had the time to look at it, but plan to do that at least this coming week.

/cc @Level/owners
