### ISSUE TITLE
Vagrant breakage: LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`

### ISSUE THREAD

**Issue by yoshuawuyts** [Level/leveldown#137]
Similar to https://github.com/Level/level/issues/1, when spinning up `vagrant` + `boot2docker`. When running `ls node_modules`, `leveldown` is listed.

###### vagrantfile
```rb
require 'fileutils'

APP_PATH = Dir.pwd
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boot2docker"
  config.vm.box_url = "https://vagrantcloud.com/mitchellh/boxes/boot2docker/versions/1.2.0/providers/virtualbox.box"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder APP_PATH, APP_PATH, id: "koalevel", :nfs => true, :mount_options => ['nolock,vers=3,udp']
end
```

###### versions
```
    "leveldown": "^1.0.0"
    "levelup": "^0.19.0"
```

Halfway through the installation I'm getting the following, not sure if related:
```
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/0.11.14"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/leveldown/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/lib/node_modules/leveldown/build'
```

Initializing leveldb as following, with `process.env.DB` set to `/data`:
```js
var levelup = require('levelup');
var wrap = require('co-level');

var path = process.env.DB || './.leveldb';
var options = {};
options.valueEncoding = options.valueEncoding || 'json';
var db = wrap(levelup(path, options));
```

Not sure what is causing this. As per https://github.com/rvagg/node-levelup/issues/222#issuecomment-35228431 I'm using `NFS`, but in my instance it fails (don't mind using it, though it isn't ideal).

As per https://github.com/Level/level/issues/1's suggestion I'm using `/data` (which should not be shared) but that doesn't appear to have any effect.

Any suggestions on how to fix this?

**Comment by ralphtheninja** [comment]
@yoshuawuyts Did you manage to solve this?

**Comment by yoshuawuyts** [comment]
@ralphtheninja I wasn't able to solve this at the time. Due to time constraints I had to abandon the project. I no longer have access to the project, so I don't think this issue will be able to be resolved. Thanks for checking up though :sparkles:
