### ISSUE TITLE
Problem when trying to build for node-webkit ( fatal error: too many errors emitted, stopping now )

### ISSUE THREAD

**Issue by hems** [Level/leveldown#138]
Hello Guys, i guess this issue might not be exactly related to you, but i'm in high hopes that you might be able to help us.

We are trying to build "level" and use "level" inside a node-webkit application, but it is yielding errors when trying to rebuild using nw-gyp.

Here is a paste bin with my console output: http://pastebin.com/Nye3HhBG

**Comment by ralphtheninja** [comment]
@hems Sorry that a response took so long. Please try this again. I suspect it has to do with an older version of `nan`. Reopen this issue if you're still having problems.

**Comment by hems** [comment]
@ralphtheninja i'm far down the line on sqlite at the moment, would have to revert my project too far back and jiggle. i don't think i'll be able to test that so soon. apologises.

**Comment by ralphtheninja** [comment]
No worries.
