### ISSUE TITLE
expose the open state

### ISSUE THREAD

**Issue by substack** [Level/leveldown#142]
It would make levelup much less complicated and easier to use with arbitrary leveldowns if leveldown could keep track of its own open state instead of tracking that information externally.

Here is the relevant discussion from levelup:
https://github.com/rvagg/node-levelup/pull/299#issuecomment-69713031

**Comment by rvagg** [comment]
@substack something you could contribute towards this are some breaking tests in abstract-leveldown so there's less work here and we can enforce the behaviour across all of the leveldowns.

**Comment by juliangruber** [comment]
What if deferred-leveldown took care of this? So its role could transform from "buffer operations" to "makes a leveldown always look open"

**Comment by ralphtheninja** [comment]
State is handled by `abstract-leveldown` and no longer by `levelup`
