### ISSUE TITLE
Move to "level" org?

### ISSUE THREAD

**Issue by rvagg** [Level/leveldown#153]
See https://github.com/rvagg/node-levelup/issues/316, same is relevant here.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by hij1nx** [comment]
:+1:

**Comment by mcollina** [comment]
:+1:, I would say this will just follow whatever levelup is doing.

**Comment by juliangruber** [comment]
Yes

**Comment by ekristen** [comment]
+1
