### ISSUE TITLE
0.10.3 compatibility

### ISSUE THREAD

**Issue by yamsellem** [Level/leveldown#156]
Looking at its release date (7th of February), it seems that release 0.10.3 and next are compatible with node 0.12.0 (released 6th of February) because they don't work anymore with node 0.10.0 to me.

Is it the proper behavior?
Can it be documented to avoid confusion?

Thanks.

**Comment by ralphtheninja** [comment]
We should still be compatible with node `0.10`. Could you be a little more specific in what is not working? Thanks.

**Comment by ralphtheninja** [comment]
@yamsellem The tests pass for `0.10.37` so we know that much at least :) (https://travis-ci.org/rvagg/node-leveldown#L225)

**Comment by ralphtheninja** [comment]
@yamsellem Please post the output of: `node -v` and `npm -v` and the error output you get.

**Comment by yamsellem** [comment]
@ralphtheninja sorry for the delay. I've test it again and do not encountered any issue. I should have been wrong then (and I cursed myself for the absolute lack of detail of my first post). I'll post here if I find more.

**Comment by ralphtheninja** [comment]
:+1:
