### ISSUE TITLE
leveldown-hyper should be a fork of leveldown

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#159]
It's a bit messy right now since the `leveldown-hyper` module on npm corresponds to the `hyper-leveldb` branch in this repository. Also, we are using a git submodule for the `HyperLevelDB` dependency.

**Comment by juliangruber** [comment]
:+1:

**Comment by ekristen** [comment]
+1

**Comment by mcollina** [comment]
+1
Il giorno sab 28 mar 2015 alle 03:34 Erik Kristensen <
notifications@github.com> ha scritto:

**Comment by dweinstein** [comment]
:+1:

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown-hyper
