### ISSUE TITLE
Rename to leveldown?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#160]
I believe the `node-*` naming convention is from the days where many repositories got the `node-` prefix to I guess be more explicit that it was a node module. Today I think people get that anyway because of an existing `package.json` and whatnot.

I also think that renaming this to match the module name is a good idea.

I know @juliangruber has +1'ed this before. What about the rest of you? :)

**Comment by ekristen** [comment]
+1

**Comment by jcrugzz** [comment]
+1

**Comment by mcollina** [comment]
+1
Il giorno sab 25 apr 2015 alle 19:30 Jarrett Cruger <
notifications@github.com> ha scritto:
