### ISSUE TITLE
Support checksum options

### ISSUE THREAD

**Issue by juliangruber** [Level/leveldown#172]
- `ReadOptions::verify_checksums` for read operations, which, by default, don't verify checksums.
- `Options::paranoid_checks` when opening a db will do aggressive checksum verification

moved over from https://github.com/Level/levelup/issues/12

**Comment by ralphtheninja** [comment]
@vweevers Anything that's still interesting to implement? I could tackle if that's the case.

**Comment by vweevers** [comment]
I have no idea. Personally I've never even seen a corrupted db. But maybe I would have, if `verify_checksums` was enabled? 🤷‍♂

**Comment by ralphtheninja** [comment]
@peakji Anything that floats your boat?

**Comment by peakji** [comment]
I have never seen a corrupted db. And in my use case, I guess I'll keep `verify_checksums` disabled for better read performance.

However, there are some blockchain and coin projects using leveldown, maybe checksums are useful there?

**Comment by peakji** [comment]
BTW, leveldb got some interesting updates recently, we could import after their next release.

**Comment by vweevers** [comment]
Just discovered that in RocksDB both `verify_checksums` and `paranoid_checks` are true by default and in `rocksdb` we currently only override `paranoid_checks` to be false. Should we set both to false?

**Comment by vweevers** [comment]
Can reopen if there's interest.
