### ISSUE TITLE
ability to set permissions on the database files

### ISSUE THREAD

**Issue by andrewrk** [Level/leveldown#177]
When you create a leveldb database, it creates files on the file system like this: http://paste.debian.net/174051/

That can be a security issue, in which case we need the perms to be 0600 instead of world-readable.

**Comment by fsateler** [comment]
Pasting here for posterity as the pastebin will expire sometime:

      total 28M
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000046.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000047.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000048.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000049.ldb
      -rw-r--r-- 1 felipe felipe  816K May  9 14:24 000050.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000051.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000052.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 14:24 000053.ldb
      -rw-r--r-- 1 felipe felipe  1.9M May  9 14:24 000054.ldb
      -rw-r--r-- 1 felipe felipe  262K May  9 14:54 000056.ldb
      -rw-r--r-- 1 felipe felipe  265K May  9 21:19 000059.ldb
      -rw-r--r-- 1 felipe felipe  489K May  9 21:28 000062.ldb
      -rw-r--r-- 1 felipe felipe   31K May  9 21:28 000065.ldb
      -rw-r--r-- 1 felipe felipe  960K May  9 21:38 000066.log
      -rw-r--r-- 1 felipe felipe  2.1M May  9 21:28 000067.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 21:28 000068.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 21:28 000069.ldb
      -rw-r--r-- 1 felipe felipe  2.1M May  9 21:28 000070.ldb
      -rw-r--r-- 1 felipe felipe 1014K May  9 21:28 000071.ldb
      -rw-r--r-- 1 felipe felipe    16 May  9 21:28 CURRENT
      -rw-r--r-- 1 felipe felipe     0 May  5 23:21 LOCK
      -rw-r--r-- 1 felipe felipe   970 May  9 21:28 LOG
      -rw-r--r-- 1 felipe felipe   317 May  9 21:28 LOG.old
      -rw-r--r-- 1 felipe felipe  2.0K May  9 21:28 MANIFEST-000064

**Comment by ralphtheninja** [comment]
How can you enforce a process to create files with only `rw` access for the current user?

**Comment by andrewrk** [comment]
I made an assumption that leveldb API exposed permissions. I just browsed the leveldb source code and now I see that they do not, in fact, expose this functionality. So that means the node.js wrapper can't have this feature.
