### ISSUE TITLE
Sample for the given statement

### ISSUE THREAD

**Issue by obastemur** [Level/leveldown#180]
I saw below statement on README and wondering if there is any sample that I can use to reproduce a crash scenario. 
```
It is strongly recommended that you use LevelUP in preference to LevelDOWN unless you have 
measurable performance reasons to do so. LevelUP is optimised for usability and safety. 
Although we are working to improve the safety of the LevelDOWN interface it is still easy to crash your 
Node process if you don't do things in just the right way.
```

If a sample is not viable, I really appreciate if you can please explain a bit. What makes LevelDOWN unsafe ?

**Comment by juliangruber** [comment]
levelup does additional argument checking, keeps you from crashing the process by for example performing operations against a closed db, emits more meaningful errors, and more :)

**Comment by obastemur** [comment]
@juliangruber Thanks for the initials.
