### ISSUE TITLE
Use which node versions on travis?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#189]
Currently we are testing `0.10`, `0.12`, `1.8`, `2.0`, `2.1` and `2.2` on travis. Should we reduce the number of iojs versions?

**Comment by juliangruber** [comment]
hmm what would be the advantage? faster builds?

**Comment by ralphtheninja** [comment]
Slept on it and I think we should probably focus on node version with different ABI versions, e.g. 0.10, 0.12, 1.8 and 2, since these will be the versions we will create prebuilt binaries for.

**Comment by ralphtheninja** [comment]
@mafintosh Does this make sense?

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/commit/8a57fab2f85a4a167c36909350d72c11956ff573
