### ISSUE TITLE
create script that builds and uploads binaries to github

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#191]
Can you create releases on github via the api as well?

If the new release does not require binaries to be rebuilt (i.e. not updating anything on the c++ side, including dependencies) it should copy the binaries from the previous version and upload them.

cc @mafintosh

**Comment by maxogden** [comment]
I kinda think we shouldn't publish to NPM until the binaries are uploaded to a release.

**Comment by ralphtheninja** [comment]
I agree.

**Comment by ralphtheninja** [comment]
https://github.com/mafintosh/prebuild
