### ISSUE TITLE
fallback to leveldown-mobile

### ISSUE THREAD

**Issue by obastemur** [Level/leveldown#192]
Below code is from `prebuilt.js`
```
var binary = require('node-pre-gyp');
var path = require('path');
var binding_path = binary.find(path.resolve(path.join(__dirname,'./package.json')));

module.exports = require(binding_path).leveldown;
```

On iOS, dynamically linking is not allowed. On Android side, everything is inside the APK file. So, the application needs to extract .node file into real file system first and then link. Still this is not that practical for a node application. The developer needs to update node-modules per desktop and mobile separately.

The assumption for `leveldown-mobile` is that; the native part is already statically linked into framework. 

if we update prebuilt.js to below;
```
try {
  var binary = require('node-pre-gyp');
  var path = require('path');
  var binding_path = binary.find(path.resolve(path.join(__dirname,'./package.json')));
 
  module.exports = require(binding_path).leveldown;
} catch (e) {
  if (typeof jxcore === 'undefined' || !process.versions.embedded || !process.versions.embedded.leveldown) 
    throw e;

  module.exports = jxcore.embeddedModule.require('leveldown').leveldown;
}
```

This wouldn't make any change on actual Leveldown's behavior. However, it will be using embedded Leveldown automatically on mobile platforms.

What do you think ?

**Comment by ralphtheninja** [comment]
I don't like to have jxcore specifics inside leveldown. But we should be able to do something similar by instead adding an api to `prebuilt.js` so you can override the default behavior by providing your own function or similar.

**Comment by mcollina** [comment]
I think we should just add a level-mobile project that bundles levelup and
leveldown-mobile.
Il giorno sab 20 giu 2015 alle 19:48 Magnus <notifications@github.com> ha
scritto:

**Comment by ralphtheninja** [comment]
+1 for level-mobile

**Comment by obastemur** [comment]
level-mobile sounds nice but there is a one problem. Upper module needs to target level-mobile. Actually, apart from the native (c,c++) part, there won't be any difference between leveldown and leveldown-mobile.

How about something with `if (process.platform == 'ios' || process.platform == 'android')` under the `catch` ?

The fallback mechanism works really nice though. I totally got the part with specifics. It would be really nice, if it fallbacks to something doesn't look like anything specific though. I think I can come up with something if fallback behavior is okay ?

**Comment by obastemur** [comment]
Thinking it again, level-mobile is also fine though. +1 .. i.e. pouchdb may pick level-mobile as a backend.
Sounds okay!

**Comment by ralphtheninja** [comment]
Hmm I kind of like the idea of some sort of fallback mechanism. What if I want to run application A that assumes leveldown somewhere underneath. It would be neat if there was some way of running any node application on jxcore *if* there are fallbacks defined somewhere.

**Comment by ralphtheninja** [comment]
To be more concrete. Lets assume I'd like to run `scuttlebot` on my router, but using `jxcore` instead of node.

cc @dominictarr

**Comment by dominictarr** [comment]
@ralphtheninja that would also require https://github.com/paixaop/node-sodium to be running on jxcore... I'm no C expert but it seems what is needed is a way to compile jxcore + any extentions into just one binary?

**Comment by ralphtheninja** [comment]
`node-sodium` would be awesome to have running on jxcore. I know too little about jxcore to see how we can simplify using already existing applications with native modules.

**Comment by obastemur** [comment]
> It would be neat if there was some way of running any node application on jxcore if there are fallbacks defined somewhere.

Actually we are at this very moment suffering on a mobile project because of this. There is a desktop test/dev file and mobile version of it. They both share the same node_modules folder. Multiple leveldown and leveldown-mobile folders.

Once embedded and required jxcore doesn't need leveldown.node file is there or anything special to leveldown-mobile

> @ralphtheninja that would also require https://github.com/paixaop/node-sodium to be running on jxcore...

First expression, only `https://github.com/paixaop/node-sodium/blob/master/sodium.cc` needs to be converted. I don't know much about node-sodium but doesn't look like a big deal to update.

**Comment by obastemur** [comment]
Thanks for all the inputs. No issue left. Closing.
