### ISSUE TITLE
binary leveldown@1.3.0 fails with 'GLIBC_2.14 not found' on CentOS 6.6

### ISSUE THREAD

**Issue by okv** [Level/leveldown#200]
Hi, there!

I install leveldown
```
npm install leveldown
\
> leveldown@1.3.0 install /var/www/nci/node_modules/leveldown
> node-pre-gyp install --fallback-to-build

[leveldown] Success: "/var/www/nci/node_modules/leveldown/build-pre-gyp/leveldown.node" is installed via remote
leveldown@1.3.0 node_modules/leveldown
├── bindings@1.2.1
├── fast-future@1.0.1
├── nan@1.8.4
└── abstract-leveldown@2.4.0 (xtend@4.0.0)
```
then get error at runtime
```
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/www/nci/node_modules/leveldown/build-pre-gyp/leveldown.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/nci/node_modules/leveldown/prebuilt.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

can i skip binary installation in some way?

**Comment by ralphtheninja** [comment]
@okv Yep. You can do `npm i --build-from-source` to build it for your system.

**Comment by ralphtheninja** [comment]
@okv What would be the proper way of fixing this so you *can* have prebuilts for centos?

cc @mafintosh

**Comment by okv** [comment]
`--build-from-source` works great, i didn't know about that flag, thanks @ralphtheninja 
I had similar experience when compile patched phantomjs on ubuntu and can't run it on centos then i compiled it on centos and it works perfect on both systems. Looks like when you compile on lower (than at runtime) glibc version it's gonna be ok. It would be great to have binaries for centos.

**Comment by ralphtheninja** [comment]
I'm just wondering how we can achieve that. Maybe we simply need to build them on a centos system but we also need to know which binaries to fetch with `node-pre-gyp`. Currently I know too little about it to come up with a good solution.

**Comment by rvagg** [comment]
Prebuilds need to be done on older dists with older libc to be forward compatible. You can achieve broadest compatibility by compiling on CentOS5 (RHEL5) which is the oldest actually supported distro out there. Doing it with Debian Wheezy would give pretty good coverage too but you may still get complaints (maybe even this specific one about RHEL6).

See the table here for a libc version <-> distro breakdown: https://en.wikipedia.org/wiki/GNU_C_Library

**Comment by ralphtheninja** [comment]
@rvagg Thanks for input!

@okv Out of curiosity. Which version of libc do you have on your system?

**Comment by okv** [comment]
@ralphtheninja CentOS 6.6 GLIBC 2.12

**Comment by ralphtheninja** [comment]
@rvagg Do you think it's possible to install an older version of libc on travis and solve this problem that way?

**Comment by rvagg** [comment]
ehh .. I don't know, I could imagine it'd be possible but I've never done something like that before - I know for instance that when compiling .debs and .rpms you can do it on newer systems but target older ones, I just don't know how that's achieved

is there any way of running Docker on travis perhaps? you could use Docker to do it in a new container running an older environment.

**Comment by mafintosh** [comment]
This should be fixed in 1.4.0. We use an older version of debian to do prebuilds now and we also test if the downloaded prebuild can be loaded. If not it falls back to compiling

**Comment by ralphtheninja** [comment]
@okv Mind trying out a `npm i leveldown` to see if it works for you?

**Comment by okv** [comment]
it works now, thanks a lot

**Comment by okv** [comment]
Hi guys.
Seems newer builds of leveldown (at least 1.4.3, 1.4.4) do not work on systems with old glibc with same error:

`Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/lib/openshift...`

i found that during deploy to openshift (uses glibc 2.12).

I downgrade to leveldown 1.4.0 and prebuild binary works just fine.

**Comment by ralphtheninja** [comment]
@okv But you are able to build it right?

**Comment by ralphtheninja** [comment]
@okv Quick question. Are you using 64 bit or 32 bit? Just so I know what to focus on first.

**Comment by okv** [comment]
@ralphtheninja looks like openshift cloud service just does `npm install`in the project dir during deploy (which starts after my push to repository). I can't find how to pass params to that command. Maybe `--build-from-source` can be passed via some env variable? It's 64 bit system.

**Comment by ralphtheninja** [comment]
> looks like openshift cloud service just does npm installin the project dir during deploy (which starts after my push to repository). I can't find how to pass params to that command. Maybe --build-from-source can be passed via some env variable?

You shouldn't need to. If `prebuild` fails it should fallback to a compile step. Is that not happening?

**Comment by ralphtheninja** [comment]
@okv Ok. I've rebuilt the 64 bit binaries for linux. Please try again with `leveldown@1.4.4`

**Comment by okv** [comment]
@ralphtheninja it doesn't fail during install it fails at runtime (same thing as in my original post, at the begin of that issue). Tried 1.4.4 again - still doesn't work, same error.

**Comment by ralphtheninja** [comment]
@okv Please make sure to do `rm ~/.npm/_prebuilds`

**Comment by ralphtheninja** [comment]
@okv Just to make sure you aren't using a cached version ..

**Comment by okv** [comment]
@ralphtheninja that helped, it's working, thanks again :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja that helped, it's working, thanks again :)

Pheeew!

**Comment by nikz99** [comment]
@okv Its fails at runtime for me too .. Am I supposed to 
`npm i --build-from-source`
`npm i leveldown`
`rm ~/.npm/_prebuilds/ -rf`
and then push the project to openshift ?

**Comment by okv** [comment]
Binary for version 1.4.4 now works with openshift as I mentoined above. If you are going to build froum souce you should do that on target platform (openshift) not locally.
