### ISSUE TITLE
document usage of prebuild module

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#201]
Mainly to explain how it works when used with leveldown and help people resolve problems, see https://github.com/Level/leveldown/issues/200 as an example

**Comment by No9** [comment]
+1 the fact that it isn't a git clone & npm install needs calling out.

**Comment by ralphtheninja** [comment]
Also, once we have prebuilds up and running we should document which version of libc we support. Currently it looks like we will build using Debian Squeeze (libc version 2.11)
