### ISSUE TITLE
build-pre-gyp folder corruption in Win7

### ISSUE THREAD

**Issue by askldjd** [Level/leveldown#205]
This behavior is seen on leveldown 1.3.0 with Win7, and not observed on Mint Linux.

After running npm install leveldown, leveldown.node is not build.

Instead, there is a file called build-pre-gyp that is 308KB. build-pre-gyp is supposed to be a folder, and I suspect that there is a output path bug where the folder and file are merged. This is because leveldown.node is roughly the same size.

![capture](https://cloud.githubusercontent.com/assets/3258724/8918254/028084bc-3485-11e5-9f43-08624a50c244.PNG)

C:\work\code\>npm install level
npm WARN installMany node-pre-gyp was bundled with leveldown@1.3.0, but bundled
package wasn't found in unpacked tree
/
> leveldown@1.3.0 install C:\work\code\ims-git\test\node_modules\leveldown
> node-pre-gyp install --fallback-to-build

[leveldown] Success: "C:\work\code\ims-git\test\node_modules\leveldown\build-pre
-gyp\leveldown.node" is installed via remote
leveldown@1.3.0 node_modules\leveldown
├── bindings@1.2.1
├── fast-future@1.0.1
├── nan@1.8.4
├── abstract-leveldown@2.4.0 (xtend@4.0.0)
└── node-pre-gyp@0.6.8

**Comment by ralphtheninja** [comment]
@askldjd Thanks for reporting this. We are currently working on an improved system for prebuilds and will release a new version tomorrow evening. Hopefully you can close this issue then :)

**Comment by mafintosh** [comment]
this should be fixed now

**Comment by mafintosh** [comment]
just verified that this is indeed fixed (including for 1.3.0)
