### ISSUE TITLE
0.10 -> 1.4 upgrade error: destroy() causing "LOCK: already held by process"

### ISSUE THREAD

**Issue by nolanlawson** [Level/leveldown#210]
I am trying to upgrade PouchDB from leveldown 0.10.5 to 1.4.0. The tests still pass on 0.10.5, but oddly, when I upgrade, I get a new error:

    OpenError: IO error: lock LOCK: already held by process

This error is thrown when I try to call `levelup()` after `close()`ing and `destroy()`ing the old database. (Our tests do this in the `beforeEach()` of each test.) I tried stepping through in the debugger, but nothing obviously popped out to me, so I suspect it might be a bug in leveldown.

The callback that's throwing is [this one](https://github.com/pouchdb/pouchdb/blob/45fcb091d47669df8c3e51092762e73a0691e971/lib/adapters/leveldb/index.js#L148). To reproduce this bug, you can run:

    git clone https://github.com/pouchdb/pouchdb.git -b upgrade-level
    cd pouchdb
    npm i && npm t

To run with `--debug` or `--debug-brk`, you can modify our script in `bin/test-node.sh`.

I'm using Mac OS X Yosemite and I tried this on iojs as well as node 0.10 and 0.12, and I got the same error in all three. Related to https://github.com/pouchdb/pouchdb/issues/3873.

**Comment by nolanlawson** [comment]
I went ahead and did a sort of "git bisect" to try to figure out exactly which version of leveldown broke.

PouchDB is currently using 0.10.5. I can confirm that 1.0.4 is demonstrating this issue. I wasn't able to test 1.0.0-1.0.3 because they didn't build on my machine (Linux Mint).

Anyone have an idea of what changed between 0.10.5 and 1.0.4 that could have caused this issue?

**Comment by nolanlawson** [comment]
Well, I did an actual `git bisect` (my previous build issues were resolved by using 0.10 instead of iojs), and it says that the first bad commit is 185b870402ac57a1f3c939841ff8021a666ffcb6, which makes no sense. :confused:

**Comment by nolanlawson** [comment]
Well, this is totally crazy. I can confirm that d14c56e3e7397aa3e6652d129f7d17e56ad49852 passes our test suite but 185b870 does not.

**Comment by nolanlawson** [comment]
For anyone who wants to run the minimal PouchDB test suite that will pass/fail the fastest, you can do this:

```
hub clone pouchdb/pouchdb && cd pouchdb
npm i
npm link /path/to/leveldown
TIMEOUT=5000 GREP=percent npm run test-node
```

**Comment by nolanlawson** [comment]
This is totally illogical. I can repro the issue by checking out  d14c56e and then modifying the package.json to have 1.0.0 as its version.

Peer deps? leveldown reading its own version somewhere and modifying its behavior? File access from conflicting versions? Gremlins?

**Comment by juliangruber** [comment]
> leveldown reading its own version somewhere and modifying its behavior

i thought about that too, but afaik only levelup does that, and it throws if it finds an incompatible version

**Comment by juliangruber** [comment]
@nolanlawson trying to run the testsuite, i get this:

```bash
 ∴  pouchdb (master) : TIMEOUT=20000 GREP=percent npm run test-node

> pouchdb@4.0.1-prerelease test-node /Users/julian/dev/pouchdb/pouchdb
> sh bin/test-node.sh

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
Seeded with: 1439791140894


  test.basics.js-http
    ✓ Test doc with percent in ID (51ms)

  test.basics.js-local
    1) "before each" hook

  1 passing (20s)
  1 failing

  1) test.basics.js-local "before each" hook:
     Error: timeout of 20000ms exceeded
      at null.<anonymous> (/Users/julian/dev/pouchdb/pouchdb/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by nolanlawson** [comment]
@juluangruber yep, that's exactly it. The bug manifests as a timeout. Unfortunately we don't log the error anywhere because we don't expect it.

**Comment by nolanlawson** [comment]
You can see the error if you add a console.log [here](https://github.com/pouchdb/pouchdb/blob/81f7ef0409a65b33027001983e6ad884d1594c70/lib/adapters/leveldb/index.js#L149-L152).

**Comment by juliangruber** [comment]
@nolanlawson i'm not getting an error there. i'm currently confused since those apis don't seem to match:

- https://github.com/pouchdb/pouchdb/blob/81f7ef0409a65b33027001983e6ad884d1594c70/lib/setup.js#L75
- https://github.com/pouchdb/pouchdb/blob/81f7ef0409a65b33027001983e6ad884d1594c70/tests/integration/utils.js#L161

**Comment by nolanlawson** [comment]
@juliangruber Yeah we currently have a weird setup where you can `PouchDB.destroy()` as well as `new PouchDB().destroy()`, but they both route to the same code.

I'll try to create a better repro case so it's easier to test; in the meantime I recently repro'd the error in Travis (https://github.com/pouchdb/pouchdb/pull/4170); [here's the log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/75867930/log.txt).

**Comment by nolanlawson** [comment]
@juliangruber OK, check this out: https://github.com/pouchdb/pouchdb/pull/4172

What I'm actually seeing now is that the `levelup()` callback is never invoked, so we get nether an error nor a result.

**Comment by juliangruber** [comment]
are you on latest levelup as well?

**Comment by nolanlawson** [comment]
Yeah, I tried a Travis run where I upgraded all 3 of levelup/leveldown/level-sublevel: https://github.com/pouchdb/pouchdb/pull/4170

**Comment by nolanlawson** [comment]
Well, I feel downright foolish. I've been distracted by a red herring -I updated the `leveldown` `dependency` in our `package.json` without also updating the `optionalDependency`. The `optionalDependency` was set to 0.10.2, whereas the regular `dependency` was set to 1.4.1.

So [this error](https://github.com/Level/levelup/blob/8f442f77baea1cdb1b7af844e3374380c2bb015f/lib/util.js#L41-L49) about incompatible versions was getting thrown, but where along the line it was getting swallowed, so I didn't see it.

That said, I can now reproduce the `LOCK: already held by process` error, and I will try to provide a better test case.

**Comment by nolanlawson** [comment]
Minimal test to reproduce: https://github.com/nolanlawson/leveldown-210

**Comment by ralphtheninja** [comment]
@juliangruber Are you looking into this? Do you need an extra pair of eyes on it? :)

**Comment by juliangruber** [comment]
@ralphtheninja i'll look into it in ~1h, but if you wanna do so now feel free to :)

**Comment by juliangruber** [comment]
potential fix: https://github.com/dominictarr/level-sublevel/pull/96

**Comment by juliangruber** [comment]
closing this issue since it's a level-sublevel issue

**Comment by ralphtheninja** [comment]
:+1:
