### ISSUE TITLE
missing release for win 64 leveldown@1.4.1

### ISSUE THREAD

**Issue by csulok** [Level/leveldown#214]
Installing leveldown@1.4.1 on a Windows 2012 server results in:

> leveldown@1.4.1 install C:\app\node_modules\leveldown
> prebuild --download

prebuild WARN install Failed to download prebuild

Having checked the releases page, it looks like the win64 files are missing for this release, but they are there for leveldown@1.4.0. Is there a specific reason for this, or is there a way to nudge the installer to the 32bit binaries if the 64bit is missing? (not sure it's compatible, just asking).

Installing a compiler is still a huge pain, especially with the VS2015 release which starts at 6.5GB, so I'd rather avoid this.

**Comment by No9** [comment]
I know @mafintosh was looking at that here
https://github.com/Level/leveldown/issues/207 but the issue got flooded
@mafintosh where did you finish on win 64 support? 
Thanks

**Comment by ralphtheninja** [comment]
@csulok You could do `npm i leveldown@1.4.0` as a workaround for now.

**Comment by csulok** [comment]
Did that, thanks :) the changelog is kinda sparse after 1.0.7, but the commit log showed there's nothing groundbreaking between the 2 releases.

**Comment by mafintosh** [comment]
I still have trouble getting leveldown to build on latest iojs on win64 (help greatly appreciated!!) which is why new builds for win64 havent been added. As a temporary workaround I'll add builds for the other versions.

**Comment by No9** [comment]
Hey @mafintosh I have the builds for x64 windows on iojs 3.2.0 and illumOS. too
Can I put them some where or is there some additional foo that we need to do? 
.

**Comment by ralphtheninja** [comment]
@No9 You should be able to do `prebuild --upload` to build and upload them. You need to have a github token though in order for the upload to succeed. You can also manually upload them.

**Comment by mafintosh** [comment]
@No9 yea would be great if you could run that to make builds for all the win x64 node versions

**Comment by No9** [comment]
@mafintosh @ralphtheninja thanks 
--upload was the magic I was looking for :)

**Comment by No9** [comment]
@ralphtheninja finally got my finger out on this. 
I have ran builds for v0.10.40, v0.12.7 and iojs 3.3.0 
they are in the releases folder 
leveldown-v1.4.1-node-v45-win32-x64.tar.gz
leveldown-v1.4.1-node-v14-win32-x64.tar.gz
leveldown-v1.4.1-node-v11-win32-x64.tar.gz
There is a funny using the automated generator with all the versions as I am hitting an issue with v2.4.0 

@csulok can you retest you this should work now.

**Comment by ralphtheninja** [comment]
:+1:
