### ISSUE TITLE
leveldown not building on smartos

### ISSUE THREAD

**Issue by mscandal** [Level/leveldown#215]
this is the output from `npm i leveldown` with
```
> node -v
v0.10.33
> npm -v
2.14.0
> node-gyp -v
v2.0.2
```

```
/
> leveldown@1.4.1 install /home/bloompop/Bloompop/node_modules/leveldown
> prebuild --download

prebuild WARN install Failed to download prebuild
make: Entering directory '/home/bloompop/Bloompop/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
In file included from /opt/local/gcc47/include/c++/bits/localefwd.h:44:0,
                 from /opt/local/gcc47/include/c++/string:45,
                 from ../deps/leveldb/leveldb-1.18.0/include/leveldb/status.h:16,
                 from ../deps/leveldb/leveldb-1.18.0/db/builder.h:8,
                 from ../deps/leveldb/leveldb-1.18.0/db/builder.cc:5:
/opt/local/gcc47/include/c++/cctype:89:11: error: '::isblank' has not been declared
deps/leveldb/leveldb.target.mk:140: recipe for target 'Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o' failed
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o] Error 1
make: Leaving directory '/home/bloompop/Bloompop/node_modules/leveldown/build'
prebuild ERR! build `make` failed with exit code: 2
npm ERR! SunOS 5.11
npm ERR! argv "node" "/opt/local/bin/npm" "i" "leveldown"
npm ERR! node v0.10.33
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.1 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.4.1 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bloompop/Bloompop/npm-debug.log
```

Not really sure what to do. Any help is greatly appreciated.

**Comment by ralphtheninja** [comment]
Mind doing `npm i leveldown --verbose` to get more output and post that into a gist?

**Comment by mscandal** [comment]
Here it is https://gist.github.com/mscandal/5fa8a0b4b49fe2b00493

**Comment by ralphtheninja** [comment]
@mafintosh Can we add a `sunos` machine as well? It seems `process.platform` is `'sunos'`

![sunos-prebuild](https://cloud.githubusercontent.com/assets/308049/9472983/a35ce8b4-4b58-11e5-9a04-75a9a6780c64.png)

**Comment by mscandal** [comment]
Anything I can do to get this working in the meantime?

**Comment by ralphtheninja** [comment]
@mscandal If you can find more information on why it doesn't compile that would be very helpful

**Comment by No9** [comment]
This looks fishy 
`/opt/local/gcc47/include/c++/cctype:89:11: error: '::isblank' has not been declared `
 I just installed 1.4.1 on my SmartOS fine so I am assuming this is an environment issue. 
@mscandal can you give us the output of `gcc --version` mine is 4.7.0

**Comment by mscandal** [comment]
@No9 I'm running gcc 4.7.3

**Comment by No9** [comment]
@mscandal 
K so that looks like a known issue on illumosgate Aug last year.
http://comments.gmane.org/gmane.os.illumos.devel/17570 

Might be worth checking if this patch is valid
http://ma.nexenta.com/~woodstock/isblank-webrev/

**Comment by mscandal** [comment]
I really don't know enough about C++/unix to apply the patch. It looks valid, but those files are read only. Even when root.

**Comment by ralphtheninja** [comment]
@No9 So we do have some limitations on compilers. Perhaps we should write something about that in the readme.

**Comment by No9** [comment]
@ralphtheninja Fair enough I just want to validate the above with a fresh smartOS instance to find out exactly where we stand.

**Comment by No9** [comment]
@mscandal ok so I have just spun up a new joyent instance 
```
Image	nodejs
Image version	15.1.2
```
and ran
```sh
$ npm install leveldb@1.4.1 
```
Works without any problems 

Also of note is that gcc on my newly created instance is one version higher so I think the bug I found above is what you have walked into. 
```
gcc -- version 
gcc (GCC) 4.7.4 
```
If you can confirm your image version please so we know if and when we walk into this again but as the container sec won't let you modify the files I don't think there is a whole heap we can do for you other than recommend you spin up another instance :(

@ralphtheninja as this is passing bug I don't think it warrents front page attention maybe a compiler wiki?

**Comment by mscandal** [comment]
@No9 My image version is nodejs/14.3.0

Thats what I was starting to think the solution would be. Thanks for helping me figure this out though!

**Comment by No9** [comment]
@mscandal no probs always happy to support illumOS folks 
We are few and far between. 
Sorry it wasn't a better outcome. 
If you wouldn't mind closing the issue if we are done here

**Comment by ralphtheninja** [comment]
:+1: Good work Anton!
