### ISSUE TITLE
Only compile once

### ISSUE THREAD

**Issue by nolanlawson** [Level/leveldown#216]
When I `npm install phantomjs`, I notice that it looks for a cached version in `/tmp/phantomjs`, so that it doesn't have to re-download the binary over and over again.

Is there any reason we couldn't do that for leveldown? Every project I work on that's linked to leveldown requires that I re-compile it every time I `npm install`, `npm update`, or `npm link`, which really slows down my workflow. Can we just compile it once and stick the compiled output in `/tmp`?

**Comment by juliangruber** [comment]
That _should_ be taken care of by the newly introduced prebuilds. Are you sure you're running the latest version?

**Comment by nolanlawson** [comment]
Ah dang. :( No, I'm still blocked by this: https://github.com/Level/leveldown/issues/210

**Comment by juliangruber** [comment]
ah, lame. i'll take another look at that issue

**Comment by nolanlawson** [comment]
yeah, I took another crack at it, but I just got completely stymied. I'm in the IRC ##leveldb room if you have questions about how to reproduce

**Comment by juliangruber** [comment]
would it be possible to create a minimal gist triggering the problem? i find it hard to dig through the pouchdb stuff, i'm not familiar with the codebase

**Comment by nolanlawson** [comment]
@juliangruber Sure thing, sorry that it's so complicated. I tried to come up with a minimal test case, but couldn't. :(

**Comment by nolanlawson** [comment]
@juliangruber Gist here: https://gist.github.com/nolanlawson/89e6ec7b987698076690

**Comment by juliangruber** [comment]
I put a `console.log()` on top of each `.destroy = function(){ ... }` I could find in the codebase and of `leveldown`, and none logged anything, so none of the `.destroy()` functions is ever really called. This line of code is reached though and should call one: https://github.com/pouchdb/pouchdb/blob/master/tests/integration/utils.js#L161.

Maybe some of the promise stuff is messing things up?

If I'm on the wrong track...I don't see how this problem relates to a levelup / leveldown `.open()` callback not firing.

**Comment by nolanlawson** [comment]
I doubt it's anything PouchDB-related. I can literally repro this bug by merely incrementing the version in leveldown's `package.json` and making no other change. I can understand it's hard to analyze given PouchDB's monster test suite, though, so I will try to write a small reproducible test case and come back to you.

**Comment by juliangruber** [comment]
Ok, yeah I understand the test case isn't easy to come up with, but I'll happily look into it :)

**Comment by nolanlawson** [comment]
Thanks for your patience! :) And yeah, I actually managed to find a reproducible test case: https://github.com/nolanlawson/leveldown-210.

I suspect this is actually a level-sublevel issue, because if I remove the `sublevel()` call, the test passes.
