### ISSUE TITLE
node.lib: invalid or corrupt file

### ISSUE THREAD

**Issue by mfrost66** [Level/leveldown#222]
platform: Win7x64, Node v4.0.0, npm 2.14.2, node-gyp v3.0.1

Compiling with VS2013 generates the following after compiling leveldown_async.cc.  I also tried with VS2015 but bombed out much earlier with what appears to be missing header file errors.

>>> ...\.node-gyp\4.0.0\Release\node.lib : fatal error LNK1107: invalid
 or corrupt file: cannot read at 0x166F [C:\temp\node_modules\leveldown\build\l
eveldown.vcxproj]

Any suggestions?  I can develop on linux, but if I can't deploy cross-platform it's a show stopper for me.   Is it possible to manually download a prebuilt binary instead?

**Comment by ralphtheninja** [comment]
> Is it possible to manually download a prebuilt binary instead?

@mfrost66 It's not possible at the moment since there are no prebuilts for that version of node yet. Once that has been resolved you should get them by default when doing `npm i leveldown`

**Comment by mfrost66** [comment]
platform: Win7x64, Node v3.3.0, npm 2.13.3, node-gyp v3.0.1

@ralphtheninja 
I reverted back to io.js 3.3.0 which if I understand this [abi matrix](https://raw.githubusercontent.com/mapbox/node-pre-gyp/master/lib/util/abi_crosswalk.json) correctly, should map to the leveldown-v1.4.1-node-v45-win32-x64.tar.gz prebuilt.  But, running ```npm i leveldown``` still fails to download.  What else do I need to do to trigger the download?

install results:
```bat
> leveldown@1.4.1 install ...\node_modules\leveldown > prebuild --download

prebuild WARN install Module did not self-register.
prebuild ERR! build premature close
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\usr\\bin\\node\\node.exe" "C:\\usr\\bin\\node\\node_modules\\npm\\bin\\npm-cli.js" "i" "leveldown"
npm ERR! node v3.3.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
```

**Comment by ralphtheninja** [comment]
@mfrost66 Hmm ok. So there are some problems with that build. @No9 Any ideas?

**Comment by ralphtheninja** [comment]
@No9 @mafintosh Should we wipe all x64 windows builds from https://github.com/Level/leveldown/releases/tag/v1.4.1 and rebuild them all once @No9 has environment setup?

**Comment by No9** [comment]
@ralphtheninja looking now

BTW I can also replicate the original `node.lib: invalid or corrupt file` so I don't think we are going to have an x64 4.0.0 build soon :( 
Trying 32 after I sort 3.3.0 out

**Comment by rvagg** [comment]
if you need help I can run stuff on the Node CI infra to generate builds, just tell me what to run and what you need as output

**Comment by ralphtheninja** [comment]
@rvagg That would be super awesome! It seems windows is the problem. If you want to try it out you could:

```
$ npm i prebuild -g
$ cd leveldown
$ git checkout v1.4.1
$ prebuild -t 0.10.40 -t 0.12.7 -t 1.0.4 -t 1.8.4 -t 2.4.0 -t 3.3.0 -t 4.0.0
```

That will build for all major abis and the resulting `.tar.gz` files will end up in `prebuilds/` in the leveldown root.

If you want to upload them you can append `-u gh-token` to the last command. This will not work though since there already prebuilt files on https://github.com/Level/leveldown/releases/tag/v1.4.1 and `prebuild` only uploads files that haven't been uploaded before.

But you can always manually attach the files to that github release.

**Comment by No9** [comment]
@mfrost66 I can't replicate that issue on 3.3.0
@ralphtheninja Does prebuild verify the module by trying to load it as part of the install?

**Comment by No9** [comment]
So I have bottomed out the 4.0.0 issue the file that is installed node.lib installed with node gyp is as it's actually a 404.html page masquerading as a .lib file :)
I will raise a bug there

**Comment by rvagg** [comment]
@No9 @ralphtheninja this is probably a prebuild issue, as of 4.0.0 (and io.js), the .lib files come from win-x86/node.lib and win-x64/node.lib, this _must_ be fixed on the client side because the SHASUMS256.txt file references those and even if we add a symlink or server rewrite it's not going to verify.

**Comment by rvagg** [comment]
Also

![wut?](https://cldup.com/lLJfInX12R-1200x1200.png)

I don't even

**Comment by rvagg** [comment]
back to the node.lib issue, if prebuild has its own download logic, it could bundle node-gyp and `require('node-gyp/lib/process-release')` to get the correct locations for these assets, all the logic is encapsulated in there as of 3.0.0

**Comment by No9** [comment]
Thanks @rvagg :) 
agree it's a prebuild issue

**Comment by ralphtheninja** [comment]
> So I have bottomed out the 4.0.0 issue the file that is installed node.lib installed with node gyp is as it's actually a 404.html page masquerading as a .lib file :)
I will raise a bug there 

Ugh.

> back to the node.lib issue, if prebuild has its own download logic, it could bundle node-gyp and require('node-gyp/lib/process-release') to get the correct locations for these assets, all the logic is encapsulated in there as of 3.0.0

I'll work on that the coming days if not @mafintosh beats me to it.

**Comment by No9** [comment]
@ralphtheninja on the upside if you manually download the node.lib file and put it in
`.node-gyp\4.0.0\x64`
Then run `prebuild -t 4.0.0 -u <gh-token>` It pushes a build to 
https://github.com/Level/leveldown/releases/edit/v1.4.1/leveldown-v1.4.1-node-v46-win32-x64.tar.gz
:) 

@mfrost66 The 4.0.0 now has a prebuild would really appreciate it if you could validate it.

**Comment by mfrost66** [comment]
@No9 Any suggestions for troubleshooting why the download fails?  The relative (I think) portion of npm-debug.log is below.  I can do a build myself, I'd just prefer to understand why the download fails both for myself and for others who might be in the same boat.

```batch
15474 silly linkStuff leveldown@1.4.1 has c:\usr\Data\SW\ORWatt\server\node_modules as its parent node_modules
15475 verbose linkBins leveldown@1.4.1
15476 verbose linkMans leveldown@1.4.1
15477 verbose rebuildBundles leveldown@1.4.1
15478 verbose rebuildBundles [ '.bin',
15478 verbose rebuildBundles   'abstract-leveldown',
15478 verbose rebuildBundles   'bindings',
15478 verbose rebuildBundles   'fast-future',
15478 verbose rebuildBundles   'nan',
15478 verbose rebuildBundles   'prebuild' ]
15479 info install leveldown@1.4.1
15480 verbose unsafe-perm in lifecycle true
15481 info leveldown@1.4.1 Failed to exec install script
15482 verbose unlock done using C:\Users\mfrost\AppData\Roaming\npm-cache\_locks\leveldown-06075a22086eb7d0.lock for c:\usr\Data\SW\ORWatt\server\node_modules\leveldown
15483 verbose stack Error: leveldown@1.4.1 install: `prebuild --download`
```

**Comment by mfrost66** [comment]
@No9 I was able to download prebuilt with 4.0.0

**Comment by No9** [comment]
Thanks @mfrost66 really appreciate that 
I can go to bed happy now

**Comment by ralphtheninja** [comment]
@No9 Awesome. And yes, prebuild tries to load the downloaded module.

**Comment by brett19** [comment]
https://github.com/mafintosh/node-gyp-install/pull/11

**Comment by brett19** [comment]
I should note that the "build premature close" error that @rvagg (and I) encountered still appears to be an issue.  It seems to occur transiently and with the fix above builds succeed the majority of the time.  I cannot however seem to identify where the "premature close" line originates from.

**Comment by brett19** [comment]
@rvagg Finally succeeded in resolving the 'premature close' issue.  See:
https://github.com/mafintosh/node-gyp-install/pull/12

**Comment by ralphtheninja** [comment]
@mfrost66 Can this issue be closed now?

**Comment by brett19** [comment]
Latest prebuild fixes "premature close" as well.  All issues mentioned in this ticket should be resolved with the latest prebuild version.

**Comment by pigchao** [comment]
> I got this dam same problem for days, installing node, node-gyp, msbuild tools, uninstalling, reinstalling, configuring, reconfiguring, ... twisted my windows 10 and retwisted, ... ty Brett, I finally got it by "npm install -g node-gyp-install" then "node-gyp-install" then my problem was S.O.L.V.E.D yay! tyvm
> nodejs: 8.11.4
> npm: 5.6.0
> node-gyp; 3.8.0

Great！！！
