### ISSUE TITLE
missing release for node 4.0 / windows x86

### ISSUE THREAD

**Issue by thunder7553** [Level/leveldown#224]
I am using Visual Studio 2015 on Windows 10 and I cannot compile leveldown (which is a separate matter). But I cannot download the prebuild binaries either. I started "npm install leveldown --verbose" and saw that it wants to download following file:

https://github.com/level/leveldown/releases/download/v1.4.1/leveldown-v1.4.1-node-v46-win32-ia32.tar.gz

Unfortunatly, I do not see a 32bit Version of that (only the 64bit). Is 32bit not supported anymore?

**Comment by ralphtheninja** [comment]
@thunder7553 Our aim is to support 32 bit windows and we're working on it.

**Comment by thunder7553** [comment]
In 1.4.2, there is no 32 bit windows support either. Can I help out somehow?

**Comment by ralphtheninja** [comment]
@No9 Got time to build some? :)

**Comment by No9** [comment]
Failed on a creating a dual build environment when I did the 1.4.2 builds the other day.
Will keep chipping away at it.

**Comment by appelgriebsch** [comment]
I've managed to have a working x64 build of it on my Windows 7 / VS 2013 work environment... if interested I can make it available for you (the binary, not the environment for sure :)).

**Comment by No9** [comment]
Thanks @appelgriebsch but we have binaries Winx64 available here https://github.com/level/leveldown/releases/ 
These are used and installed by leveldown via prebuild

**Comment by No9** [comment]
Hey @thunder7553 we now have Winx86 as prebuilds.
If these workout for you please close this issue thanks

**Comment by thunder7553** [comment]
@No9 I tested it, and it works! Thank you very much!
