### ISSUE TITLE
prebuild --download hangs & fails behind proxy

### ISSUE THREAD

**Issue by zaceno** [Level/leveldown#226]
Best guess: prebuild isn’t using my proxy settings. Even though they are set in environment variables, npm config AND command line flags.

Command:

```

sudo npm install leveldown --verbose --global --insecure --without-ssl --strict-ssl=false --proxy=http://xxxxx:3128 --https-proxy=http://xxxxxx:3128

```

Console output (just the last part)

```
npm info install leveldown@1.4.1

> leveldown@1.4.1 install /usr/local/lib/node_modules/leveldown
> prebuild --download

prebuild http request GET https://github.com/level/leveldown/releases/download/v1.4.1/leveldown-v1.4.1-node-v46-darwin-x64.tar.gz
prebuild WARN install socket hang up
prebuild info install Falling back to compilation
prebuild http request https://nodejs.org/dist/v4.1.1/node-v4.1.1.tar.gz
prebuild ERR! build connect ENETUNREACH 104.20.23.46:443
npm verb unsafe-perm in lifecycle false
npm info leveldown@1.4.1 Failed to exec install script
npm verb unlock done using /Users/zache/.npm/_locks/leveldown-8847a5c85fdd2424.lock for /usr/local/lib/node_modules/leveldown
npm verb stack Error: leveldown@1.4.1 install: `prebuild --download`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:817:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid leveldown@1.4.1
npm verb cwd /Users/zache/Code/queues
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "leveldown" "--verbose" "--global" "--insecure" "--without-ssl" "--strict-ssl=false" "--proxy=http://xxxx:3128" "--https-proxy=http://xxxxx:3128"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.1 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.4.1 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild lib/node_modules/leveldown
npm info preuninstall leveldown@1.4.1
npm info uninstall leveldown@1.4.1
npm verb unbuild rmStuff leveldown@1.4.1 from /usr/local/lib/node_modules
npm info postuninstall leveldown@1.4.1
npm verb gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/leveldown

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/Code/queues/npm-debug.log

```

**Comment by zaceno** [comment]
... also, could you advise me on a manual workaround?

I can of course download the prebuilt `https://github.com/level/leveldown/releases/download/v1.4.1/leveldown-v1.4.1-node-v46-darwin-x64.tar.gz` -- but how do I go about unpacking and manually putting it in my local node_modules, to satisfy other packages that depend on leveldown?

**Comment by ralphtheninja** [comment]
@zaceno You could try to update the local prebuild dependency in leveldown, e.g. `npm i prebuild@2.6.0` and then try installing again

**Comment by ralphtheninja** [comment]
@zaceno Also, could you paste the complete verbose output in a gist?

**Comment by zaceno** [comment]
Managed to force the leveldown install to use prebuild v 2.6.0 by making a package.json and npm-shrinkwrap.json. Verbose output of this found here: https://gist.github.com/zaceno/4e77122c2a3823e8a0ec

... but as you can see, the problem remains.

Again: since I am able to download the prebuild manually -- is there any way I can cobble things together manually to make npm and dependent packages (pouchdb specifically) happy?

**Comment by ralphtheninja** [comment]
If you download the `.tar.gz` file to the root of `leveldown` folder you can just unpack it and it will end up in `build/Release/leveldown.node`

![unpack](https://cloud.githubusercontent.com/assets/308049/10218624/8937934c-6838-11e5-80d3-384bab674776.png)

**Comment by ralphtheninja** [comment]
@zaceno Ok, so that was the log from the last output. Mind pasting the original problem? If prebuild fails for some reason it should fallback to building the binaries and I want to find out why that doesn't happen.

**Comment by zaceno** [comment]
Yes, the gist was from when I used prebuild@2.6.0. It did fallback to trying to build from source (but building from source failed for some other reason). I'll get back to you with the original problem shortly.  Trying your suggestion of putting the prebuild inside node_modules/leveldown a t m.

**Comment by zaceno** [comment]
Here's full verbose output of original problem: https://gist.github.com/zaceno/126a2ad71c44157e25f7

**Comment by zaceno** [comment]
Unfortunately I wasn't able to just unpack the prebuilt in my node_modules/leveldown

(failed install means I had no leveldown. So I downloaded from github, and tried to run npm install. Even though the build is there, I wasn't able to hack the package.json to make it stop trying to rebuild from source on npm install)

**Comment by juice49** [comment]
I've just encountered this issue. Did you figure out the cause or a workaround?

**Comment by zaceno** [comment]
afraid not. :( I "solved" it by temporarily connecting from outside our corporate proxy, and doing `npm install leveldown`.  npm caches the prebuilt binary (I presume) so I can now do npm install pouchdb et c in every project I need it, without problems. ...until I clean npm's cache that is

**Comment by juice49** [comment]
Hmm okay, I'll try that out! Thanks for the help 😊.

**Comment by juice49** [comment]
I managed to fix this in the end, although I think I was likely experiencing a different problem. Our RHEL server had an old version of gcc (< 4.8) that was failing to compile leveldown.

If `gcc -v` shows a version less than 4.8, maybe this is same problem. I read about this in another issue, but afraid I can't find the link now.

**Comment by rsfernandes** [comment]
Using the 1.6.0 version the --build-from-source works and the process don't try to download the prebuild binaries.

**Comment by ralphtheninja** [comment]
We use `prebuild-install` now which should have support for proxies. See https://github.com/mafintosh/prebuild-install/commit/5993c1676c7530ecdc12409cb20cf6a39c0e47c7
