### ISSUE TITLE
Prebuilt binaries are being used even with --build-from-source option

### ISSUE THREAD

**Issue by wgiroir** [Level/leveldown#228]
I am attempting cross compile leveldown for arm using OpenEmbedded Yocto.

The command being run to build leveldown is
`npm i --verbose --debug --build-from-source --target_arch=ia32 --target_platform=linux`

Npm is getting the correct options as you can see in the output

`npm info it worked if it ends with ok`
`npm verb cli [ '/usr/local/bin/node',`
`npm verb cli   '/usr/local/bin/npm',`
`npm verb cli   'i',`
`npm verb cli   '--verbose',`
`npm verb cli   '--debug',`
`npm verb cli   '--build-from-source',`
`npm verb cli   '--target_arch=ia32',`
`npm verb cli   '--target_platform=linux' ]`
`npm info using npm@1.3.21`
`npm info using node@v0.10.24`

Not only is npm pulling down the prebuilt binary, it is pulling down the x86 binary

`prebuild --download`
`prebuild info looking for local prebuild @ prebuilds/leveldown-v1.4.1-node-v11-linux-x64.tar.gz`
`prebuild info not found. downloading...`
`prebuild info unpack required /home/walt/workspace/42/wwrelay-rootfs/yocto/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/leveldown/1.0+gitAUTOINC+86b96a823f-r1/git/build/Release/leveldown.node` `successfully`
`prebuild info install Prebuild successfully installed!`
`npm verb unsafe-perm in lifecycle true`
`npm info postinstall leveldown@1.4.1`
`npm info prepublish leveldown@1.4.1`
`bindings@1.2.1 node_modules/bindings`

**Comment by wgiroir** [comment]
This issue has been recreated outside of the cross compile environment

* git clone git@github.com:Level/leveldown.git

* cd leveldown

* npm  i --build-from-source --verbose >& /tmp/a

* fgrep -n leveldown.node /tmp/a
14702:prebuild info unpack required /home/walt/workspace/leveldown/build/Release/leveldown.node successfully

* md5sum /home/walt/workspace/leveldown/build/Release/leveldown.node
e04c04b7eb6e58db7224a7a9eea3abc2  /home/walt/workspace/leveldown/build/Release/leveldown.node

* mkdir /tmp/b ; cd /tmp/b

* wget https://github.com/Level/leveldown/releases/download/v1.4.1/leveldown-v1.4.1-node-v11-linux-x64.tar.gz

* tar xzf leveldown-v1.4.1-node-v11-linux-x64.tar.gz

* md5sum build/Release/leveldown.node 
e04c04b7eb6e58db7224a7a9eea3abc2  build/Release/leveldown.node

**Comment by ralphtheninja** [comment]
@wgiroir On it.

**Comment by wgiroir** [comment]
I reviewed the package.json file and found a solution/workaround for this one.
I can, as your README.md suggest, use `npm run rebuild`

Now just need a successful build

**Comment by ralphtheninja** [comment]
@wgiroir I've patched prebuild now. Mind testing out `npm i --build-from-source` again? Wipe `node_modules` folder first :)

**Comment by wgiroir** [comment]
@ralphtheninja Absolutely.  Thanks for the quick patch.  I'll give you an update in the next few hours

**Comment by wgiroir** [comment]
This is fixed
