### ISSUE TITLE
Build failure on OSX 10.6

### ISSUE THREAD

**Issue by MidnightLightning** [Level/leveldown#232]
Just updated to Node v4.2.1 (via MacPorts), and now my LevelDB installation won't work (specifically, LevelUP NPM module can't find LevelDown). Running `npm install leveldown` results in the error:

```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/boydb/.node-gyp/4.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  g++ '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DSNAPPY=1' '-DLEVELDB_PLATFORM_POSIX=1' '-DOS_MACOSX=1' -I/Users/boydb/.node-gyp/4.2.1/src -I/Users/boydb/.node-gyp/4.2.1/deps/uv/include -I/Users/boydb/.node-gyp/4.2.1/deps/v8/include -I../deps/leveldb/leveldb-1.14.0 -I../deps/leveldb/leveldb-1.14.0/include -I../deps/snappy/snappy-1.1.1  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o.d.raw  -c -o Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o ../deps/leveldb/leveldb-1.14.0/db/builder.cc
cc1plus: error: unrecognized command line option "-std=gnu++0x"
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/boydb/Documents/db/node_modules/leveldown
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

Namely, `-std=gnu++0x` is not recognized; not supported on OSX 10.6?

**Comment by rvagg** [comment]
> Namely, -std=gnu++0x is not recognized; not supported on OSX 10.6?

Yeah, I think so, 10.6 is kind of ancient. Does `npm install leveldown` not find a binary for you? It should grab one so you don't need to compile. Can you post the full npm output please? Perhaps you are running a 32-bit system, in which case I doubt there's a binary for you.

**Comment by MidnightLightning** [comment]
No, it doesn't find a binary; that was the command I ran to get that error. It is an older MacPro (2008 model). It does have Intel (Xeon) processors (two dual-core 64-bit 3.0 GHz processors), so hopefully is still compatible. That box is stuck on 10.6 due to graphics card not meeting the requirements for 10.7.

Install log posted to http://pastebin.com/mk4f41X6

**Comment by pietercolpaert** [comment]
Same problem on Ubuntu, same node version

**Comment by No9** [comment]
Hey @MidnightLightning That looks like it's installing 0.10.x for some reason?
`npm verb addNamed "0.10.5" is a plain semver version for leveldown
npm verb addNamed ">=0.10.4 <0.11.0" is a valid semver range for leveldown` 
among other references in that paste bin.

Which is weird considering it's a plain `npm install leveldown`
Can you run 
`npm install leveldown@1.4.2` and confirm the same issue persists. 
Thanks

**Comment by MidnightLightning** [comment]
Oh that's it, I'm just way out of date on versions; I was working in projects with a `package.json` that specified `0.10.5`. Upping that to `1.4.2` did find a binary to download, and that works just fine.
