### ISSUE TITLE
installation error on windows 10

### ISSUE THREAD

**Issue by barbalex** [Level/leveldown#233]
leveldown is included in my project as part of pouchdb

when I run `npm install` I get this error:

    C:\Users\alex\ae\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\alex\AppData\Roaming\npm\nod
    e_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Si
    e den Schalter "/m" hinzufügen.
      bufferutil.cc
      win_delay_load_hook.c
         Bibliothek "C:\Users\alex\ae\node_modules\bufferutil\build\Release\bufferutil.lib" und Objekt "C:\Users\alex\ae\no
      de_modules\bufferutil\build\Release\bufferutil.exp" werden erstellt.
      Code wird generiert.
      Codegenerierung ist abgeschlossen.
      bufferutil.vcxproj -> C:\Users\alex\ae\node_modules\bufferutil\build\Release\\bufferutil.node

    > leveldown@1.4.2 install C:\Users\alex\ae\node_modules\leveldown
    > prebuild --download

    Der Befehl "prebuild" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.

    npm WARN EPACKAGEJSON ae@1.0.0 No repository field.
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alex\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm
    -cli.js" "i"
    npm ERR! node v5.0.0
    npm ERR! npm  v3.3.6
    npm ERR! code ELIFECYCLE
    npm ERR! leveldown@1.4.2 install: `prebuild --download`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild --download'.
    npm ERR! This is most likely a problem with the leveldown package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     prebuild --download
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls leveldown
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\alex\ae\npm-debug.log

So building my project is not any more possible.

What can I do?

By the way: I have an OsX notebook and the error does not occur on that.

**Comment by juliangruber** [comment]
It can't find the `prebuild` command, which is weird because it should have been installed by npm beforehand. Can you try again after completely removing the `node_modules` forlder in your project?

**Comment by juliangruber** [comment]
_could_ also be a path issue. can you past the output of `npm ls` __before__ removing node_modules as advised above?

**Comment by barbalex** [comment]
here is the output from `npm ls`: https://gist.github.com/barbalex/591009d3e9514198eafb

**Comment by barbalex** [comment]
regenerating node_modules solved the problem, thanks!
