### ISSUE TITLE
`prebuild` not found with npm 2.14.7

### ISSUE THREAD

**Issue by julien-f** [Level/leveldown#234]
Installing only leveldown works but installing both leveldown and prebuild fails:

```
> npm i prebuild leveldown
 
> leveldown@1.4.2 install /root/tmp/node_modules/leveldown
> prebuild --download

sh: 1: prebuild: not found
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "prebuild" "leveldown"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leveldown@1.4.2 install: `prebuild --download`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/tmp/npm-debug.log
```

**Comment by julien-f** [comment]
It seems that changing the `install` script to `postinstall` fixes the issue.

**Comment by ralphtheninja** [comment]
Ouch. I'm on it.

**Comment by julien-f** [comment]
It seems better with `postinstall` but there still are some issues: I still get the error when I do `npm rebuild` in my project :/

**Comment by ralphtheninja** [comment]
@julien-f I can fix the `postinstall` quick. Is your project open source or can you produce something that I can run to reproduce?

**Comment by julien-f** [comment]
The project is open source, but I am trying to figure out how exactly to reproduce the issue.

**Comment by ralphtheninja** [comment]
Now I remember why I picked `install` instead of `postinstall`. If you do `npm i` inside leveldown source then npm will first try to build everything and then run prebuild --download after that.

**Comment by julien-f** [comment]
The project is [vatesfr/xo-server#next-release](https://github.com/vatesfr/xo-server/tree/next-release) and the issue mainly occur when the dependencies are bundled as you can see with [this package](https://cloud.vates.fr/index.php/s/t1MrHLI784ucdXr).

**Comment by ralphtheninja** [comment]
> It seems that changing the install script to postinstall fixes the issue.

How did you test this?

**Comment by julien-f** [comment]
First I tested by creating a local copy of leveldown and editing manually the `package.json`: it fixes the first use case (`npm i prebuild ./leveldown`).

I also edited leveldown inside the `xo-server` package but I did not get the same success:
- `npm rebuild` fails with *leveldown@1.4.2 install: `prebuild --download`*
- `npm start` fails with:
```
/tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/build/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/build/Debug/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/build/Release/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/out/Debug/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/Debug/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/out/Release/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/Release/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/build/default/leveldown.node
 → /tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/compiled/4.2.1/linux/x64/leveldown.node
    at bindings (/tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/tmp/node_modules/xo-server/node_modules/level/node_modules/leveldown/leveldown.js:4:46)
    at Object.<anonymous> (/tmp/node_modules/xo-server/node_modules/level/level.js:1:44)
    at Object.<anonymous> (/source/xo.js:10:38)
    at Object.<anonymous> (/source/index.js:35:32)
    at Object.<anonymous> (/tmp/node_modules/xo-server/index.js:11:18)
    at Object.<anonymous> (/tmp/node_modules/xo-server/bin/xo-server:10:25)
```

**Comment by ralphtheninja** [comment]
Are you doing `npm rebuild` because you're targeting multiple platforms?

**Comment by julien-f** [comment]
Yes, I deploy the software as a single npm package and the `npm rebuild` in `postinstall` ensures (at least AFAIU :p) that compiled package are properly rebuild against the correct version of Node.

**Comment by ralphtheninja** [comment]
> Yes, I deploy the software as a single npm package and the npm rebuild in postinstall ensures (at least AFAIU :p) that compiled package are properly rebuild against the correct version of Node.

Checking the `xo-server` code but I don't see any `postinstall` step there. Is that the project you're referring to or is it something else? The point of using `prebuild` in leveldown is just that use case, to be able to install binaries for the correct version of node, so I don't see why you need to rebuild. I must be missing something :)

**Comment by ralphtheninja** [comment]
I know you have multiple issues here but lets address your original problem with `npm i leveldown prebuild` not working. To me this feels like a npm bug since `npm i leveldown` actually works. I have tested this with `npm@3.3.6` and it works fine.

So a workaround for this right now (as I see it) is either:

1. You install `prebuild` and `leveldown` separately (as in not in a single command)
2. Upgrade npm

The reason why prebuild does the download during the install phase and not during postinstall is that if we *don't* then npm will try to build leveldown because a missing `"install"` in package.json will default to `"install": "node-gyp rebuild"` (see https://docs.npmjs.com/files/package.json#default-values) which is something we don't want, since it would defeat the purpose of having prebuilt binaries in the first place :)

Technically we *could* do something like `"install": "true"` or `"install": "echo"` together with `"postinstall": "prebuild --download"` but that is a really ugly hack, just for the purpose of circumventing a problem inside npm.

**Comment by ralphtheninja** [comment]
@Level/owners Anyone else feel like chipping in?

**Comment by ralphtheninja** [comment]
@julien-f As for your other problems. Please open a new issue or ping me on irc (freenode) and we can walk through them together. Github issues are good but not ideal for real time things :)

**Comment by juliangruber** [comment]
i agree with @ralphtheninja that updating npm should work best

**Comment by julien-f** [comment]
We succeeded in updating npm for all our customers but unfortunately we face another issue (#236) which I do not know if it is a npm or a leveldown issue.

**Comment by ralphtheninja** [comment]
May I ask why you are bundling your dependencies (and leveldown) in the first place?

**Comment by julien-f** [comment]
It eases deployment on our customers' machines which often don't have direct access to internet (and therefore npmjs.org).

**Comment by julien-f** [comment]
I am open to any suggestions :)

**Comment by ralphtheninja** [comment]
> It eases deployment on our customers' machines which often don't have direct access to internet (and therefore npmjs.org).

Ok. So how do you deploy it if they don't have direct access to internet? What OS are they running?

**Comment by julien-f** [comment]
The are running Debian 7 and we are deploying via a custom updater which downloads the packages on our server, sometimes via a proxy.
We could use configure the proxy in npm but it has other issues (e.g. npm/npm#3559) which we do not have with bundle packages.

There is another benefit: it does not matter when the bundled package is installed, it always comes the same versions of the dependencies (even if they have been deleted from npmjs… yes, it happened).

**Comment by ralphtheninja** [comment]
If everyone is running Debian 7, can't you just build the package once and be done with it? That would be even better for them since they don't need a build environment installed.

**Comment by ralphtheninja** [comment]
That said, it should still work of course. Just saying :)

**Comment by julien-f** [comment]
> If everyone is running Debian 7, can't you just build the package once and be done with it? That would be even better for them since they don't need a build environment installed.

They don't all have the same version of Node :/

**Comment by ralphtheninja** [comment]
> They don't all have the same version of Node :/

Oh of course. Sorry for stupid questions. Just trying to wrap my head around your use case.

**Comment by julien-f** [comment]
No problem :)

**Comment by ralphtheninja** [comment]
So we can assume they are running *any* version of node?

**Comment by DonutEspresso** [comment]
For anyone else out there running into this - I had this issue too, turns out it's because my shrinkwrap is generated by npm3, but my build slaves were using npm2. Moving my build slaves to use npm3 fixed the issue. Thank goodness for search, the error messages and npm debug logs were not particularly helpful!
