### ISSUE TITLE
DLL open failed when running with electron (windows 10)

### ISSUE THREAD

**Issue by dominictarr** [Level/leveldown#239]
running the prebuilt leveldown with electron fails although with node (4.2.3) it works.

I got this error, it wasn't very informative...

```
Error: A dynamic link library (DLL) initialization routine failed.
c:\code\patchwork\node_modules\leveldown\build\Release\leveldown.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:140:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (c:\code\patchwork\node_modules\leveldown\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (c:\code\patchwork\node_modules\leveldown\leveldown.js:4:46)
    at Module._compile (module.js:434:26)
```

**Comment by dominictarr** [comment]
Maybe we can compile leveldown with emscripten? at least javascript is portable

**Comment by No9** [comment]
Look at this sample project from @ralphtheninja
https://github.com/Level/electron-demo/blob/master/package.json

It looks like electron is not ABI compatible with node so you have to rebuild level using post install magic 
Maybe a feature req for prebuild :)
Do you have a windows build environment?

**Comment by dominictarr** [comment]
> Do you have a windows build environment? 

:sob: , no but I want one. the closest I have got so far msbuild.exe is installed and it's not complaining about vcbuild.exe missing but hundreds of errors about all the header files being missing. standard header files like `stdio.h`

**Comment by dominictarr** [comment]
prebuild+electron works on linux (and mac too i bet)

**Comment by No9** [comment]
I see it's for patchwork and that builds a 32bit version :/ I can't do anything right now but I might get 10 mins to run that patchwork build tomorrow and give you the output?

**Comment by dominictarr** [comment]
That would be awesome, thanks!!!

**Comment by dominictarr** [comment]
Oh also, have a go at https://github.com/dominictarr/chloridedown we need this for crypto. It's just my branch of sodium - I removed some stuff that didn't seem necessary to get rid of dependencies on make, automake, libtoolize, still builds on linux. Then we'd have a full windows build!!!

**Comment by ralphtheninja** [comment]
> Look at this sample project from @ralphtheninja
> https://github.com/Level/electron-demo/blob/master/package.json
> 
> It looks like electron is not ABI compatible with node so you have to rebuild level using post install magic
> Maybe a feature req for prebuild :)
> Do you have a windows build environment?

I can't take credit for that :) @juliangruber hacked it together

**Comment by ralphtheninja** [comment]
> It looks like electron is not ABI compatible with node so you have to rebuild level using post install magic
> Maybe a feature req for prebuild :)

That's a good idea. I spoke with @mafintosh about that as well and it would be nice to have something that "just works" for native modules running in the electron environment.

**Comment by No9** [comment]
Hey @dominictarr as you suspected it died on chloride down.
I remember trying to move node-sodium to windows gyp build a long time ago and never got it solved :( 
And after that I wouldn't fancy trying to take on chloridedown TBH

I see libsodium have since included Visual Studio Build Files and that came into node-sodium at the start of the year.
https://github.com/paixaop/node-sodium/blob/master/deps/libsodium/libsodium.sln  
 
It might be a simpler option to go back to node-sodium and have windows specific prebuild command that runs the visual studio project then then ignores the dependency https://github.com/paixaop/node-sodium/blob/master/binding.gyp#L12?

Sorry it wasn't better news

**Comment by dominictarr** [comment]
@No9 what was the error? Did you use the `simplify` branch?

It really shouldn't be that hard to build sodium - it's just C, there are lots of files, but it has no external dependencies etc. I suspect what makes it hard is toolchain dependencies
for example:

https://github.com/paixaop/node-sodium/blob/master/Makefile#L7-L10
defines.js is a node script that uses regexps to copy some defines from the automake output to `./deps/libsodium.gyp`. :mask: but I just removed that stuff, and checked in a libsodium.gyp without any extra defines and now no automake dependency and it still builds just fine on linux. plus you don't need automake.

**Comment by dominictarr** [comment]
@No9  if you got a build of leveldown that works with electron on windows that is still progress because at least it means we can run patchwork with the sodium-browserify

**Comment by No9** [comment]
@dominictarr I did not see the simplify branch! That is very interesting

It's all meetups and christmas parties for the rest of the week :) but I will try that branch over the weekend. 

For the leveldown electron I was hoping to get some prebuild magic from @ralphtheninja or @mafintosh then just run it (He hinted) but if i get bandwidth Ill give it a spin after chloride

**Comment by dominictarr** [comment]
@No9 awesome thanks!

**Comment by No9** [comment]
@dominictarr can you enable issues on chloridedown so we can track the build progress there?

**Comment by ralphtheninja** [comment]
We build for electron + windows now.
