### ISSUE TITLE
Implement CompactRange

### ISSUE THREAD

**Issue by rvagg** [Level/leveldown#24]
This is pretty hard-core, but if you've know you've been doing some heavy work in a particular (not too big) key range then you could order a compaction of that range rather than waiting for leveldb to get around to the range (it normally works its way sequentially through the key ranges that make up files at each "level").

Might be handy, but it might also be best to wait for someone to request that we implement this feature?

``` c++
  // Compact the underlying storage for the key range [*begin,*end].
  // In particular, deleted and overwritten versions are discarded,
  // and the data is rearranged to reduce the cost of operations
  // needed to access the data.  This operation should typically only
  // be invoked by users who understand the underlying implementation.
  //
  // begin==NULL is treated as a key before all keys in the database.
  // end==NULL is treated as a key after all keys in the database.
  // Therefore the following call will compact the entire database:
  //    db->CompactRange(NULL, NULL);
  virtual void CompactRange(const Slice* begin, const Slice* end) = 0;
```

**Comment by bookchin** [comment]
Implemented by https://github.com/Level/leveldown/pull/340 😄
