### ISSUE TITLE
should we update 0.10 branch to support node 5?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#246]
Any thoughts on this?

cc @Level/owners

**Comment by juliangruber** [comment]
maybe let's wait if there's interest?

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/issues/244

**Comment by juliangruber** [comment]
ah I didn't remember that. +1 from me then!

**Comment by ralphtheninja** [comment]
It's sort of annoying though that if we fix this and publish e.g. 0.10.6 then that will be the latest release for leveldown

**Comment by juliangruber** [comment]
we can publish under the 0.10 tag so people only get it if they want it

**Comment by juliangruber** [comment]
but yeah i'm fine with people upgrading, unless there's a really compelling reason to support the old version

**Comment by mafintosh** [comment]
i'd personally just support the latest version.

**Comment by ralphtheninja** [comment]
Ok, so lets leave this hanging for a while, until someone *really* needs it.

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/pull/248
