### ISSUE TITLE
Compiler error when using Visual Studio 2015 on Windows 7

### ISSUE THREAD

**Issue by strrchr** [Level/leveldown#247]
```
d:\home\js\modules_by_npm\node_modules\leveldown\deps\leveldb\port-libuv\stdint-msvc2008.h(109): error C2371: 'uint_fast16_t': red efinition; different basic types (compiling source file leveldb-1.18.0\db\filename.cc) [D:\home\js\modules_by_npm\node_modules\lev eldown\deps\leveldb\leveldb.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(40): note: see declaration of 'uint_fast16_t' (compiling
   source file leveldb-1.18.0\db\filename.cc)
```
The errors are like the above.
I modify some part of deps\leveldb\port-libuv\port_uv.h from
```
#elif defined(_MSC_VER)
  #include "stdint-msvc2008.h"
  #define PLATFORM_IS_LITTLE_ENDIAN true
  #define snprintf _snprintf
```
to
```
#elif defined(_MSC_VER)
// MSVC++ 14.0 _MSC_VER == 1900 (Visual Studio 2015)
#if _MSC_VER < 1900
  #include "stdint-msvc2008.h"
#endif
  #define PLATFORM_IS_LITTLE_ENDIAN true
#if _MSC_VER < 1900
  #define snprintf _snprintf
#endif
```
Then the compilation is OK.
Is it the correct solution?
It would be nice if the problem is fixed.

**Comment by obastemur** [comment]
Looks like I forgot bringing the fix from `leveldown-mobile` https://github.com/Level/leveldown-mobile/blob/master/deps/leveldb/port-libuv/port_uv.h#L29-L33

@strrchr almost correct solution. I'm going to PR `port_uv.h` from leveldown-mobile and see what other folks will say.

**Comment by ralphtheninja** [comment]
> Then the compilation is OK.
> Is it the correct solution?
> It would be nice if the problem is fixed.

If it compiles the tests run it should be OK. At least an improvement from not compiling :)
