### ISSUE TITLE
Travis: make: g++-4.8: Command not found

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/leveldown#253]
leveldown@1.4.4

Much errorness when building on Travis today. Is this a problem with Travis, or with leveldown? I havent changed my build config. Is there a new magic incantation to get leveldown to build on Travis?

https://travis-ci.org/fergiemcdowall/search-index/jobs/108820234

**Comment by ralphtheninja** [comment]
@fergiemcdowall You need at least gcc 4.8 to build c++11 code, see leveldowns travis file:

https://github.com/Level/leveldown/blob/master/.travis.yml#L5-L13

**Comment by ralphtheninja** [comment]
On a side note. Any special reason you are building it? There should be prebuilt binaries for you.

**Comment by ralphtheninja** [comment]
If you don't need to build it, you can remove the following lines from your `.travis.yml` https://github.com/fergiemcdowall/search-index/blob/master/.travis.yml#L15-L17

**Comment by fergiemcdowall** [comment]
Oh- thats a good tip- trying it now...

**Comment by ralphtheninja** [comment]
Hmm, I just noticed that you are in fact using gcc 4.8, so it *should* work building it with your current `.travis.yml`.

**Comment by fergiemcdowall** [comment]
Ahhhh... trying it anyway just in case. Yes, my `.travis.yml` has been working up until now

I wonder if Travis is just having a bad day

**Comment by ralphtheninja** [comment]
Travis often have bad hair days :/

**Comment by fergiemcdowall** [comment]
It does indeed- I think that was my cue to pack up and go home!

Thanks for the help :)

**Comment by ralphtheninja** [comment]
> It does indeed- I think that was my cue to pack up and go home!
> 
> Thanks for the help :)

Let me know how things work out!

**Comment by fergiemcdowall** [comment]
will do

**Comment by fergiemcdowall** [comment]
It magically started compiling on Travis again all by itself :tada: 

Maybe Travis was having a bad hair day

**Comment by ralphtheninja** [comment]
It did, I had the same problems yesterday. Happy it worked out!
