### ISSUE TITLE
random travis fails

### ISSUE THREAD

**Issue by juliangruber** [Level/leveldown#257]
this week two builds failed but passed on 2nd run. different node versions, different errors. we need to investigate what's happening there.

i guess we'd start by trying to cause build failure locally?

**Comment by ralphtheninja** [comment]
+1

**Comment by rvagg** [comment]
would removing io.js help?

```
  - "3"
  - "2"
  - "1.8"
  - "1.0"
```

These are no longer supported upstream

**Comment by juliangruber** [comment]
iirc there was one on node 4 as well, but anyway +1 on removing unsupported versions

**Comment by rvagg** [comment]
can we put some links in here to failed builds as they happen to collect the pattern?

**Comment by juliangruber** [comment]
unfortunately it seems like triggering a rebuild will overwrite the previous build..at least i couldn't find any in the travis build history

**Comment by juliangruber** [comment]
this is one that failed first: https://travis-ci.org/Level/leveldown/jobs/108674087

**Comment by ralphtheninja** [comment]
We could make `travis` branch and just re-run it until it fails, save the log, re-run etc. Maybe also contact travis to get some more information from them?

**Comment by juliangruber** [comment]
https://twitter.com/juliangruber/status/699013604205600768

**Comment by juliangruber** [comment]
@ralphtheninja that sounds perfect!

**Comment by ralphtheninja** [comment]
> would removing io.js help?
> 
>   - "3"
>   - "2"
>   - "1.8"
>   - "1.0"

I can start by removing those.

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/pull/258

**Comment by rvagg** [comment]
OK, so how about we use this as a dumping ground for failed builds, when you see one fail, capture the output around the failure and paste it in here.

**Comment by ralphtheninja** [comment]
> OK, so how about we use this as a dumping ground for failed builds, when you see one fail, capture the output around the failure and paste it in here.

+1 Put it in a gist and link it here.

**Comment by ralphtheninja** [comment]
We haven't gotten any random failures in quite a while now. Closing.
