### ISSUE TITLE
Aggregation of key/values?

### ISSUE THREAD

**Issue by braydonf** [Level/leveldown#261]
After testing using the `highWaterMark` option for the db iterator with modifications to give the entire cache array instead of each item individually I was able to see up to ~8x speed improvements.

Would it be useful to have an additional iterator/aggregation method to help in the case that each key/value isn't needed but an aggregate? For example:

``` js
function getSum(startDateKey, endDateKey, callback) {
  db.aggregator({
    gt: Buffer.concat([startDateKey, new Buffer('00', 'hex')]),
    lt: Buffer.concat([endDateKey, new Buffer('ff', 'hex')]),
    keys: false,
    values: true
  }, function(values) {
     var sum = values.reduce(function(a, b) {
       return a + b.readDoubleBE()
     }, 0) 
     return [sum, values.length];
  }, function(err, result) {
    if (err) {
      return callback(err)
    }
    callback(null, {sum: result[0], total: result[1]}}
  });
}
```

**Comment by ralphtheninja** [comment]
This looks cool. What would `db.aggregator()` look like/do more concretely?

**Comment by dominictarr** [comment]
@braydonf can you describe the modifications? there is a pretty high bar for adding a feature to level, but if you can show that something is slowing it down (especially by 8x) then that would be something we are _very interested_ in.

**Comment by braydonf** [comment]
@dominictarr Changes were to return the cache instead of iterating over each item in the cache ( https://github.com/braydonf/leveldown/commit/ae98b0676454cae268c551ef97b387601913dea8 ) However after running these again the performance difference isn't as significant as a previous attempt:
```
iterator:
milliseconds 2278
count 1000000
iterator (with cache returned):
milliseconds 1844
count 1000000
```

**Comment by braydonf** [comment]
@ralphtheninja I was imagining that iteration over all of the key/values and aggregation would all be done as an AsyncWorker. Would need to test to see the performance gain.

**Comment by braydonf** [comment]
From the benchmarks at https://github.com/google/leveldb sequential reads should be around 0.476 micros/op (1 million sequential reads should be ~500ms?)

**Comment by vweevers** [comment]
Consolidating this into https://github.com/Level/community/issues/70 (which is about read streams, but the [proposed underlying mechanism](https://github.com/Level/community/issues/70#issuecomment-502026423) uses iterators).
