### ISSUE TITLE
Switch to node-pre-gyp?

### ISSUE THREAD

**Issue by appelgriebsch** [Level/leveldown#266]
Hey,

I've seeing various issues when trying to package an ElectronJS application with PouchDB & LevelDB adapter. It all comes down to the prebuild command loading the wrong version of the prebuild binary (module version 46 from nodejs 4.4.x vs. version 47 in Electron 0.37.x).

I just checked the sqlite module (that works flawlessly in this setup) and they are using another prebuild distribution library named node-pre-gyp (that either works with an Amazon S3 bucket or any other HTTP URL to grab the binaries depending on local system setup). As it seems the Electron-packager is already prepared to handle different module versions for node-pre-gyp packages.

As it might be a no-brainer to switch to node-pre-gyp as binary distribution mechanism, do you see anything against doing so (hint: I would even do a pull request for it, if you will accept it)?!

**Comment by ralphtheninja** [comment]
@appelgriebsch Mind describing the use case / issues in more detail? I'd personally much rather try fixing prebuild to play nice with electron-packager.

**Comment by rvagg** [comment]
seems like something to take up with prebuild tbh, if there's a problem there we'd all be better served by having it resolved at the source

**Comment by appelgriebsch** [comment]
I've created an electron-boilerplate project (github.com/appelgriebsch/electron-boilerplate) that uses pouchdb and leveldown. When doing a npm install it automatically fetches the packages and when processing leveldown also downloads the prebuild binary, that matches the local nodejs environment (that's nodejs 4.4.1 with module version 46 in my case). After fetching all application dependencies I trigger an 'electron-rebuild' to rebuild the node binaries for the version that is suited for the current electronjs runtime package (that's electronjs 0.37.2 with module version 37 in this case).

That works well with the node-pre-gyp base node packages (e.g. node-sqlite), but it won't fix the module binary for leveldown, resulting in an error during application startup:
```
leveldb-adapter is not working, fallback to SQLite (websql)
Error: Module version mismatch. Expected 47, got 46. This generally implies that leveldown was built with a different version of node than that which is running now.  You may try fully removing and reinstalling PouchDB or leveldown to resolve
```

**Comment by ralphtheninja** [comment]
@appelgriebsch Got it. Does it matter which branch I use in `electron-boilerplate` to reproduce it? I.e. any out of `angularjs` or `reactjs` I guess?

**Comment by mafintosh** [comment]
@ralphtheninja this gist is a simple reproducible test case as well, https://gist.github.com/mafintosh/aabf2bfd02c87902619f1ebec119433b

**Comment by appelgriebsch** [comment]
@ralphtheninja jepp, best to try it with the angularjs branch

**Comment by juliangruber** [comment]
for me https://github.com/juliangruber/require-rebuild has been working really well, mind giving it a try? just include `require('require-rebuild')()` before any other dependencies and start your app.

**Comment by No9** [comment]
Should mention that I am seeing issues with node-pre-gyp as well. False positive installs being the main one. I don't think there is a panacea here

**Comment by ralphtheninja** [comment]
Should be resolved now since we build for electron as well.
