### ISSUE TITLE
Package doesn't work with Debian Wheezy

### ISSUE THREAD

**Issue by frankrousseau** [Level/leveldown#276]
Hi Level team,

  I just would like to notifiy you that Leveldown can no more be deployed on Debian 7 Wheezy (since the 1.4.5 version, it requires a too high version of libc). It's no more compatible with our setup. It's not a big deal because, at Cozy, we are migrating to Debian 8. But it may be a problem for other organizations. That's why I wanted to tell you about that.

Btw, thank you for that awesome project.

**Comment by ralphtheninja** [comment]
@frankrousseau Thanks for noticing this. We will rebuild them on an older version of libc.

**Comment by ralphtheninja** [comment]
@frankrousseau Is that for 64 bit I guess?

**Comment by ralphtheninja** [comment]
@frankrousseau Mind trying again? @mafintosh just rebuilt them

**Comment by frankrousseau** [comment]
Sorry, but the problem is still here:

```
/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/cozy-indexer/node_modules/search-index/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/cozy-indexer/node_modules/search-index/node_modules/leveldown/build/Release/leveldown.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/cozy-indexer/node_modules/search-index/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
```

When I run `dpkg -l`:

```
dpkg -l | grep libc6
ii  libc6:amd64                     2.13-38+deb7u7                amd64        Embedded GNU C Library: Shared libraries
ii  libc6-dev:amd64                 2.13-38+deb7u7                amd64        Embedded GNU C Library: Development Libraries and Header Files
```

**Comment by mafintosh** [comment]
@frankrousseau you need to delete your local cache as well before re-installing, ~/.npm/_prebuilds/

**Comment by julien-f** [comment]
I still have the error, even after deleting `~/.npm/` and `/tmp/npm-*`.

**Comment by frankrousseau** [comment]
It was the same last time I tried.

**Comment by ralphtheninja** [comment]
@mafintosh Are you sure the linux binaries are built with an older version of glibc? Seems it's still complaining on version 2.14.

**Comment by mafintosh** [comment]
@ralphtheninja to the best of my knowledge. is there a way i can which version of glibc i have installed?

**Comment by ralphtheninja** [comment]
Try `dpkg -l | grep libc6` (I just learned that myself from above)

**Comment by mafintosh** [comment]
oh it says 2.19-18. hmm wonder if something updated libc on my build box

**Comment by ralphtheninja** [comment]
@frankrousseau It should build now. Please re-open if that's still not the case.
