### ISSUE TITLE
incorrect prebuilt binary being installed for current node version

### ISSUE THREAD

**Issue by cdaringe** [Level/leveldown#278]
hi all:

i'm rebuilding `leveldown` for `electron`.  when i run `npm i` or `npm rebuild` using the `electron` node process, my _system node_ version is being used to build, not the version from the process actively running the rebuild or install command (i.e., my electron's node)

this is pretty easy to see.

```
# get my electron node modules version
🛰  cdieringer:~/$ export ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 && /path/to/Electron
> process.versions
{ 
  ...
  modules: '47',
  ... }
>
```

```
# get my system node modules version
🛰  cdieringer:~/node/coinstac-client-core$ node
> process.versions
{ 
  ...
  modules: '46',
  ...
 }
```

great.  so, my sys version is node 4.x/module:46, and my electron version is 5.10/module:47

Thus, my goal is to build against 47.  However, i'm finding that the rebuild command still rebuilds w/ 46.

`export ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 && /path/to/Electron /path/to/npm/bin/npm-cli.js rebuild leveldown --runtime=electron --target=0.37.7 --arch=x64 --verbose --debug`

The full output from the command is [here](https://gist.github.com/cdaringe/3e15594bedfd45bf3c65ec8431681c3f).

I believe that this _used to work_.  Not 100%, but a darn rock solid 75%. :)  Tips?  Thanks!

**Comment by cdaringe** [comment]
full disclosure, i had issues with `electron-rebuild`, so i forked off and created [ionizer](https://www.npmjs.com/package/ionizer).  one of the reasons to do so was because the `rebuild` processes weren't run with the electron node, and some packages' rebuild scripts checked `process.versions` etc to do rebuilds, which consequently ended up never rebuilding with the target `node` version.

**Comment by ralphtheninja** [comment]
I'm wondering if it's a problem related to prebuilds [hash bang](https://github.com/mafintosh/prebuild/blob/master/bin.js#L1)

cc @mafintosh

**Comment by cdaringe** [comment]
@ralphtheninja. good thought.  The above cmd fails, as explained, but so does the ionizer command.  The reason I'm skeptical about the hash being the root cause is because ionizer uses https://github.com/cdaringe/squish-squash, so I have high confidence that the right node would be used.  I'll write a test over in that repo to test your suggestion!

**Comment by ralphtheninja** [comment]
> I'll write a test over in that repo to test your suggestion!

Cool!

**Comment by cdaringe** [comment]
well, i wrote [the test](https://github.com/cdaringe/squish-squash/blob/master/test/index.js#L73).  i regret to inform that `#!` still does honor the squashed version of node.  bummer.

so, still seeking tips!  thx.

**Comment by juliangruber** [comment]
@cdaringe try running the script via `node script.js` instead of `./script.js`

**Comment by cdaringe** [comment]
hey @juliangruber, apologies, can you specify further?  which do you mean?  thanks!

**Comment by ralphtheninja** [comment]
Should be resolved now since we also build for electron.
