### ISSUE TITLE
prebuild --install fails on Node 6

### ISSUE THREAD

**Issue by capaj** [Level/leveldown#279]
see https://api.travis-ci.org/jobs/125934637/log.txt?deansi=true

**Comment by ralphtheninja** [comment]
From the log output you just linked

> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

**Comment by ralphtheninja** [comment]
Just updated leveldown on travis to use node 6 and it builds fine https://github.com/Level/leveldown/pull/280, you can take a peek at leveldowns .travis.yml file here https://github.com/Level/leveldown/blob/master/.travis.yml#L5-L13 on how to use C++11

**Comment by capaj** [comment]
@ralphtheninja thanks, did not realize travis needed this. Now builds just fine.

**Comment by ralphtheninja** [comment]
> @ralphtheninja thanks, did not realize travis needed this. Now builds just fine.

:+1:
