### ISSUE TITLE
prebuild --install fails on my system

### ISSUE THREAD

**Issue by HumanSprout** [Level/leveldown#281]
failed installing levelmeup

    npm ERR! leveldown@1.4.5 install: 'prebuild --install'
    npm ERR!  Exit status 2
    npm ERR! 
    npm ERR! Failed at the leveldown@1.4.5 install script 'prebuild --install'.

node v4.4.0 npm v2.14.20

**Comment by ralphtheninja** [comment]
@HumanSprout Mind doing `npm install --verbose` and put the output in a gist?

**Comment by HumanSprout** [comment]
Thanks for the quick response, here it is

https://gist.github.com/HumanSprout/0db6400f3a6d38ea52bfe5040e4cc1a1

**Comment by juliangruber** [comment]
the error happens because you run `npm install --verbose` from your home directory, try doing that inside you application's directory and post the results again

**Comment by HumanSprout** [comment]
I see, the error was from trying to install levelup globally, thank you for
your time
