### ISSUE TITLE
Debian Wheezy failure

### ISSUE THREAD

**Issue by julien-f** [Level/leveldown#287]
Installation succeed but there is a warning:

```
$ npm i
npm WARN lifecycle leveldown@1.4.6~install: cannot run in wd %s %s (wd=%s) leveldown@1.4.6 prebuild --install /tmp/leveldown/node_modules/leveldown
```

But the package does not work:

```
$ node
> require('leveldown')
Error: Could not locate the bindings file. Tried:
 → /tmp/leveldown/node_modules/leveldown/build/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/build/Debug/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/build/Release/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/out/Debug/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/Debug/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/out/Release/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/Release/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/build/default/leveldown.node
 → /tmp/leveldown/node_modules/leveldown/compiled/4.2.4/linux/x64/leveldown.node
    at bindings (/tmp/leveldown/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/tmp/leveldown/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
```

My setup:

```
$ npm version
{ npm: '3.4.0',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '46',
  node: '4.2.4',
  openssl: '1.0.2e',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by julien-f** [comment]
I can provide access to a test system if needed.

**Comment by juliangruber** [comment]
is that the only line in the build output about leveldown?

**Comment by julien-f** [comment]
The only thing else in the `npm i` output is the dependency tree.

**Comment by ralphtheninja** [comment]
@julien-f Are you installing leveldown as a dependency of another module? Or installing dependencies for leveldown itself? The warning from npm spits out the following path, which looks odd:

> `/tmp/leveldown/node_modules/leveldown`

**Comment by ralphtheninja** [comment]
> I can provide access to a test system if needed.

That would be nice!

**Comment by julien-f** [comment]
@ralphtheninja It's installed directly in the `/tmp/leveldown` I have created for the tests :)

You can access the machine through ssh with your public keys:

```
$ ssh -p 2223 root@hq.vates.fr
```

Feel free to do whatever you want, it's a virtual machine :)

**Comment by ralphtheninja** [comment]
I can't login

**Comment by juliangruber** [comment]
there are multiple keys here: https://github.com/ralphtheninja.keys

**Comment by julien-f** [comment]
@ralphtheninja My bad, I added them but then I overwrote the file :stuck_out_tongue:

**Comment by ralphtheninja** [comment]
I get this when trying to require leveldown after installing it:

```
[03:56 14] xoa:tmp$ ls
node_modules  npm-23591-8ef354bc
[03:56 14] xoa:tmp$ node -v
v4.2.4
[03:56 14] xoa:tmp$ node
> require('leveldown')
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/node_modules/leveldown/build/Release/leveldown.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/tmp/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/tmp/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
> [03:57 14] xoa:tmp$ dpkg -l | grep libc6
ii  libc6:amd64                        2.13-38+deb7u10           amd64        Embedded GNU C Library: Shared libraries
ii  libc6-dev:amd64                    2.13-38+deb7u10           amd64        Embedded GNU C Library: Development Libraries and Header Files
```

**Comment by ralphtheninja** [comment]
Seems to be the same as https://github.com/Level/leveldown/issues/276

**Comment by ralphtheninja** [comment]
This is a two fold problem:

* the prebuilt binaries have been built on a too new version of glibc (2.14 it seems)
* `prebuild` isn't testing the downloaded binary, if it would it would fail and fallback to a compile step, so we have some regression here

I'm digging further

**Comment by ralphtheninja** [comment]
Turns out `opts.abi` is `undefined` [here](https://github.com/mafintosh/prebuild/blob/master/download.js#L94) so we will never make the require test.

We can fix this by providing `opts.abi` but I'm thinking that maybe the download code shouldn't do this test at all? Since `opts.abi` is only used in that place of `download.js` we could instead make the require test in `bin.js` instead? This way we don't need to pass in abi at all.

@juliangruber Would moving out the require test screw something up for your `require-rebuild` module?

**Comment by juliangruber** [comment]
i'm ok with removing the require test @ralphtheninja

**Comment by ralphtheninja** [comment]
@julien-f Should work now. Just tested it on your virtual machine. Feel free to test as well :) We still have the problem with glibc, but now the require test fails so leveldown will be built.

**Comment by ralphtheninja** [comment]
@julien-f Please close is this is no longer an issue

**Comment by julien-f** [comment]
@ralphtheninja Thank you so much!

The next time I have an issue I'll prepare you a nice VM to work with :stuck_out_tongue:

**Comment by ralphtheninja** [comment]
> The next time I have an issue I'll prepare you a nice VM to work with :stuck_out_tongue:

That was *extremely* helpful. Thanks :)
