### ISSUE TITLE
Use leveldown in node-webkit

### ISSUE THREAD

**Issue by jishuo1213** [Level/leveldown#289]
I am using linvodb3 in win32 node-webkit 0.12.1 with node.js 1.2.0 ,I build leveldown successfully use nw-gyp,but when i use as follow:
```
      var LinvoDB = require("linvodb3");
    
    LinvoDB.defaults.store = {db: require("leveldown")}; 

    LinvoDB.dbPath = process.cwd();
    var Planet = new LinvoDB("planeta", {/* schema, can be empty */})
    Planet.find({}).exec(function (err, docs) {
  
        console.info(docs)
    });
```
I got an error as follow:
`
nwjs-v0.12.1-win-ia32\node_modules\linvodb3\node_modules\levelup\lib\levelup.js:115 Uncaught TypeError: object is not a function`

I don't konw this error is cause by linvodb3 or the leveldown.node file I build.

**Comment by SlamDunkDcc** [comment]
@ralphtheninja  I found this problem too.

**Comment by juliangruber** [comment]
The line that is throwing the typeerror is https://github.com/Level/levelup/blob/master/lib/levelup.js#L115, which hints us that the dbFactory passed is not a function, as it should be.

Can you provide us with a snippet that doesn't use linvodb3, instead just levelup and leveldown, but still causes the error?

**Comment by SlamDunkDcc** [comment]
I suspect that the compiler "leveldown.node" has a problem.  But I don't know how to compile it. @juliangruber

**Comment by jishuo1213** [comment]
Leveldown can use in node-webkit ,Previous it's my fault make it not works.My english is not good,So I will not explained in detail.If any one want know about how to use leveldown in node-webkit.Can @me in this issue.Thank you very much @juliangruber,I will close this issue.
