### ISSUE TITLE
question: err callback type

### ISSUE THREAD

**Issue by cdaringe** [Level/leveldown#291]
hi all:

shooting from the hip trying to debug an issue.  is this correct or _not correct_?  checkout the comment.

```js
// /node_modules/leveldown/iterator.js
  } else {
    debugger
    this.binding.next(function (err, array, finished) {
      if (err) return callback(err)
      // ^^  `err === true`.  should this be an _Error_ instance?  getting the `Boolean` `true`
      that.cache    = array
      that.finished = finished
      that._next(callback)
    })
  }
```

pouchdb uses this bad boy under the hood. not sure if their `callback` needs to handle booleans or if leveldown needs to be emitting Error instances.  given that this is a `.js` file, I would expect this to `cb` with and `Error`.

I cannot _easily_ provide a small test case, as I'm not ~~keep~~ familiar with the pouchdb internals.  i'm running this from within the electron runtime.  pouchdb tests all pass when using electron (`1.2.2`) as node.  coffee shop is closin', but can provide more as needed!  thanks!~

Thanks!

**Comment by ralphtheninja** [comment]
I had a look at `src/iterator.cc` and the callback in `Iterator::Next` looks like:

https://github.com/Level/leveldown/blob/master/src/iterator.cc#L260

```c++
v8::Local<v8::Function> callback = info[0].As<v8::Function>();
```

But for `Iterator::End` it's

```c++
v8::Local<v8::Function> callback = v8::Local<v8::Function>::Cast(info[0]);
```

@rvagg Any thoughts on this?

**Comment by juliangruber** [comment]
@cdaringe it's an issue with electron shipping an ABI incompatible v8 version. See https://github.com/electron/electron/issues/5851.

The easiest way to fix this right now is simply to stick with electron 1.1.3.

**Comment by cdaringe** [comment]
hey @juliangruber, thanks a bunch.  just curious, how did you prescribe the diagnosis, here?

**Comment by cdaringe** [comment]
OH.  i see now. thx.
