### ISSUE TITLE
Install Fails Debian 3.2.60

### ISSUE THREAD

**Issue by NicoNet** [Level/leveldown#292]
GIST of --verbose
https://gist.githubusercontent.com/anonymous/390fa16d299dde3034deaab596d51ced/raw/d5004709230ce2769671be9494f9deb04737b8a4/npm-verb-leveldown.txt
-
> leveldown@1.4.6 install /tmp/node_modules/leveldown
> prebuild --install

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the leveldown@1.4.6 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "leveldown"
npm ERR! cwd /tmp/leveldowninstall
npm ERR! node -v v4.4.3
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/leveldowninstall/npm-debug.log
npm ERR! not ok code 0

**Comment by juliangruber** [comment]
> npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by NicoNet** [comment]
Thanks, fixed by created symlink /usr/bin/node -> /usr/bin/nodejs .
