### ISSUE TITLE
Unable to install leveldown on CentOS 6.8

### ISSUE THREAD

**Issue by josephting** [Level/leveldown#293]
Seems like Glibc version to me.
Leveldown requires 2.14 but I only have 2.12.

```
# ldd --version
ldd (GNU libc) 2.12
```

NPM Log
https://gist.github.com/josephting/57f51a840d050c72d7de34cb083eafbb

I saw some warning elsewhere about updating Glibc to 2.14 might break something else.

**Comment by rvagg** [comment]
You're going to need to install and then enable devtoolset-2 to get a newer version of gcc to compile anything with Node.js v4 and beyond. `gcc -v` should show at least v4.8. There's a few ways to achieve this, we use the Scientific Linux packages to do this in Node core, http://linux.web.cern.ch/linux/devtoolset/ but I see there's also some being provided by some CentOS folks now too: http://people.centos.org/tru/devtools-2/readme

**Comment by josephting** [comment]
Thanks. I've tried it now but they still didn't work when I try to install it globally.
Weirdly, it now works if I install it locally.
I went as far as compiling and replacing glibc with v2.14 and it still doesn't work.
I'm totally lost now.

https://gist.github.com/josephting/8c2d56138cd74aae8db2f0e2efa6715f
