### ISSUE TITLE
leveldb 1.19 is out!

### ISSUE THREAD

**Issue by juliangruber** [Level/leveldown#298]
https://github.com/google/leveldb/releases/tag/v1.19

A bunch of bug fixes, and in particular those new features:

- Add "approximate-memory-usage" property to leveldb::DB::GetProperty
- Add leveldb::Cache::Prune
- Added leveldb::Status::IsInvalidArgument() method
- Add arm64 support to leveldb
- Now attempts to reuse the preceding MANIFEST and log file when re-opened

The last one should help with start up time a lot if there's a lot of in-flight data on re-open.

The diff can be found here: https://github.com/google/leveldb/compare/v1.18...v1.19

Who wants to take the lead on this? This should be mostly about making sure it still compiles, and exposing the new features if necessary.

**Comment by juliangruber** [comment]
Actually, I have time right now, I'll get started in a branch and see how far I can get

**Comment by juliangruber** [comment]
This is my work in progress pull request: https://github.com/Level/leveldown/pull/299

**Comment by tcr** [comment]
This also adds an implementation for MIPS, required for compiling leveldown on the Tessel 2 platform. Excited :) cc https://github.com/tessel/t2-compiler/issues/27
