### ISSUE TITLE
Prebuilt Linux ARM binaries are missing in 1.4.6 and 1.4.5 releases

### ISSUE THREAD

**Issue by ewnd9** [Level/leveldown#300]
1.4.6 (Apr 30) https://github.com/Level/leveldown/releases/tag/v1.4.6
1.4.5 (Apr 19) https://github.com/Level/leveldown/releases/tag/v1.4.5

![image](https://cloud.githubusercontent.com/assets/1713789/17723956/bc5f0a36-6470-11e6-9278-5149ba69f807.png)

1.4.4 and below have them https://github.com/Level/leveldown/releases/tag/v1.4.4 

![image](https://cloud.githubusercontent.com/assets/1713789/17723952/b2b40842-6470-11e6-880f-ea77063b2db6.png)

**Comment by rvagg** [comment]
Who's doing prebuilds these days? @ralphtheninja? I can make armv6 and arm64 binaries if given publish instructions & permission.

**Comment by ralphtheninja** [comment]
> Who's doing prebuilds these days? @ralphtheninja? I can make armv6 and arm64 binaries if given publish instructions & permission.

:+1: 

I used to do them for rpi but have been busy :/

Build them by doing `npm run prebuild` inside the `leveldown` folder.

Publish them by attaching them to the [release](https://github.com/Level/leveldown/releases/tag/v1.4.6).

**Comment by rvagg** [comment]
@ralphtheninja is there any API, maybe using `curl`, to automate attaching files to releases?

**Comment by ralphtheninja** [comment]
@rvagg `prebuild` handles this as well if you have a valid github token, see https://github.com/mafintosh/prebuild#uploading

**Comment by rvagg** [comment]
thanks @ralphtheninja, I'll try and get that sorted out to do this automatically, for now I've manually uploaded the arm builds

**Comment by ralphtheninja** [comment]
> thanks @ralphtheninja, I'll try and get that sorted out to do this automatically, for now I've manually uploaded the arm builds

Awesome!

**Comment by robinpaulson** [comment]
Hi guys, could you take another look at automating this please? We're missing prebuilds for rpi, version 1.6.0. Cheers

**Comment by sabrehagen** [comment]
Got any bandwidth to accommodate the rpi prebuilds @rvagg?
