### ISSUE TITLE
windows prebuilt missing

### ISSUE THREAD

**Issue by juliangruber** [Level/leveldown#305]
(target=4.5.0 arch=x64 platform=win32)

**Comment by RangerMauve** [comment]
What's required to fix this? Maybe I could do a PR.

**Comment by vweevers** [comment]
```
prebuild info build Uploaded 10 new prebuild(s) to Github
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v11-win32-ia32.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v11-win32-x64.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v14-win32-ia32.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v14-win32-x64.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v46-win32-ia32.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v46-win32-x64.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v47-win32-ia32.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v47-win32-x64.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v48-win32-ia32.tar.gz
prebuild info build -> prebuilds/leveldown-v1.4.6-node-v48-win32-x64.tar.gz
```

Building for 0.10.44 was a particular pain. For reference, you need npm `>= 2.15.9 < 3` (nodejs/node-gyp#972). Additionally, prebuild did not honor `npm config msvs_version 2015` (with or without `--global`). Had to set an environment variable instead. In full:

```
nvm use 0.10.44 32
npm i npm@2 -g
set npm_config_msvs_version=2015
prebuild -b 0.10.44 --strip --arch=x64
prebuild -b 0.10.44 --strip --arch=ia32
```

(`--strip` doesn't do anything on Windows atm).

@juliangruber More are missing: 1.4.5 (all), 1.4.3 (32-bit), 1.4.2 (ABI 47 / Node 5). How far back should I go?

**Comment by juliangruber** [comment]
@vweevers hmmm tbh i'm not connected to any windows development, so I guess this is fine?

Thank you so much for figuring this out and going through the trouble! :)

**Comment by vweevers** [comment]
Yea, I just realized those are all in the same semver range. In any case, people can find this ticket (hi there!) and request additional prebuilds.

OK to close, imo.

**Comment by juliangruber** [comment]
<3 !

**Comment by 0x00A** [comment]
Hey, @vweevers do you know how we might go about creating a job to automatically generate prebuilds for windows? Maybe using some kind of job we can put on a server? Just an idea; maybe it would require too much human intervention to work. But I just ran into this and I think there is no prebuild for the 1.5.x release.

**Comment by 0x00A** [comment]
Maybe I'm actually wrong about this, because on Windows 10 I just tried to install `leveldown@1.4.6` and I got the same errors I was getting trying to install latest...

```
$ npm install leveldown@1.4.6
[    ..............] - fetchMetadata: sill mapToRegistry uri http://registry.npmjs.org/nan] - 
> leveldown@1.4.6 install C:\Users\IEUser\work\voltra\node_modules\leveldown
> prebuild --install
prebuild WARN install read ECONNRESET
prebuild WARN install got an error, rolling back install
prebuild ERR! configure error
prebuild ERR! stack Error: read ECONNRESET
prebuild ERR! stack     at exports._errnoException (util.js:1026:11)
prebuild ERR! stack     at TLSWrap.onread (net.js:569:26)
prebuild ERR! not ok
prebuild ERR! build Error: read ECONNRESET
prebuild ERR! build     at exports._errnoException (util.js:1026:11)
prebuild ERR! build     at TLSWrap.onread (net.js:569:26)
```

**Comment by vweevers** [comment]
@0x00A auto-generating prebuilds is what #309 aims to do. Actually we could use your help there: https://github.com/Level/leveldown/pull/309#issuecomment-246319089.

As for the install problem, that's weird, has to be a connection problem. If it was a missing prebuild, then prebuild (the module) would just fall back to compiling leveldown. I manually tested most of the prebuilds before I uploaded them. Which node version are you using?

**Comment by 0x00A** [comment]
ah! #309 was exactly what I had in mind!

On node latest. Fresh Win10 IEUser image on VirtualBox. It must be some kind of connection issue, but it's strange because all the other modules seem to install fine. Anyway, closing this again because it's going off on a tangent.
