### ISSUE TITLE
Faster range queries

### ISSUE THREAD

**Issue by chjj** [Level/leveldown#307]
My code very regularly makes use of iterators, iterating over every item in an lte->gte range without seeking or stopping, buffering all the values along the way.

I have a feeling this is a very common pattern. It could be optimized to avoid the overhead of js->c++->js->c++ and the creation of an async worker on each `next()` call. There are cases where we may be iterating over a couple hundred (maybe thousands of) records. The `iter.next(callback)` flow adds an unnecessary performance hit.

To have the entire behavior of `iter()->iter.next()->...->iter.end()` optionally run as a single async job in c++ would be a very nice perf increase.

In my current leveldown wrapper, I have a method called `iterate()`:

``` js
db.iterate({
  gte: ...,
  lte: ...,
  keys: false,
  values: true
}, callback); // Callback receives an array of collected values.
```

I realize that adding a method like this is more than just an addition to leveldown, but maybe an addition to the entire leveldown API definition.

Thoughts?

**Comment by dominictarr** [comment]
how is this different to this https://github.com/Level/leveldown/pull/96 ?
It would also be interesting to hear a more concrete description of how you are using iterators

**Comment by chjj** [comment]
@dominictarr, mmm, I didn't even think about that. Been too long since I've looked at the iterator code. Closing.
