### ISSUE TITLE
Differentiating (branches?)

### ISSUE THREAD

**Issue by Announcement** [Level/leveldown#308]
I noticed a few other _branches_ that peeked the curiosity...
- Hyper
- Basho
- RocksDB

What are these, and why aren't they documented?

**Comment by vweevers** [comment]
- Hyper: moved to https://github.com/Level/leveldown-hyper
- Basho: not currently maintained (and not documented because it was an experiment)
- RocksDB: moved to https://github.com/Level/rocksdb.
