### ISSUE TITLE
prebuild-install

### ISSUE THREAD

**Issue by EchoChung6** [Level/leveldown#310]
Hi, came across the following issues when i execute sudo npm install levelmeup -g:

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/leveldown.node] Error 1
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/levelmeup/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:87:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:172:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/usr/local/lib/node_modules/levelmeup/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "levelmeup" "-g"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Yingying/npm-debug.log
npm ERR! code 1

![screen shot 2016-09-18 at 12 10 56 pm](https://cloud.githubusercontent.com/assets/18530465/18612289/6f8e3a14-7d99-11e6-951a-611ff0935745.png)

and the debug log is as follows:

[npm-debug.txt](https://github.com/Level/leveldown/files/478480/npm-debug.txt)

I  have read your previous solution at https://github.com/Level/leveldown/issues/288 but it did not work for me.
I posted the output of npm i leveldown --verbose to a gist: https://gist.github.com/EchoChung6/6805302183d101d61c51e0729ff9c778

Thank you for your time.

**Comment by Jlabarca** [comment]
You fixed it? I have the same problem, tried everything and still not working

**Comment by EchoChung6** [comment]
No I did not. Have you?
It seems no one is looking at this issue?

**Comment by juliangruber** [comment]
What's interesting is that `npm install leveldown` works, it just doesn't work when you seem to install it as part of the levelmeup project.

All we get is

```
22020 verbose stack Error: leveldown@1.4.6 install: `prebuild --install`
22020 verbose stack Exit status 2
```

**Comment by ralphtheninja** [comment]
> What's interesting is that npm install leveldown works, it just doesn't work when you seem to install it as part of the levelmeup project.

o.O

The only difference I can see here is that `levelmeup` is installed using `sudo`. So that might be related.

**Comment by ralphtheninja** [comment]
@EchoChung6 Would you mind trying to _clone_ `levelmeup` and just do `npm install` inside it?

**Comment by EchoChung6** [comment]
Thank you ralphtheninja.

**Comment by gtirloni** [comment]
Found this issue while researching the following error with nodejs 6.9.0:

```
$ npm install levelup

> leveldown@0.10.6 install /srv/common_terms_registry/express/node_modules/leveldown
> node-gyp rebuild

make: Entering directory `/srv/common_terms_registry/express/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../node_modules/nan/nan.h:194:0,
                 from ../src/batch.cc:5:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:221:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at /srv/common_terms_registry/.node-gyp/6.9.0/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:200,
                 from ../src/batch.cc:5:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at /srv/common_terms_registry/.node-gyp/6.9.0/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ../src/batch.cc:5:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:602:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:602:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:603:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:608:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:608:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:613:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:613:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:614:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:619:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:619:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1961:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /srv/common_terms_registry/.node-gyp/6.9.0/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
../src/batch.cc: In static member function ‘static v8::Local<v8::Value> leveldown::Batch::NewInstance(v8::Local<v8::Object>, v8::Local<v8::Object>)’:
../src/batch.cc:73:69: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /srv/common_terms_registry/.node-gyp/6.9.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                                                     ^
../src/batch.cc:76:69: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /srv/common_terms_registry/.node-gyp/6.9.0/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                                     ^
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/srv/common_terms_registry/express/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-327.36.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/common_terms_registry/express/node_modules/leveldown
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
bl@0.8.2 node_modules/levelup/node_modules/bl -> node_modules/gpii-pouch/node_modules/bl
xtend@3.0.0 node_modules/deferred-leveldown/node_modules/xtend -> node_modules/gpii-pouch/node_modules/deferred-leveldown/node_modules/xtend
xtend@3.0.0 node_modules/levelup/node_modules/xtend -> node_modules/gpii-pouch/node_modules/pouchdb/node_modules/levelup/node_modules/xtend
ptd-front-end@0.0.1 /srv/common_terms_registry/express
├─┬ gpii-pouch@0.0.0 (git://github.com/the-t-in-rtf/gpii-pouchdb.git#667c6e109dd67fc031c1171a1389dd7ad03f9728)
│ └─┬ pouchdb@3.3.1
│   ├── UNMET PEER DEPENDENCY bn.js@^0.15.0
│   └─┬ levelup@0.18.6 
│     ├─┬ deferred-leveldown@0.2.0 
│     │ └── abstract-leveldown@0.12.4 
│     ├── prr@0.0.0 
│     └── semver@2.3.2 
└─┬ levelup@1.3.3 
  ├─┬ deferred-leveldown@1.2.1 
  │ └── abstract-leveldown@2.4.1 
  ├── level-codec@6.1.0 
  ├─┬ level-errors@1.0.4 
  │ └─┬ errno@0.1.4
  │   └── prr@0.0.0 
  ├── level-iterator-stream@1.3.1 
  ├── prr@1.0.1 
  └── semver@5.1.1 

npm WARN miller-rabin@1.1.1 requires a peer of bn.js@^0.15.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@0.10.6 (node_modules/leveldown):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@0.10.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by danielsun174** [comment]
Same Error with nodejs v7.0. anyone has a solution?

**Comment by ralphtheninja** [comment]
@gtirloni You're using a really old version of levelup/leveldown/leveldb. I suggest you update to a newer version first and try that out. I also suggest you try `level` (which bundles `levelup` and `leveldown`) instead of using `levelup`.

**Comment by ralphtheninja** [comment]
@danielsun174 If you're running the latest leveldown (leveldb 1.19) and have similar problems, please open a separate issue for this.

**Comment by MassimoCappellano** [comment]
Hi, I thing I've the same problem trying to install level and in particular `leveldown@1.5.3` on `Openshift`

On the server the versions are:

```
[comuni-simplethings.rhcloud.com 5877e7df0c1e663d5e000123]\> gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[comuni-simplethings.rhcloud.com 5877e7df0c1e663d5e000123]\> node --version
v7.4.0
[comuni-simplethings.rhcloud.com 5877e7df0c1e663d5e000123]\> npm --version
4.1.1 
```

the command executed: `npm i leveldown --verbose`

I posted the output of npm i leveldown --verbose to a gist: 
https://gist.github.com/MassimoCappellano/1dc9277c166ad82e6cabd6c4668a46a9

Thanks
Massimo

**Comment by MassimoCappellano** [comment]
From searching seems that the problem is due to gcc very old version on openshift platform

This is the output of `npm i leveldown >install_leveldown.log 2>&1`
https://gist.github.com/MassimoCappellano/49b54f10c9bcaf4e1941837157b1604d

In particular 

`../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`

But on that platform gcc is 4.4.7, not compatible with C++ 11.

Others:

https://github.com/icflorescu/openshift-cartridge-nodejs/issues/12

https://github.com/ramr/nodejs-custom-version-openshift/issues/12

**Comment by Huangming222** [comment]
I have the same error.

**Comment by vweevers** [comment]
@Huangming222 this issue is rather old, if updating to the latest version doesn't help then:

> please open a separate issue for this with install log etc. The best thing would be if you could do `npm i leveldown --verbose` and paste that install log into a gist and link the gist.

**Comment by Huangming222** [comment]
This is the log file
> leveldown@3.0.0 install F:\Workspace\0 In Progress\Angular\gero3_win_org\gero3_win_real\node_modules\pouchdb\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.13.0 runtime=node arch=x64 platform=win32)

F:\Workspace\0 In Progress\Angular\gero3_win_org\gero3_win_real\node_modules\pouchdb\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Workspace\0 In Progress\Angular\gero3_win_org\gero3_win_real\node_modules\pouchdb\node_modules\leveldown
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular5-csv@0.2.11 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular5-csv@0.2.11 requires a peer of @angular/http@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular5-csv@0.2.11 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng4-intl-phone@1.2.1 requires a peer of @angular/core@>=4.0.0 <5.0.0 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng4-intl-phone@1.2.1 requires a peer of @angular/forms@^4.1.3 but none is installed. You must install peer dependencies yourself.
npm WARN ng4-intl-phone@1.2.1 requires a peer of @types/lodash@^4.14.64 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhenh\AppData\Roaming\npm-cache\_logs\2019-04-22T12_04_26_109Z-debug.log

**Comment by vweevers** [comment]
You're missing Python. Please see https://github.com/nodejs/node-gyp#installation.

If you're using node v10 and you want prebuilt binaries you'll need at least `leveldown@3.0.1`.

**Comment by Huangming222** [comment]
I am trying now and thanks and struggling. :)

**Comment by vweevers** [comment]
On Windows, [`npm install --global windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools) should install everything you need (including Python).

**Comment by Huangming222** [comment]
I think so. download and installing.

**Comment by Huangming222** [comment]
Thank you. I fix it. Have a good experience.
