### ISSUE TITLE
no prebuilt binaries for electron 1.4 (abi 50)

### ISSUE THREAD

**Issue by mmckegg** [Level/leveldown#313]
I can use this command to rebuild leveldb for the current latest version of electron:
```bash
$ npm rebuild --runtime=electron --target=1.4.2 --abi=50 --disturl=https://atom.io/download/atom-shell
```

This works fine except that it has to rebuild from source because electron actually uses an abi version of `50` (the most recent prebuild in releases is 48). This make installing electron packages like [ferment](https://github.com/mmckegg/ferment) and [patchwork](https://github.com/ssbc/patchwork-electron) much more tedious and slower than it could be.

**If you add me to this repo, I'd happily contribute prebuilds for:**
- v50-darwin-x64
- v50-linux-x64

Or these targets could be added to the automated build. Either way's fine with me 😸 just be nice to get this sorted.

**Comment by ralphtheninja** [comment]
@mmckegg Invitation sent! :smile:
