### ISSUE TITLE
Close callback never called

### ISSUE THREAD

**Issue by martinheidegger** [Level/leveldown#314]
I have a code in which callback is not being called:

```javascript
var level = require('level')

module.exports = function (databaseDir, input, callback) {
  var db = level(databaseDir, function () {
    console.log('a')
    input.del.forEach(db.del.bind(db))
    for (var key in input.put) {
      db.put(key, input.put[key])
    }
    console.log('b')
    db.close(function () {
      console.log('c')
      callback()
    })
  })
}

```

input contains a quite a few put keys.

The output is
```
a
b
```
so... `c` is never reached. I tried to find the problem but, well...

**Comment by michaelnisi** [comment]
I find your code confusing, but this issue looks more like a [levelup](https://github.com/Level/levelup) question to me. Try https://github.com/Level/levelup#batch and close the database on its callback—not sure you should though: in hot code it's ineffective to constantly open and close the database.

**Comment by martinheidegger** [comment]
@michaelnisi I am aware that it is very ineffective _(it is part of a test if it is possible, because i am preparing learning material on this and want to get an answer)_ What I would like to confirm is if it is illegal and which "project" this bug belogs to.

**Comment by vweevers** [comment]
`put()` and `del()` are asynchronous, so the above code closes the database before the operations have a chance to complete. Either add callbacks to [`put()`](https://github.com/Level/levelup#dbputkey-value-options-callback) and [`del()`](https://github.com/Level/levelup#dbdelkey-options-callback), or like @michaelnisi suggested, try `db.batch()`:

```js
var operations = input.del.map(function(key) {
  return { type: 'del', key: key }
})

for(var key in input.put) {
  operations.push({ type: 'put', key: key, value: input.put[key] })
}

db.batch(operations, function (err) {
 // all done, you can call db.close() now
})
```

The second issue is that you're mixing [two ways of managing a levelup instance](https://github.com/Level/levelup#levelupdb-callback-). Choose between:

```js
level('my-db', function (err, db) {
  // the database is open at this point
  db.batch(..)
})
```

And:

```js
var db = level('my-db')
// this database will auto-open and defer all operations until then
db.batch(..)
```

**Comment by martinheidegger** [comment]
I understand that this is "uncool" way of using it. but I even if the commands are called async I would expect an error "i.e. you cant close because there are still commands open" and in any case the db should have closed, right?

**Comment by ralphtheninja** [comment]
@martinheidegger What does your `input` look like? (Just want to run it the way you do)

**Comment by vweevers** [comment]
@martinheidegger I suspect the close callback does not fire because you're mixing the two ways of managing the instance.

**Comment by ralphtheninja** [comment]
There's an old issue here: https://github.com/Level/leveldown/issues/32 which might be related (I unassigned myself since I really don't have time). Also there are known issues with doing `.close()` in the same tick when there are iterators opened with segfaults etc.

**Comment by ralphtheninja** [comment]
> @michaelnisi I am aware that it is very ineffective (it is part of a test if it is possible, because i am preparing learning material on this and want to get an answer)
> What I would like to confirm is if it is an incorrect behaviour and which github repo this bug (if it is a bug) belongs to.

So I guess `leveldown` is the correct place for this problem.

**Comment by martinheidegger** [comment]
It looks like something like this:
```javascript
input = {
   del: ['key-a', 'key-b', .... and several more],
   put: {
     'new-key-1': 1,
     'new-key-2': 2,
     'new-key-3': 3,
     ... etc.
     'new-key-4131', 4131
   }
}
```

**Comment by vweevers** [comment]
Also be aware, that without callbacks for `put` and `del`, the database will emit an `error` event if any of the operations fail.

**Comment by martinheidegger** [comment]
@vweevers absolutely aware of that ^_^

**Comment by michaelnisi** [comment]
If I run your code like this, where `l` is your module:

```js
const l = require('./')

const keys = function () {
  var keys = []
  for (var i = 0; i < 10000; i++) { keys.push(i) }
  return keys
}()

const put = keys.reduce(function (acc, key) {
  acc[key] = key
  return acc
}, {})

const del = []

l('.', { put: put, del: del }, function () {})
```

The output is:

```
a
b
c
```

Interestingly, if I also pass the keys as del:

```js
const del = keys
```

I get:

```
a
b
```

And crash with:

```
/Users/michaelnisi/node_modules/levelup/lib/levelup.js:284
        callback()
        ^

TypeError: callback is not a function
    at /Users/michaelnisi/node_modules/levelup/lib/levelup.js:284:9
```

**Comment by vweevers** [comment]
@michaelnisi that's because this line of code:

```js
input.del.forEach(db.del.bind(db))
```

Is actually:

```js
input.del.forEach(function(key, index, array) {
  db.del(key, index, array)
})
```

**Comment by michaelnisi** [comment]
@vweevers You mean: 

```js
input.del.forEach(function(key, index, array) {
  db.del(key, function (){})
})
```

Which gives: 

```
a
b
c
```

✌️

**Comment by martinheidegger** [comment]
Looks like the function type should be checked?!

**Comment by michaelnisi** [comment]
@vweevers Sorry, I misread what you were saying. You are right!

**Comment by martinheidegger** [comment]
Maybe this could work by changing: https://github.com/Level/levelup/blob/master/lib/levelup.js#L34

to:

```javascript
function getCallback (options, callback) {
  return typeof options === 'function' ? options : typeof callback === 'function ? callback : undefined
}
```

**Comment by ralphtheninja** [comment]
@michaelnisi Aye, I get the same results.

**Comment by michaelnisi** [comment]
Just to clarify my mumblings, replacing the line:

```js
db.del.bind(db)
```

with:

```js
input.del.forEach(function (key) {
  db.del(key, function () {})
})
```

in the initial module resolves the issue on the call site, the underlying issue, as @martinheidegger pointed out, seems to be an unguarded callback.

**Comment by vweevers** [comment]
> Looks like the function type should be checked?!

An invalid argument *should* throw, imo. It would be hard to track down bugs otherwise.

More importantly, the issue of closing early still stands. There's currently no guarantee the data is actually written to disk, if I'm reading it right.

I understand what you're trying to do, and I'm not saying the segfault bug isn't a valid concern, but it looks to me as if you're using `close()` for async flow control here. Other mechanisms (like `batch` or some flow control lib) would be more appropriate.

**Comment by martinheidegger** [comment]
> An invalid argument should throw, imo. It would be hard to track down bugs otherwise

I think this would be the first place to have sanity checks and if it is added there then it should be also added for the other parameters. i.e. The current implementation does allow silly values such as 1 or null. https://github.com/Level/levelup/blob/master/lib/util.js#L25

Having a ton of sanity checks might be good but  this would be major change _(not a patch)_ and should clearly define the timing of the occurring error (should it be handled async through the callback error or using throw?).

> ... if I'm reading it right.

You are reading it right. It is also discussed the open issue [#32](https://github.com/Level/leveldown/issues/32) and [i think](https://github.com/Level/leveldown/issues/32#issuecomment-253760125) it should be addressed in levelup.

> Other mechanisms (like batch or some flow control lib) would be more appropriate

Answered [above](https://github.com/Level/leveldown/issues/314#issuecomment-253747592)

Closing this issue and reopening it in levelup. Thank you all for your help!

**Comment by martinheidegger** [comment]
Created here: https://github.com/Level/levelup/issues/406
