### ISSUE TITLE
Assertion failed on db open

### ISSUE THREAD

**Issue by andris9** [Level/leveldown#315]
I have a corrupt database that I'm not able to open or repair. Whenever I try to use it I get the following error that I'm unable to catch:

Output on OSX (node v6.8.1, leveledb 1.19):

```
Assertion failed: (x == NULL || !Equal(key, x->key)), function Insert, file ../deps/leveldb/leveldb-1.19/db/skiplist.h, line 344.
Abort trap: 6
```

Output on Ubuntu (node v6.8.1, leveledb 1.18):

```
../deps/leveldb/leveldb-1.18.0/db/skiplist.h:344: void leveldb::SkipList<Key, Comparator>::Insert(const Key&) [with Key = const char*; Comparator = leveldb::MemTable::KeyComparator]: Assertion `x == NULL || !Equal(key, x->key)' failed.
```

**Comment by juliangruber** [comment]
would sharing that database with us be possible? could also be private via mail.

**Comment by andris9** [comment]
@juliangruber I can share it privately. I'll upload the compressed folder (it's about 300MB) and mail you the link to it.

**Comment by andris9** [comment]
@juliangruber I emailed the download link to the email listed on your Github page.

**Comment by juliangruber** [comment]
ok, sorry for the delay, I'll try to work on this tomorrow! can you also send it to @ralphtheninja?

**Comment by ralphtheninja** [comment]
@andris9 Did you manage to resolve this? Please re-open if this is still an issue and you need more help/assistance with it.
