### ISSUE TITLE
leveldb 1.19 breaks static builds

### ISSUE THREAD

**Issue by mmckegg** [Level/leveldown#318]
Just recently [had an issue](https://github.com/mmckegg/patchwork-next/issues/1#issuecomment-258579861) where the prebuild I published for electron v.1.4.x (package ABI v50) wasn't working for someone running Ubuntu 12.04. We tracked the problem down to the `lbstdc++` version.

Didn't test this, but I suspect it would apply to all of the leveldown 1.5.0 linux prebuilds.

Turns out leveldb 1.19 [has a bug in it that breaks static builds](http://patchwork.ozlabs.org/patch/667542/). I rolled back to the 1.4.6 prebuild and everything work perfectly fine again.

**Comment by ralphtheninja** [comment]
@mmckegg We had similar problems before with `glibc`. Which version of `libstdc++` is running on that Ubuntu 12.04?

**Comment by mmckegg** [comment]
Not sure, but I built the prebuild on a machine running 5.4.0 20160609

@bhaugen what's the output of `g++ -dumpversion` on your machine?

**Comment by bhaugen** [comment]
> @bhaugen what's the output of g++ -dumpversion on your machine?
4.6

**Comment by ralphtheninja** [comment]
Here's what I get on my machine on the prebuilt `leveldown.node`

```
$ strings build/Release/leveldown.node | grep GLIBCXX
GLIBCXX_3.4                                          
```

**Comment by mmckegg** [comment]
@ralphtheninja yes, same for me with the prebuild that wasn't working. 

I have unpublished but here it is for reference: [leveldown-v1.5.0-node-v50-linux-x64.tar.gz](https://github.com/Level/leveldown/files/573144/leveldown-v1.5.0-node-v50-linux-x64.tar.gz)
