### ISSUE TITLE
Don't process close() until current in-flight async ops are complete

### ISSUE THREAD

**Issue by rvagg** [Level/leveldown#32]
Will involve more tracking like the delete-iterators-on-close work. Each async operation will have to increment a counter when starting and decrement when done, will also need to trigger a possible-close function when done.
Without this, a segfault is possible when you close() while an operation is in-flight.

**Comment by ralphtheninja** [comment]
@dominictarr I believe it involves all in flight operations (see https://github.com/rvagg/node-leveldown/issues/157)

**Comment by ralphtheninja** [comment]
@mcollina The counter would have to be static I guess.

**Comment by martinheidegger** [comment]
Shouldn't this be a feature of levelup, I mean: It is sort of a pain to do this for every client.

**Comment by ralphtheninja** [comment]
Or maybe in `abstract-leveldown`?

**Comment by martinheidegger** [comment]
In any case https://github.com/Level/levelup#dbclosecallback  doesn't mention this case and at the minimum it should state what the "should-case" should be.

**Comment by ralphtheninja** [comment]
Nice!
