### ISSUE TITLE
Release new version soon?

### ISSUE THREAD

**Issue by DanReyLop** [Level/leveldown#330]
Hi folks,

I'm trying to migrate a big project to `yarn` (the project is not so big, but it has a ton of dependencies), and `leveldown` is preventing me from a smooth transition. I don't even know which of my dependencies or sub-sub-dependencies is using `leveldown` LOL

I've tracked down the issue to a problem with Yarn and Prebuild, it was solved here: https://github.com/Level/leveldown/commit/738a103027442b03a0fd6cd8070b141bf85986c1

Any chance you folks will tag a new release in the near future? It looks there's plenty of commits since `1.5.0`.

If not, I'll just have to install the needed dependencies to build node packages in Windows (.NET and Python, I think), and tell all the Windows users in my team to do the same. Not terrible, but certainly annoying.

Thank you in advance.

**Comment by ralphtheninja** [comment]
@DanReyLop Definitely this week! Would be nice to get https://github.com/Level/leveldown/pull/329 merged first.

**Comment by peakji** [comment]
It would be great if someone could help me to review https://github.com/Level/leveldown/commit/26a297ca32b880969ac52b55c13d93348d86ea30#diff-ae26fbaaef77866c6fa9f7dab20dd2e0R242 before the new release. I just want to make sure that I'm using `slice` and the macros right. 🤔

**Comment by benthemonkey** [comment]
I'm in the same boat, I would love it if `leveldown` had a release so I can start using Yarn (I depend on `hard-source-webpack-plugin` -> `level` -> `leveldown` -> `prebuild`)

Hopefully this is a minor or patch release, or else I'll have to wait on a PR to `level` before I'll be unblocked.

Thanks!

**Comment by peakji** [comment]
Merry Christmas!

@benthemonkey `level` uses `"leveldown": "~1.5.0"` [#L37](https://github.com/Level/level/blob/master/package.json#L37), so it should float in automatically.

ping @ralphtheninja , lets make a new release. 😎

**Comment by ralphtheninja** [comment]
New minor or patch? cc @juliangruber @mafintosh

**Comment by peakji** [comment]
I think a patch release is enough: https://github.com/Level/leveldown/compare/v1.5.0...master Docs unmodified, all changes are transparent to users.

**Comment by ralphtheninja** [comment]
1.5.1 released

**Comment by vweevers** [comment]
One of the prebuilds ([node 7, win x86](https://ci.appveyor.com/project/Level/leveldown/build/29/job/4n88qkwh8tdi1sel)) failed:

```
Uploading 1 prebuilds(s) to Github releases
Error: Error from GitHub: Validation Failed
    at responseHandler (C:\projects\leveldown\node_modules\ghutils\ghutils.js:22:23)
    at BufferList._callback (C:\projects\leveldown\node_modules\jsonist\jsonist.js:48:7)
    at BufferList.end (C:\projects\leveldown\node_modules\bl\bl.js:89:10)
```

Seems random, I'm gonna trigger a rebuild.

**Comment by juliangruber** [comment]
appveyor passed now!

**Comment by juliangruber** [comment]
oh the glory :) https://github.com/Level/leveldown/releases

**Comment by ralphtheninja** [comment]
prebuild-ci :heart: It's such a breeze to release native addons with this setup!
