### ISSUE TITLE
node-v47 builds are missing in release

### ISSUE THREAD

**Issue by martinheidegger** [Level/leveldown#332]
This has probably to do with #331. it seems like some versions of node are not published in the release. When investigating https://github.com/workshopper/levelmeup/issues/62 I found that v47 is required for Node v5.0.0

**Comment by vweevers** [comment]
Support for Node 5 was dropped (#320), having reached end of life. Was this too soon, if 10% of users ([ballpark figure](https://twitter.com/seldo/status/781258069678391296)) are still on v5? @juliangruber @ralphtheninja 

![schedule](https://cloud.githubusercontent.com/assets/3055345/21539245/490da3c8-cda5-11e6-81ad-25d41746c1aa.png)

**Comment by ralphtheninja** [comment]
Yeah, in retrospect it was maybe not the right thing to do.

**Comment by ralphtheninja** [comment]
That said, we can always put it back and release a new patch?

**Comment by vweevers** [comment]
I vote yes. The tests are unlikely to break on v5 anytime soon, supporting it takes no effort.

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/pull/333

**Comment by juliangruber** [comment]
should be in release 1.5.2 once the builds are finished

**Comment by vweevers** [comment]
Oops, what about appveyor?

**Comment by vweevers** [comment]
#334

**Comment by ralphtheninja** [comment]
@vweevers It's easy to forget about windows ;) :rose:

**Comment by vweevers** [comment]
All good. We have 20 prebuilds now 📣 

@ralphtheninja for future releases, it might be a good idea to wait with `npm publish` until all prebuilds are finished. Because that can take a couple of hours sometimes.

**Comment by ralphtheninja** [comment]
> @ralphtheninja for future releases, it might be a good idea to wait with npm publish until all prebuilds are finished. Because that can take a couple of hours sometimes.

Aye, I thought about it immediately after hitting enter. (Hmm, maybe I should wait for prebuilds before publishing). Next time! :)
