### ISSUE TITLE
npm i leveldown fails.

### ISSUE THREAD

**Issue by Industrial** [Level/leveldown#336]
Hi.
 I'm getting errors with the command `npm i leveldown --verbose`

Here is the `npm-debug.log`; https://gist.github.com/Industrial/46cbeadcc4e71eba1ef9025737f6e409

I'm not sure what to do now.

**Comment by juliangruber** [comment]
It can't find the `prebuilt` binary which is a dependency of leveldown and should be part of the tree. This isn't the first time I have seen this error...really curious what is causing it. Could you try again with a fresh cache and recent npm?

```bash
$ npm cache clean
$ npm install -g npm@latest
$ rm -Rf node_modules
$ npm install
```

**Comment by Industrial** [comment]
I'm having the same issue. Maybe it's related to another issue I'm having:

When I run `npm install` I often get a `Maximum call stack size exceeded` error. When I run it multiple times it doesn't give me errors the second/last time so I assumed it had worked.

This is my package.json: https://github.com/Industrial/tomwieland.nl/blob/develop/package.json

**Comment by Industrial** [comment]
The problem seems to be a Vagrant + Windows Host problem, so I'm closing this ticket.

For reference; https://github.com/npm/npm/issues/9953
