### ISSUE TITLE
Build/prebuild failure - Android on ARM

### ISSUE THREAD

**Issue by robinpaulson** [Level/leveldown#343]
I tried to install a node package called 'ssb-patchwork` on Android 6 today, via the nodejs package in termux [1]. It failed at the build/prebuild for leveldown in ways I don't understand. I have seen the package leveldown-mobile, but am not sure how to use it in this case (also, there are no prebuilds available). I have included what I think are the relevant lines from npm-debug.log [2]. Is this an error in leveldown, with my build tools, or something else?

[1] http://termux.net/
[2] 7242 silly install leveldown@1.5.3 /data/data/com.termux/files/home/node_modules/.staging/leveldown-c0808a86
7243 info lifecycle leveldown@1.5.3~install: leveldown@1.5.3
7244 verbose lifecycle leveldown@1.5.3~install: unsafe-perm in lifecycle true
7245 verbose lifecycle leveldown@1.5.3~install: PATH: /data/data/com.termux/files/usr/lib/node_modules/npm/bin/node-gyp-bin:/data/data/com.termux/files/home/node_modules/leveldown/node_modules/.bin:/data/data/com.termux/files/home/node_modules/.bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
7246 verbose lifecycle leveldown@1.5.3~install: CWD: /data/data/com.termux/files/home/node_modules/leveldown
7247 silly lifecycle leveldown@1.5.3~install: Args: [ '-c', 'prebuild --install' ]
7248 silly lifecycle leveldown@1.5.3~install: Returned: code: 2  signal: null
7249 info lifecycle leveldown@1.5.3~install: Failed to exec install script

7271 verbose stack Error: leveldown@1.5.3 install: `prebuild --install`
7271 verbose stack Exit status 2
7271 verbose stack     at EventEmitter.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
7271 verbose stack     at emitTwo (events.js:106:13)
7271 verbose stack     at EventEmitter.emit (events.js:191:7)
7271 verbose stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
7271 verbose stack     at emitTwo (events.js:106:13)
7271 verbose stack     at ChildProcess.emit (events.js:191:7)
7271 verbose stack     at maybeClose (internal/child_process.js:877:16)
7271 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
7272 verbose pkgid leveldown@1.5.3
7273 verbose cwd /data/data/com.termux/files/home
7274 error Linux 3.0.101-replicant
7275 error argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "install" "ssb-patchwork"
7276 error node v6.9.3
7277 error npm  v3.10.10
7278 error code ELIFECYCLE
7279 error leveldown@1.5.3 install: `prebuild --install`
7279 error Exit status 2
7280 error Failed at the leveldown@1.5.3 install script 'prebuild --install'.
7280 error Make sure you have the latest version of node.js and npm installed.
7280 error If you do, this is most likely a problem with the leveldown package,
7280 error not with npm itself.
7280 error Tell the author that this fails on your system:
7280 error     prebuild --install

**Comment by naginagi** [comment]
I had a similar issue using termux. I had to install prebuild tool with `npm install -g prebuild`, to get to another issue: no leveldown v1.6.0 prebuild tarball available for ARM64 (it was looking for `https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v48-android-arm64.tar.gz`)
