### ISSUE TITLE
rocksdb

### ISSUE THREAD

**Issue by mcollina** [Level/leveldown#344]
Hi folks, what's the status on rocksdb?

I see there are

https://www.npmjs.com/package/rocksdown by @chjj.
https://www.npmjs.com/package/rocksdb by @rvagg.
https://www.npmjs.com/package/flat-rocks by @jmanero.

**Comment by dcousens** [comment]
Related https://github.com/Level/leveldown/issues/346

**Comment by gillesdemey** [comment]
There is also some more recent work by @dberesford https://github.com/dberesford/rocksdb-node
