### ISSUE TITLE
RocksDB integration questions [question]

### ISSUE THREAD

**Issue by cyberjar09** [Level/leveldown#346]
x-post from stackoverflow: [http://stackoverflow.com/questions/42340910/rocksdb-nodejs-integration-questions](http://stackoverflow.com/questions/42340910/rocksdb-nodejs-integration-questions)

In the process of evaluating RocksDB as a datastore for a new application that we could be potentially building (currently looking at NodeJS as the app server). I had a few takeaways from my initial exploration of the RocksDB literature. Would appreciate if anyone can clarify/correct my understanding:
1. https://www.npmjs.com/package/rocksdb does not list APIs like `MultiGet` `Snapshot` `RangeScan` `GetUpdatesSince` among others. Is is correct to assume that these are currently not implemented in the NPM module?
2. Based on the documentation, the compaction is more efficient when running on server hardware (multiple cores). I believe this would be unaffected when RocksDB is embedded inside NodeJS (question is arising from the fact that Node is single threaded).
3. Any other gotchas we need to look out for WRT RocksDB and NodeJS?

**Comment by chjj** [comment]
The `rocksdb` package has been unmaintained for a while if I remember right. I have a more up to date implementation of RocksDB for leveldown here: https://github.com/chjj/rocksdown

I haven't gone crazy with adding rocksdb features yet though.

**Comment by cyberjar09** [comment]
Thanks @chjj 
I find there is a lack of a good literature WRT RocksDB. I tried looking for a book (not even a MEAP) but was not able to find anything.

**Comment by dcousens** [comment]
@cyberjar09 did you end up using `rocksdown`?

**Comment by cyberjar09** [comment]
@dcousens No I did not use it because I did not find anything additional in terms of functionality implemented that I needed.

**Comment by ralphtheninja** [comment]
See https://github.com/Level/rocksdb for future issues/questions. Thanks.
