### ISSUE TITLE
node-gyp build failure on window server

### ISSUE THREAD

**Issue by jimmytuc** [Level/leveldown#349]
My OS: Window Server 2008 R2 64bit
Python 2.7
Microsoft Visual Studio 2013
Node: 6.9.1

This error occured while i'm trying install from git source.
C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error
C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [D:\jstest\ifthatok\leveldb\node_modules\leveldown
\deps\leveldb\leveldb.vcxproj]

![8a05e34630f948caaa7a7371223fbd3c](https://cloud.githubusercontent.com/assets/3124405/23642375/cb9354b6-032c-11e7-8b9c-62f23f99fb9e.png)
![8ac27fa918f949db9787f77d07dddc93](https://cloud.githubusercontent.com/assets/3124405/23642376/cba240d4-032c-11e7-9c2b-924762b95360.png)

Please tell me if i was wrong.

Thanks

**Comment by ralphtheninja** [comment]
Try the latest version of node. You should not need to setup a build environment for windows in order to leveldown. Also it's not really the scope of leveldown to help people with this, I know windows and native modules is a huge pain, sorry.
