### ISSUE TITLE
update to leveldb-1.20

### ISSUE THREAD

**Issue by myf** [Level/leveldown#351]
it seems that leveldb 1.20 came out, be good to update to that version

https://github.com/google/leveldb/tree/v1.20

**Comment by peakji** [comment]
PR: https://github.com/Level/leveldown/pull/353
```
# tests 947
# pass  947
✓ ok
```

@juliangruber @ralphtheninja shall we expose the new `max_file_size` options to leveldown?

**Comment by peakji** [comment]
I almost forgot that we have **Advanced options**! Added `max_file_size` 😎.
