### ISSUE TITLE
Test on multiple platforms

### ISSUE THREAD

**Issue by peakji** [Level/leveldown#355]
We now have the latest leveldb `1.20` (https://github.com/Level/leveldown/pull/353) and snappy `1.1.4` (https://github.com/Level/leveldown/pull/354) in master.

Since this is a quite a big update, I think we should leave this issue open for a few days and test in practice, I'll be testing this thoroughly on macOS and Linux.

**Comment by vweevers** [comment]
👍 

I'll smoke-test it on a Windows-based ETL project I'm running.

**Comment by peakji** [comment]
**Data Compatibility**
- [x] leveldown-master + db files from 1.6.0
- [x] leveldown-1.6.0 + db files from master

**Benchmarks**

```
# db-bench.js @ leveldown-master
Wrote 1000000 entries in 67s, 110.62MB
Database size: 97M

# db-bench.js @ leveldown-1.6.0
Wrote 1000000 entries in 79s, 110.62MB
Database size: 96M
```

**Memory**
```
# memory.js - 5min @ leveldown-master
Memory: rss=28mb, js-heap=4/9mb native-heap=18mb

# memory.js - 5min @ leveldown-1.6.0
Memory: rss=28mb, js-heap=4/9mb native-heap=18mb
```

**Comment by ralphtheninja** [comment]
@peakji How about releasing a pre-minor?

**Comment by ralphtheninja** [comment]
@juliangruber Will `prebuild-ci` work with preminor versions etc?

**Comment by peakji** [comment]
👍 for pre-minor.

**Comment by ralphtheninja** [comment]
`travis` and `appveyor` building `1.7.0-0`. Will publish once they have finished.

**Comment by ralphtheninja** [comment]
![preminor](https://cloud.githubusercontent.com/assets/308049/24956226/ffea44ce-1f86-11e7-9475-ced168291723.png)

**Comment by ralphtheninja** [comment]
@chjj Hey! I know you use leveldown pretty heavily. It would be really nice if you had time to test this preminor out and give some feedback.
