### ISSUE TITLE
AppVeyor and node 0.12.18

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#358]
When building on AppVeyor we get the following message

```
Build started
git clone -q --branch=master https://github.com/Level/leveldown.git C:\projects\leveldown
git checkout -qf 91d05e1d1ae69502116278ae216133a64646f79d
Running Install scripts
Install-Product node $env:nodejs_version $env:platform
Uninstalling node 4.8.1 (x86)...
Installing node 0.12.18 (x86)...
npm -g i npm@latest
C:\Users\appveyor\AppData\Roaming\npm\npm -> C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@4.4.4 C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm
set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
npm i --ignore-scripts
npm WARN npm npm does not support Node.js v0.12.18
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
```

@vweevers Maybe we should upgrade the node version used on AppVeyor? Something you feel like taking on? :)

**Comment by vweevers** [comment]
I think we have to downgrade npm instead (or just skip `npm -g i npm@latest`), because it looks like npm no longer supports node 0.12.

**Comment by vweevers** [comment]
Installing the latest npm used to be required for some node-gyp issue. Maybe that was for 0.10 only, I don't remember.. and I don't feel like going down that rabbit hole today ;) So how about we just remove the `npm -g i npm@latest` line from `appveyor.yml`, see what happens?

**Comment by ralphtheninja** [comment]
> So how about we just remove the npm -g i npm@latest line from appveyor.yml, see what happens?

Can't we just run the latest/a later version node?

**Comment by vweevers** [comment]
> Can't we just run the latest/a later version node?

To what? 0.12.18 is the latest 0.12, and npm dropped support for everything < 4.

**Comment by ralphtheninja** [comment]
Nevermind. I'm drunk or something. Didn't realize it was the version we were building for. Closing :)
