### ISSUE TITLE
`GLIBCXX_3.4.21` not found

### ISSUE THREAD

**Issue by kevinfoerster** [Level/leveldown#364]
I am getting an error that the correct version GLIBC was not found.
`Error: /package/host/localhost/gcc-4/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found`

this is kind of true…
`strings /package/host/localhost/gcc-4/lib64/libstdc++.so.6 | grep GLIBCXX` shows no matching version number. 

unfortunately my system is supposed to use a different path for Libraries to include: 
`echo $LD_LIBRARY_PATH 
/package/host/localhost/gcc-5/lib64`

so, when I run `strings /package/host/localhost/gcc-5/lib64/libstdc++.so.6 | grep GLIBCXX` I see the right version number but the file is not being used, because `$LD_LIBRARY_PATH` seems to be ignored by node/leveldown.

any idea how to change this?

ps. moving or symlinking the file is not an option

**Comment by vweevers** [comment]
Is this still an issue?

**Comment by vweevers** [comment]
Closing for lack of feedback. Feel free to reopen if still an issue.
