### ISSUE TITLE
prebuilt files for node 8.0

### ISSUE THREAD

**Issue by JamesKyburz** [Level/leveldown#365]
Could we please publish the prebuilt files for node 8.0 `leveldown-v1.7.0-node-v57*`

**Comment by ralphtheninja** [comment]
@juliangruber Would restarting the latest build on travis make this update? (Since I assume `prebuild-ci` would need an updated version of `node-abi`)

**Comment by ralphtheninja** [comment]
@juliangruber Aah of course. We need to update `.travis.yml` for this to work, right?

**Comment by ralphtheninja** [comment]
@JamesKyburz I'll just release `1.7.1` instead and it will build all on travis and appveyor. We need to update `.travis.yml` and `appveyor.yml` anyway.

**Comment by JamesKyburz** [comment]
@ralphtheninja Nice thanks!

**Comment by juliangruber** [comment]
@ralphtheninja correct! We need to update `.travis.yml`, and `node-abi` needs to be fresh enough.
