### ISSUE TITLE
error if I close while a create read stream is running/started

### ISSUE THREAD

**Issue by dominictarr** [Level/leveldown#37]
this comes in a few flavors,
if you create close before the stream is 'ready',
then it will not have an iterator. (this is probably fixed by my previous commit, that is coming into 0.9)

next, if it happens while the stream is still reading,
readStream tries to call `next()` after `end()`.

I'm gonna get something to eat, and then I'll add a test for this after.

**Comment by ralphtheninja** [comment]
@dominictarr @mcollina Can this issue be closed?

**Comment by dominictarr** [comment]
this is really old and I havn't encounted a problem like this recently, so it's probably okay to close.

**Comment by ralphtheninja** [comment]
> this is really old and I havn't encounted a problem like this recently, so it's probably okay to close.

:+1: 

Just trying to clean up some stuff.

**Comment by mvayngrib** [comment]
@dominictarr @ralphtheninja

i still get segfaults on close() when iterators are still going

os: osx 10.12.1
node: 6.5.0 (same result with node 0.12.7)
leveldown: 1.5.0

the below code gives me a segfault every time, but often dies peacefully with smaller N (10, 100, 1000):

```js
const level = require('level')
const db = level('./test.db')
const N = 10000
const batch = []
for (var i = 0; i < N; i++) {
  batch.push({ type: 'put', key: i, value: 'a' })
}

db.batch(batch, function (err) {
  if (err) throw err

  db.createReadStream()
    .once('data', function (data) {
      db.close()
    })
})
```

**Comment by ralphtheninja** [comment]
@mvayngrib

Does the following work better?

```js
db.createReadStream().once('end', db.close.bind(db))
```

**Comment by mvayngrib** [comment]
@ralphtheninja you mean instead of the 'data' handler?

**Comment by ralphtheninja** [comment]
> @ralphtheninja you mean instead of the 'data' handler?

Yep

**Comment by mvayngrib** [comment]
this works fine, but then it doesn't test the close during iteration condition:
```js
const level = require('level')
const db = level('./test.db')
const N = 10000
const batch = []
for (var i = 0; i < N; i++) {
  batch.push({ type: 'put', key: i, value: 'a' })
}

db.batch(batch, function (err) {
  if (err) throw err

  db.createReadStream()
    .once('end', db.close.bind(db))
})
```

**Comment by ralphtheninja** [comment]
@mvayngrib Aye, I realized that after I asked you :) It should be a good test case. This problem is still not solved in leveldown.

**Comment by mvayngrib** [comment]
@ralphtheninja haha ok. Is this issue the best place to monitor the discussion / progress?

**Comment by ralphtheninja** [comment]
Can confirm it's still a problem on `1.7.1`

**Comment by ralphtheninja** [comment]
This no longer segfaults in version `1.7.2`. Instead you get an error on the readable stream. We should add a test for this.

**Comment by mvayngrib** [comment]
@ralphtheninja the above the test still gives me a segfault:

```sh
$ grep version node_modules/leveldown/package.json 
  "version": "1.7.2",
~/Code/leveldown-segfault
$ node index.js 
Segmentation fault: 11
~/Code/leveldown-segfault
```

**Comment by ralphtheninja** [comment]
@mvayngrib Ok, re-opening

> @ralphtheninja the above the test still gives me a segfault:

"the above the test"? Please post the snippet in a new comment.

**Comment by mvayngrib** [comment]
@ralphtheninja sure, this one:

```js
const level = require('level')
const db = level('./test.db')
const N = 10000
const batch = []
for (var i = 0; i < N; i++) {
  batch.push({ type: 'put', key: i, value: 'a' })
}

db.batch(batch, function (err) {
  if (err) throw err

  db.createReadStream()
    .once('data', function (data) {
      db.close()
    })
})
```

**Comment by mvayngrib** [comment]
@ralphtheninja oops, that's my bad. I had two version of leveldown. Awesome! Feel free to close
