### ISSUE TITLE
create test for createReadStream error while closing the db

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#370]
See https://github.com/Level/leveldown/issues/37 and https://github.com/Level/leveldown/issues/37#issuecomment-267845120 for background

**Comment by vweevers** [comment]
@ralphtheninja woa you've been a busy bee :)

**Comment by ralphtheninja** [comment]
:trollface:

**Comment by vweevers** [comment]
This is covered now, by the combination of https://github.com/level/leveldown/issues/514, https://github.com/Level/leveldown/issues/597, https://github.com/Level/leveldown/issues/612 and https://github.com/Level/iterator-stream/pull/34 (the latter ensures the iterator is ended on an error, the former ensure that closing the db waits for pending operations).
