### ISSUE TITLE
Synchronous Methods

### ISSUE THREAD

**Issue by kriszyp** [Level/leveldown#372]
I think there can some compelling reasons to offer synchronous versions of the leveldown functions (returning immediately without a callback, not disc sync). Sometimes synchronous can simply be easier to reason about (less race conditions to consider with other code running while waiting). And, in particular with leveldb with small-valued databases, gets and puts are often faster than node's worker/queue mechanism, the queuing of the event callback can take more time than the operation itself.

There has been some prior work to add this functionality here:
https://github.com/snowyu/node-nosql-leveldb
This is out-of-date and no longer seems to compile. I have been updating/porting some of the synchronous functions in my own branch for our purposes:
https://github.com/kriszyp/leveldown

I am just curious if such efforts might be considered for upstream merging? I am fine with just using my own branch for our application, and I haven't really completed a full set of sync methods, I just converted enough functionality for our own purposes, but would there be value in having a full set of synchronous equivalent functions in the main leveldown repo?

And thanks for the great package, this has been incredibly valuable to us!

**Comment by peakji** [comment]
👍 for `openSync`, `getSync`, and `putSync`. We often use leveldown as a huge counter dict for simple analytics jobs, atomic ops (like `INCR` in **Redis** or `findAndModify` in **MongoDB**) could be implemented easier with these sync methods.

But as discussed in https://github.com/Level/leveldown/pull/136, do we really need sync iterator? The iterator code is quite complicated already 😰.

**Comment by ralphtheninja** [comment]
I don't mind adding sync functionality if others find it useful. When implementing tests we should consider updating `abstract-leveldown` as well so other down implementations can implement their own sync methods.

**Comment by frankboehmer** [comment]
+1 for getSync, putSync, delSync. Could massively improve performance for certain use cases.

**Comment by zixia** [comment]
@snowyu Thanks for the reference to the bug.

How can I test your updated code? I'd like to confirm this bug ASAP because recently I meet it in my production environment every day.

Related to https://github.com/Chatie/wechaty/issues/1355

**Comment by zixia** [comment]
@snowyu Thank you very much. I'm updating my module right now and will get back to you when I have any results.

**Comment by zixia** [comment]
@snowyu had you tested `nosql-leveldb` under mac?

I got a `Segmentation fault` when run test in TravisCI, which worked without problem with `leveldown` before.

See: https://travis-ci.com/zixia/flash-store/jobs/130978289

**Comment by vweevers** [comment]
Please continue further discussion about `nosql-leveldb` in its own repo.

**Comment by zixia** [comment]
@vweevers Ok. 

@snowyu Can you enable **Issue** for your repository? Becasue you forked it from the `leveldown`, by default we can not file issue on your repo.

**Comment by snowyu** [comment]
@zixia  done.  

I've found the reason:  the c++11 feature `std:mutex` raised error on Mac.

**Comment by ccorcos** [comment]
For those interested in an immediate solution: https://github.com/Level/mem/pull/50
