### ISSUE TITLE
Read-only DB open

### ISSUE THREAD

**Issue by acacio** [Level/leveldown#376]
Hi,

as exhibited by the existence and popularity of layers like [multileveldown](/mafintosh/multileveldown) and [multilevel](/juliangruber/multilevel), the need for concurrent read-only access to a DB is a common occurrence.

It would be great if this functionality was part of the core leveldown API, allowing for a model of:
- 1 "master" read-write process
- many "read-only" **eventually consistent** processes

By dropping for the need of a fully consistent view of the DB, it can be made less complex to implement.

Thank you,
Acacio

**Comment by peakji** [comment]
Hi Acacio,

AFAIK, the core LevelDB is designed as an embedded database for a **single process** with no read-only mode.

Here are some workarounds: https://stackoverflow.com/questions/9177598/multiple-instances-of-a-leveldb-database-at-the-same-time

And you could try RocksDB, which provides native read-only mode, through our new [Level/rocksdb](https://github.com/Level/rocksdb).

**Comment by vweevers** [comment]
Replication is an opinionated process that doesn't belong in a low-level part like `leveldown`. There are many modules available that provide replication *on top of* leveldown.
