### ISSUE TITLE
Readme: merge "Prebuilt binaries" into "Supported platforms"

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#380]
I feel like [Prebuilt binaries](https://github.com/level/leveldown#prebuilt-binaries) deserves to be higher up and suggest merging it with [Tested & supported platforms](https://github.com/level/leveldown#tested--supported-platforms). Like:

- Open with "LevelDOWN ships with prebuilt binaries for [many platforms](https://github.com/Level/leveldown/releases)."
- List platforms that are officially supported but have no prebuilds. For those, refer to [`node-gyp` installation instructions](https://github.com/TooTallNate/node-gyp#installation).
- Also mention supported Node.js versions
- With that, we can drop the Windows notes.

WDYT @ralphtheninja?

**Comment by ralphtheninja** [comment]
Sounds good!

**Comment by vweevers** [comment]
Do we want to drop node 4 and 0.12 here too?

**Comment by ralphtheninja** [comment]
> Do we want to drop node 4 and 0.12 here too?

I think so. Maybe we should have an official statement on which node versions we aim to support. From e.g. the latest major version and two major versions back as an example.

**Comment by vweevers** [comment]
I like that. Suggestion: "We aim to support *at least* Active LTS and Current Node.js releases." Which is currently 6.x and 8.x, respectively.

Could also add a version badge. By adding `"engines": { "node": ">= 5.x" }` to `package.json` and then using `https://img.shields.io/node/v/leveldown.svg`. Or if someone objects to that, a manual badge: `https://img.shields.io/badge/node-%3E%3D%205.x-brightgreen.svg`. Either one would show as:

![Node version](https://img.shields.io/badge/node-%3E%3D%205.x-brightgreen.svg)

**Comment by mcollina** [comment]
I think dropping support for Node.js versions should be semver-major change.

We might want to think of using n-api. We are currently discussing the possibility to have a "single binary to rule them all", including both 4 and 6 on Linux and Mac (not Windows).
