### ISSUE TITLE
create prebuilts for alpine linux?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#388]
Alpine linux seems to be very commonly used in the docker world. For this reason it would be really nice to have prebuilt binaries for that particular environment. I'm guessing right now `prebuild-install` picks the wrong binaries with a segfault as a result.

See https://github.com/Level/levelup/issues/484 for some background

**Comment by ralphtheninja** [comment]
Workaround for alpine linux users at the moment is to use `--build-from-source` when installing e.g. `level` (or `leveldown` directly)

**Comment by dcharbonnier** [comment]
I don't think it's possible with yarn @ralphtheninja

**Comment by vweevers** [comment]
Some context:

> As Alpine Linux uses musl, you may run into some issues with environments expecting glibc-like behavior – especially if you try to use binaries compiled with glibc. You should recompile these binaries to use musl (compiling on Alpine is probably the easiest way to do this).
> -- [(source)](https://github.com/mhart/alpine-node#caveats) (https://github.com/mhart/alpine-node/issues/107)

A possible solution is to:

1. Compile prebuilds in an alpine Docker container
1. Add a `'-musl'` suffix to prebuild names
1. Use https://github.com/lovell/detect-libc at npm install time (to force compile if no matching prebuild is found) and run time (to select the right prebuild)

**Comment by vweevers** [comment]
Tasks:

- [ ] Create docker image: https://github.com/prebuild/docker-images/issues/6
- [ ] Create Travis job, named `alpine`, similar to the `arm` job, with `--tag-libc`
