### ISSUE TITLE
tweak readme

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#396]
- [x] travis badge should be svg and not png
- [x] make sure travis and appveyor have different looks
- [x] LevelDOWN -> leveldown
- [x] LevelUP -> levelup
- [x] add downloads badge (see memdown)
- [x] remove big npm download badges
- [x] unquote properties
- [x] Node.js Buffer objects => Buffers
- [x] `String`s => strings
- [x] JavaScript `String`s => strings
- [x] A richer set of data-types are catered => A richer set of data-types is catered

Anything else?

**Comment by vweevers** [comment]
Also LevelUP => levelup

**Comment by ralphtheninja** [comment]
@vweevers Maybe we should remove the quoted properties as well, like you did for levelup

**Comment by vweevers** [comment]
Also noticed:

- [ ] Node.js Buffer objects => Buffers
- [ ] `String`s => strings
- [ ] JavaScript `String`s => strings
