### ISSUE TITLE
Fix documentation of `asBuffer` option

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#398]
In [the options for `get()`](https://github.com/Level/leveldown/blob/ad98a02132506cda88015636a052112392de6bcb/README.md#options-2) it says:

> if you need a string [..] you should fetch it as one with `{ asBuffer: true }`.

I *think* that should be `{ asBuffer: false }`.

@ralphtheninja @juliangruber

**Comment by ralphtheninja** [comment]
At first I thought I introduced this when re-writing the README but it seems it has been around for a while. Also, since _default_ is `true` it seems wrong to tell the user to actually use `true` when it's not even needed (since it's default).

**Comment by juliangruber** [comment]
SGTM, for now we can just invert the object and this option's documentation should be good enough.
