### ISSUE TITLE
Trace/breakpoint trap on MIPS 24KEc

### ISSUE THREAD

**Issue by mitsos1os** [Level/leveldown#403]
Hi guys,
We are running LEDE 17.01.4 on a mipsel 24KEc CPU and cross compiling NodeJS v8.9.0 along with leveldown (the actual chain is mqtt-level-store -> level-browserify -> leveldown) using the package configuration of [nxhack](https://github.com/nxhack/openwrt-node-packages).

We also install LinvoDB3 which also uses Leveldown as dependency. We can write successfully to the localstorage using the engine, however when we try to read from it we get Trace/breakpoint trap which exits NodeJS process....

This did not use to happen on older Node version such as 6.10 on the same platform, and right now everything else that we compile (like node-serialport) runs successfully without any problems.

Any ideas please?

**Comment by ralphtheninja** [comment]
> We also install LinvoDB3 which also uses Leveldown as dependency. We can write successfully to the localstorage using the engine, however when we try to read from it we get Trace/breakpoint trap which exits NodeJS process....

Do you have any more information, such as core dump etc?

**Comment by mitsos1os** [comment]
Thank you for the prompt response. I do not have any extra info. But if you guide me I can provide you with anything you need...

**Comment by ralphtheninja** [comment]
First you need to compile `leveldown` with debug symbols, e.g.

```
$ npm i node-gyp -g
$ node-gyp rebuild --debug
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/lms/.nvm/versions/node/v8.4.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/lms/src/level/leveldown/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/lms/.nvm/versions/node/v8.4.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/lms/.node-gyp/8.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/lms/.node-gyp/8.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/lms/.nvm/versions/node/v8.4.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/lms/.node-gyp/8.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/lms/src/level/leveldown',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Debug', '-C', 'build', '--jobs', 4 ]
make: Entering directory '/home/lms/src/level/leveldown/build'
  CXX(target) Debug/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Debug/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Debug/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Debug/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
...
```

I'm unsure how to get core dumps on `OpenWRT` so you would have to do some research there and how to debug them using e.g. gdb or similar. Either way, compiling `leveldown` with debug symbols is essential and is the first step.

**Comment by ggkitsas** [comment]
Hello,
We work together on this issue with mitsos1os. You can find a core dump here:
https://mega.nz/#!R2ZRATga!2AgerN3w0hTgd8oJUhipmaBzzCqPTci4xts4-Td53Fk
