### ISSUE TITLE
not compiling on Mac 

### ISSUE THREAD

**Issue by arpecop** [Level/leveldown#407]
Node 9.2.0 (latest) just refuses to install/compile level down (any version) on Mac OS and Linux, anyone experiencing the same?

**Comment by ralphtheninja** [comment]
@arpecop What output do you get when compiling?

**Comment by arpecop** [comment]
`➜  ~ heroku run bash --app vault101
Running bash on ⬢ vault101... up, run.1999 (Free)
~ $ node -v
v9.2.0
~ $ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
~ $ cd /tmp/
/tmp $ npm install levelup leveldown

> leveldown@2.0.1 install /tmp/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /app/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.0.1-leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v2.0.1/leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v2.0.1/leveldown-v2.0.1-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.2.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/tmp/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
make: g++: Command not found
deps/leveldb/leveldb.target.mk:148: recipe for target 'Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o' failed
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o] Error 127
make: Leaving directory '/tmp/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.13.0-133-generic
gyp ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/leveldown
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@2.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-11-18T12_30_01_273Z-debug.log`

**Comment by vweevers** [comment]
It looks like you're missing a compiler toolchain (`make: g++: Command not found`). For Ubuntu, `apt-get install build-essential` or `apt-get install g++` (because you already have `make`) should cover it.
