### ISSUE TITLE
upgrade from leveldown 1.4.6

### ISSUE THREAD

**Issue by astracz** [Level/leveldown#416]
The changelog hasn't been updated in a while and while the commits seem to not affect backwards compatibility with the leveldb content, I don't know. I'm upgrading from node v6 and leveldown 1.4.6 prebuilts to node v8 and the latest leveldown release.

Can someone give me a summary of whether it's okay to upgrade or what I should pay attention to?

**Comment by ralphtheninja** [comment]
New major was released when we dropped support for `0.12` so you should be fine.
