### ISSUE TITLE
 OpenError: IO error: LockFile

### ISSUE THREAD

**Issue by EasonWang01** [Level/leveldown#419]
```js
function initDB() {
  return levelup(leveldown(path.join(__dirname, `DB${process.env.PORT}`)));
}

```
which will result in error but process.env.PORT is a number not undefined.
And if I using a constant for the DB name it will works fine.

**Comment by ralphtheninja** [comment]
I can't reproduce this. Even `undefined` as port yields a `DBundefined` folder.

**Comment by peakji** [comment]
I guess its not about `process.env.PORT`, this error means the database is **locked**.

A leveldb database may only be opened by one process at a time, please check your background processes.

**Comment by EasonWang01** [comment]
Thanks for reply.
In MacOS works fine,I will restart my windows computer tomorrow.

**Comment by vweevers** [comment]
@EasonWang01 if it helps: on Windows, it's (more) important to properly close db's (and await the callback) before you try to reopen them.

**Comment by EasonWang01** [comment]
I close it each time when finishing it,this is happend at the first time for starting DB.
Will check is another process still running tomorrow.

**Comment by EasonWang01** [comment]
Ok,confirm it always happen on Windows 10.

**Comment by EasonWang01** [comment]
The problem is using ` set process.env.PORT`will got one additional space at the end.After trim it works good.
