### ISSUE TITLE
testdata folder is published on npm

### ISSUE THREAD

**Issue by kenshyx** [Level/leveldown#420]
`deps/snappy/snappy-1.1.4/testdata` should be removed when publishing to npm. It seems this rule `deps/snappy/snappy-*/testdata/` from `.npmignore` is not working.

**Comment by ralphtheninja** [comment]
Which version of `leveldown` are you using? Seems to work when I install `2.1.1`.

**Comment by kenshyx** [comment]
I'm using `v1.9.0`.

**Comment by ralphtheninja** [comment]
Well, there you go :)

**Comment by kenshyx** [comment]
Hehe thx :D
