### ISSUE TITLE
Database size keep increasing forever

### ISSUE THREAD

**Issue by terrybleger** [Level/leveldown#435]
Do I really have to create separate folder/instance just to re-write a key? Since every put/del operation will increase the database size. Calling repair won't help anyway, only calling destroy or rm the directory manually will reset the size since I will have to create a new instance, but I have to do this for every key and I have to create separate folders for each key/instance that I don't want the size to keep increasing.

Why don't it just creates two ldb files for old & new instead of unlimited ldb files?

**Comment by vweevers** [comment]
You can [manually trigger compaction](https://github.com/Level/leveldown#leveldowncompactrangestart-end-callback) or tune LevelDB through [the options](https://github.com/Level/leveldown#leveldownopenoptions-callback), in particular the advanced options. Note the caveat:

> Modify them only if you can prove actual benefit for your particular application.
