### ISSUE TITLE
Older versions of leveldown are broken on node 10

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#455]
It turns out older versions of leveldown are broken on node 10 so if there aren't any prebuilt binaries (which is highly unlikely since we haven't built any for node 10 on older versions) installs must be able to build leveldown, which they can't.

It seems to me that `v2.0.2` and above works with node 10 (albeit some deprecation warnings) but `v2.0.1` and below are broken.

See https://github.com/Level/leveldown/issues/448 for background.

Build error:

```
In file included from ../node_modules/nan/nan.h:192:0,
                 from ../src/leveldown.h:11,
                 from ../src/database.cc:12:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../node_modules/nan/nan.h:192:0,
                 from ../src/batch.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../node_modules/nan/nan.h:192:0,
                 from ../src/database.h:16,
                 from ../src/database_async.cc:12:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
```

**Comment by vweevers** [comment]
Considering the age of node 10 (4 days) and the age of leveldown 2.0.1 (6 months), that's perfectly acceptable IMO.

**Comment by ralphtheninja** [comment]
> Considering the age of node 10 (4 days) and the age of leveldown 2.0.1 (6 months), that's perfectly acceptable IMO.

Maybe acceptable for now. The question is what to do about it. If we should do something about it.

**Comment by vweevers** [comment]
Should we do something about it?

[![](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/Yes.%20Patch%201.9)](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/Yes.%20Patch%201.9/vote)
[![](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/Yes.%20Patch%201.9%2C%201.8%2C%201.7%2C%20..)](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/Yes.%20Patch%201.9%2C%201.8%2C%201.7%2C%20../vote)
[![](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/No.%20Users%20should%20update%20to%20%3E%3D%202)](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/No.%20Users%20should%20update%20to%20%3E%3D%202/vote)
[![](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/No%2C%20but%20add%20a%20warning%20to%20README)](https://api.gh-polls.com/poll/01CC5QQZCKAZF43MS3S1174CYQ/No%2C%20but%20add%20a%20warning%20to%20README/vote)

**Comment by MongoExpUser** [comment]
I had the same problem when I upgraded to **Node 10.**

After looking around, I tried several versions of **Leveldown**.  Eventually, I came to the same conclusion as **ralphtheninja**  stated above.

Only **Leveldown v 2.0.2** looks like the only solution for now...

**Comment by ralphtheninja** [comment]
> Only Leveldown v 2.0.2 looks like the only solution for now...

`v2.0.2` and _above_ should work, e.g. `v2.1.0`, `v2.1.1`, `v3.0.0` and `v3.0.1`.

**Comment by MongoExpUser** [comment]
ralphtheninja,
I have been working on this for almost 3 days. I tried  versions **above 2.0.2** with no luck. I systematicallly tested all the version **from 1.7.2 upward.**..

Only version 2.0.2  keeps my **Level DB Server** running without any crash or error or **lock-up**.

I guess my situation might be different since what I am actually using is **Level-party** (for clusters/multi-processes/multi-processors) which bundled **Level 1.7.0** and **Leveldown 1.7.2** as dependencies.

So, I  changed the Leveldown dependency within Level-party from 1.7.2 to 2.0.2 and the Level DB Server  finally worked as expected.

**Comment by ralphtheninja** [comment]
> Only version 2.0.2 keeps my Level DB Server running without any crash or error or lock-up.

What kind of crashes, errors or lock-ups are you having? This is valuable information to us. It would be really nice if you could share it.

**Comment by MongoExpUser** [comment]
ralphtheninja,
Thank you very much for your last post. There are broadly two categories in general:

1) Could not not compile some dependencies with **node-gyp**.
2) lock of up of **Leveldb** when 2 or more processes try to access the **db**. Again, this is related to level-party internal workings and dependencies.

These errors are now resolved as I mentioned in my earlier post.

**Comment by vweevers** [comment]
Please see [UPGRADING.md](https://github.com/Level/leveldown/blob/master/UPGRADING.md#v301):

> If you're using node v10 you'll need at least `leveldown@2.0.1` to successfully compile. In addition, if you want prebuilt binaries you'll need at least `leveldown@3.0.1`.
