### ISSUE TITLE
Document highWaterMark

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#468]

**Comment by ralphtheninja** [comment]
I still don't know what it does

**Comment by peakji** [comment]
+1 for documenting `highWaterMark`.

The default `highWaterMark` will pre-load more than necessary for some use cases.

In one of my hobby project, I use leveldown to store a large number of news articles form different sources. For analyzing, I just want 10 docs per source, so I use an iterator to seek to the prefix and terminate early.

From my experience, setting a low `highWaterMark` could bring significant performance boost (5 - 100 x) for early termination use cases.

**Comment by vweevers** [comment]
Done in [`classic-level`](https://github.com/Level/classic-level/pull/1), the replacement for `leveldown`: https://github.com/Level/classic-level/pull/1. I will not document it in `leveldown` because that's more involved, due to the `highWaterMark` option conflicting with streams. So docs would also have to explain that and how to get around it, but at that point I'd recommend to switch to `classic-level` instead. Also because it has a new `nextv()` method which removes one of the use cases of `highWaterMark` (namely to decrease rather than increase it).
