### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#474]

**Comment by ralphtheninja** [comment]
I'll rebase the branch and create a PR meanwhile.

**Comment by MeirionHughes** [comment]
well; where they are at the moment does work: 

```
yarn add Level/level-typings -D
yarn add Level/levelup
yarn add Level/memdown
```
doesn't install any of the devDependencies in level-typings (which installs everything to do a quick test). and with tsconfig: 

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "types": [
      "node",
      "level-typings"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```
you do get typings. 

![image](https://user-images.githubusercontent.com/3584509/40087305-e6be57ea-5899-11e8-8c7d-be2270edd2a2.png)

still think it needs another set of eyes to run over it - Might be a bit easier now as all the typings are in one place.
