### ISSUE TITLE
Provide prebuilt binaries for laster node version

### ISSUE THREAD

**Issue by jeremad** [Level/leveldown#538]
```prebuild-install WARN install No prebuilt binaries found (target=10.14.0 runtime=node arch=x64 platform=win32)```

It looks like only there is prebuilt binaries only for older versions of node. This is too bad since node-gyp requires python2, and you don't want everybody to mess up with their python configuration!

**Comment by vweevers** [comment]
Which version of `leveldown` are you installing? Because:

> If you're using node v10 you'll need at least `leveldown@2.0.1` to successfully compile. In addition, if you want prebuilt binaries you'll need at least `leveldown@3.0.1`.

**Comment by jeremad** [comment]
Indeed I was using a dependency that depended on level 2.something. Thanks guys!
