### ISSUE TITLE
Split up binding.cc

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#542]
TBD after #540 is merged.

**Comment by ralphtheninja** [comment]
I have no problem with splitting `binding.cc` into multiple parts. I propose something like:

```
$ tree src/
src/
├── batch.cc
├── batch.h
├── common.cc
├── common.h
├── database.cc
├── database.h
├── iterator.cc
├── iterator.h
├── main.cc
├── workers.cc
└── workers.h

0 directories, 11 files
```

@vweevers I also thought that maybe you could do this. It would be a good exercise for you to get some of that code into your head, so it's not only in mine. WDYT?

**Comment by ralphtheninja** [comment]
Or maybe:

```
$ tree src/
src/
├── common.cc
├── common.h
├── context.cc
├── context.h
├── main.cc
├── workers.cc
└── workers.h

0 directories, 7 files
```

Where `context.{h,cc}` would contain `Database`, `Iterator` and `Batch` classes.

**Comment by vweevers** [comment]
By "common" you mean the macros and helpers?

**Comment by ralphtheninja** [comment]
> By "common" you mean the macros and helpers?

Yeah, basically any code that needs to be shared between files. Macros and function signatures goes into the header file, function implementations in .cc.

**Comment by vweevers** [comment]
I'm fine with the way it is now.
