### ISSUE TITLE
Specify minimum node version(s) with non-experimental N-API in package.json

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#547]
Current:

https://github.com/Level/leveldown/blob/b49194f482139244cde4b0fa478abbe1ebd68c80/package.json#L60-L62

**Comment by ralphtheninja** [comment]
I _think_ we can use https://github.com/nodejs/node-addon-api and keep supporting node v6, but not sure. It would be great if we could get this out without pulling support for existing node versions.

**Comment by ralphtheninja** [comment]
Some off github discussions led us to stop supporting node 6. It's soon reaching EOL anyway.

**Comment by vweevers** [comment]
Done in #552
