### ISSUE TITLE
Add npm script to pull binaries from CI, before npm publish

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#557]
Using `prebuildify-ci download`. Also, should we document this required step? @ralphtheninja

**Comment by ralphtheninja** [comment]
> Using `prebuildify-ci download`. Also, should we document this required step? @ralphtheninja

Yeah, lets do it for transparency and if anyone is wondering about it.

**Comment by ralphtheninja** [comment]
Ps. It's also nice to have around, even if you _do_ know it, as a check list.

**Comment by vweevers** [comment]
> Ps. It's also nice to have around, even if you do know it, as a check list.

Agree, esp. because the "build flows" are now different for leveldown, rocksdb, etc
