### ISSUE TITLE
Level doesn't properly work with Unix and msgpack loaded

### ISSUE THREAD

**Issue by KenanSulayman** [Level/leveldown#56]
~~We're not able to deploy databases created on OSX to servers running same-environment (Node, same modules, same architecture) on CentOS.~~ *Level does not work properly on Unix environments with msgpack loaded though both work standalone.*

It fails horribly: http://f.cl.ly/items/0Y3O200g2d3v1Q0S1R2R/Text%202013.08.22%2019%3A04%3A43.txt.

Any idea?

**Comment by ralphtheninja** [comment]
@KenanSulayman Is this still a problem? The please re-open if that's the case.
