### ISSUE TITLE
Fix warning in LevelDB

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#568]
![screenshot from 2018-12-16 22-43-19](https://user-images.githubusercontent.com/308049/50059207-0e601700-0184-11e9-916f-fb12fe1c3253.png)

**Comment by vweevers** [comment]
Happens on L38 and L41: 

https://github.com/Level/leveldown/blob/ebf1ef112634b02cf0e0e043297f7ac378aebb84/deps/leveldb/leveldb-1.20/util/hash.cc#L35-L46

LevelDB expects the `FALLTHROUGH_INTENDED` macro to be defined externally. We don't do that, so we get a warning. To get rid of it (at least in GCC 7) we can do one of: 

A (adapted from a comment [here](https://lwn.net/Articles/794944/)):

```cpp
#if !defined(FALLTHROUGH_INTENDED) && defined(__has_cpp_attribute)
  #if __has_cpp_attribute(fallthrough)
    #define FALLTHROUGH_INTENDED [[fallthrough]]
  #elif __has_cpp_attribute(gnu::fallthrough)
    #define FALLTHROUGH_INTENDED [[gnu::fallthrough]]
  #endif
#endif

#if !defined(FALLTHROUGH_INTENDED) && defined(__has_attribute)
  #if __has_attribute(__fallthrough__)
    #define FALLTHROUGH_INTENDED __attribute__((__fallthrough__))
  #endif
#endif
```

B (slightly cleaner but less compatible, adapted from [here](https://github.com/google/re2/blob/ab12219ba56a47200385673446b5d371548c25db/util/util.h#L28-L36)):

```cpp
#ifndef FALLTHROUGH_INTENDED
#if defined(__clang__)
#define FALLTHROUGH_INTENDED [[clang::fallthrough]]
#elif defined(__GNUC__) && __GNUC__ >= 7
#define FALLTHROUGH_INTENDED [[gnu::fallthrough]]
#endif
#endif
```

Or C: do nothing, it's only a warning.

**Comment by vweevers** [comment]
> C: do nothing, it's only a warning.

Aye
