### ISSUE TITLE
Can we reuse binding.cc code in e.g. rocksdb?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown#570]
It would be nice if we could re-use the glue code for e.g. `rocksdb` so it could be based on napi as well, `leveldownmiddle`? :grin:

At least spend some time thinking about this. In theory it should be possible to extract the glue code into a separate module, given that the underlying store exposes the same api.

**Comment by vweevers** [comment]
By glue code, do you mean the JS, `binding.cc` or both?

Would it still be possible to add RocksDB-specific options (https://github.com/Level/rocksdb/issues/13)?

**Comment by ralphtheninja** [comment]
> By glue code, do you mean the JS, `binding.cc` or both?

Aah sorry this was a bit unclear. I meant the `binding.cc` code.



> Would it still be possible to add RocksDB-specific options ([Level/rocksdb#13](https://github.com/Level/rocksdb/issues/13))?

Good question. We might need to do some tweaks to the binding code.

**Comment by vweevers** [comment]
I don't know how to achieve this, taking the differences (https://github.com/Level/rocksdb/issues/100#issuecomment-480587457) into account.

What I can do, is copy `binding.cc` verbatim from `leveldown` to `rocksdb` and make sure this ends up in its own commit (A) in master. Then record the necessary RocksDB changes in a second commit (B). Future `leveldown` changes can be cherry-picked onto master, but should we get into big merge conflicts, we also have the option of reapplying B - which will be relatively small - onto a new `binding.cc`.

Namespace aliases (`namespace leveldb = rocksdb`) could make B even smaller.

**Comment by vweevers** [comment]
Closing for now; if anyone has ideas to tackle this they're welcome.

Until then, the situation is not that bad. It's just a matter of keeping `rocksdb` in sync with `leveldown`, usually by cherry-picking commits, and doing it frequently makes it easier.
