### ISSUE TITLE
AppVeyor build for v5.0.0-1 failed

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#578]
```
Collecting artifacts...
Found artifact 'prebuilds' matching 'prebuilds' path
Uploading artifacts...
[1/1] v5.0.0-1-win-x64.zip (467,857 bytes)...100%
Deploying using GitHub provider
Creating "v5.0.0-1" release for repository "Level/leveldown" tag "v5.0.0-1" commit 
"058fba171451cbb2aec9655ac9a17b2b254c058d"...Error creating GitHub release: Provider setting not
 found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML 
was exported) while being logged under correct account.
Parameter name: auth_token
```

Weird, because it worked on the previous tagged build (5.0.0-0) and there has been no change to `appveyor.yml`.

**Comment by vweevers** [comment]
![image](https://user-images.githubusercontent.com/3055345/50497858-ef8f3980-0a3b-11e9-8359-448ca825fe7d.png)

Wait what

**Comment by vweevers** [comment]
Oh, there are 2 active accounts on AppVeyor. [Julian's](https://ci.appveyor.com/project/juliangruber/leveldown/) and [Level's](https://ci.appveyor.com/project/Level/leveldown/). In some places, GitHub status updates link to Julian's account, of which the build failed (because I created the secret with the Level account). The build on Level's account did succeed.

Since when has this been the case? 🤔

**Comment by vweevers** [comment]
@juliangruber Can you please remove leveldown from your AppVeyor account? Thanks 💯

**Comment by ralphtheninja** [comment]
> Since when has this been the case? thinking

Yeah, this is a bit odd. We haven't changed anything here. However, the difference is that we're not deploying the binaries in the same way as before, which was handled by `prebuild` (via `ghreleases` module).

**Comment by ralphtheninja** [comment]
@juliangruber ping?

**Comment by vweevers** [comment]
FYI @juliangruber @peakji I've deactivated two webhooks for AppVeyor, which I believe belong to your accounts.
