### ISSUE TITLE
idea for fast bulk inserts

### ISSUE THREAD

**Issue by dominictarr** [Level/leveldown#58]
So, I've heard that it's fastest to insert records in reverse because of the skip list.

This is not how data is normally stored... much more often, it's in the other direction.

But, what if you reversed the comparator?

Then the database would think you are inserting everything in reverse!
So, maybe this would "just work" more often?

Another idea: what if you could make a few optimizations to the skip list,
like, remember the last point you inserted, so if you are often inserting a series of sequential values (logging or time series data) then it would only have to search once?

I don't really know that much about skiplists, do they need to be balanced?
Looking at it now, but just guessing at ideas...

**Comment by vweevers** [comment]
Inserting sorted data in reverse is indeed faster, though not by much:

![batch-put 1561879036341](https://user-images.githubusercontent.com/3055345/60393599-4f17f000-9b18-11e9-92ac-b52df7395bab.png)
