### ISSUE TITLE
Leveldown not installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by Wist9063** [Level/leveldown#581]
I'm having issues when running `npm i`, it always snags on this package. 
It seems like there is no pre-build, so that might be the problem but i'm not sure.
I've cleared my cache, updated node & npm. I even created a new user. I still can't get it to work.

Version:
Node.js: `11.6.0`
npm: `6.5.0-next.0`

Log: https://gist.github.com/Wist9063/d1cb659b34f9bcc9bbc52afa0cefd3ff

**Comment by ralphtheninja** [comment]
Yeah, this is an issue with node 11 and `leveldown`. What are you installing that's including `leveldown`?

**Comment by ralphtheninja** [comment]
@vweevers Maybe we should release a `v4.0.2` patch supporting node 11? Wdyt?

**Comment by ralphtheninja** [comment]
Sorry, just checked and it seems leveldown v4 does work with node 11.

@Wist9063 Any chance you could upgrade leveldown?

**Comment by ralphtheninja** [comment]
Browsing the logs it seems you're trying to install `leveldown@1.7.0` which is too old for node 11.

**Comment by ralphtheninja** [comment]
Went through some versions. It seems `v2.1.1` works fine with node 11. No prebuilts, but it compiles.

**Comment by Wist9063** [comment]
@ralphtheninja To answer your first question, is was a npm package called level that I don't use, so I have uninstalled that. 
Second question: Yeah, installing 2.1.1 worked. Thanks
