### ISSUE TITLE
compilation hangs for ARMV6

### ISSUE THREAD

**Issue by max-zu** [Level/leveldown#592]
I have to deploy my project on a device with a processor arm. If I use arm32v7/node in my docker file, then everything works fine. If I use arm32v6/node process hangs on next step
```
> leveldown@4.0.1 install /app/node_modules/leveldown
> prebuild-install || node-gyp rebuild

```

**Comment by vweevers** [comment]
Sorry for the late response. It should work on 5x. We also have a prebuilt binary for armv6 since 5.5.0.

If upgrading doesn't help, feel free to reopen.
