### ISSUE TITLE
Make methods of derived Workers final instead of virtual

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#598]
E.g. instead of:

https://github.com/Level/leveldown/blob/3ff48f1d918129d9178240bdcdaad57bce2cd3a9/binding.cc#L848-L850

Write:

```js
 void DoExecute () final { 
   SetStatus(database_->Put(options_, key_, value_)); 
 }
```

**Comment by ralphtheninja** [comment]
Iirc they are still virtual so this is why I kept the `virtual` keyword. But fine if you want to remove it.

**Comment by vweevers** [comment]
After reading a bit, I see why you'd want to keep `virtual`. It makes no difference to the compiler, but it's helpful information to humans. Without it you'd have to look at the base class to find a method is virtual.

So instead I want to:

1. Make structs `final` (rather than their methods); I now realize that's what I wanted to communicate
2. Add the `override` keyword to methods (keeping `virtual` because some compilers bark otherwise).
