### ISSUE TITLE
Remove redundant electron prebuilds?

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#602]
I noticed that `node-napi.node` and `electron-napi.node` are equal, at least for Linux. So we can save on npm package size by only including `node-napi.node` (doesn't matter to `node-gyp-build`, it will treat that as a "runtime agnostic" prebuild).

Under what conditions do they _not_ match? 🤔

**Comment by ralphtheninja** [comment]
Hmm, that's a good question. cc @mafintosh

**Comment by vweevers** [comment]
FYI

```
npm notice package: leveldown@5.0.0
npm notice === Tarball Contents ===
...
npm notice 389.3kB prebuilds/android-arm/node-napi.node
npm notice 394.4kB prebuilds/android-arm64/node-napi.node
npm notice 295.3kB prebuilds/darwin-x64/electron-napi.node
npm notice 295.3kB prebuilds/darwin-x64/node-napi.node
npm notice 388.5kB prebuilds/linux-arm/node-napi.node
npm notice 406.8kB prebuilds/linux-arm64/node-napi.node
npm notice 407.1kB prebuilds/linux-x64/electron-napi.node
npm notice 407.1kB prebuilds/linux-x64/node-napi.node
npm notice 489.5kB prebuilds/win32-x64/electron-napi.node
npm notice 501.2kB prebuilds/win32-x64/node-napi.node
npm notice 249B    scripts/cross-compile
npm notice === Tarball Details ===
npm notice name:          leveldown
npm notice version:       5.0.0
npm notice package size:  2.0 MB
npm notice unpacked size: 5.2 MB
npm notice shasum:        44bb893346c2791b3b50276171a5421ecd83f2a9
npm notice integrity:     sha512-MZhLrJEanXmaM[...]3eF8Pw1QYBSDg==
npm notice total files:   195
```

**Comment by vweevers** [comment]
See https://github.com/nodejs/node-addon-api/issues/269 - it seems only Windows needs a separate Electron prebuild.

**Comment by vweevers** [comment]
Preliminary support matrix:

| OS                      | Electron  | `electron-napi.node` | `node-napi.node`
|:-----------------------|:------------|:----------------------------|:----------------------
| Windows 10 x64 | 3.1.8       | ✔️                            | ❌  (nodejs/node-addon-api/issues/269)
| Windows 10 x64 | 4.1.2       | ❌ (UNC bug?)        | ❌ (UNC bug?)
| Linux x64            | 3.1.8       | TBD                          | TBD
| Linux x64            | 4.1.2       | TBD                          | TBD
| MacOS x64         | 3.1.8       | TBD                          | TBD
| MacOS x64         | 4.1.2       | TBD                          | TBD

**Comment by vweevers** [comment]
Given these results, I think our best bet is to ditch `electron-napi.node` for all platforms, and to recommend Windows users to either use `--build-from-source` or upgrade to Electron 4.
