### ISSUE TITLE
build failed with Node v12.0.0

### ISSUE THREAD

**Issue by KsRyY** [Level/leveldown#628]
## Enviroment
```
node version: 12.0.0
platform: Manjaro Linux x64 (linux419)
GCC Version: 8.3.0
```

Looks like something in the `/leveldown/src/batch.o` went wrong or is incompatitible with Node v12.0.0 because leveldown builds fine on 10.15.1

**Comment by vweevers** [comment]
Which version of `leveldown` are you installing and could you share a log (preferably as a [gist](https://gist.github.com/))?

**Comment by KsRyY** [comment]
the log is at here [gist](https://gist.github.com/KsRyY/29bbb9dab9cba52a60f9e5914db6f1ec)

**Comment by KsRyY** [comment]
But there's a lot of Chinese

**Comment by KsRyY** [comment]
The leveldown version is 4.0.2

**Comment by vweevers** [comment]
For node 12, you'll need `leveldown@5`.

**Comment by KsRyY** [comment]
OK thanks

**Comment by ralphtheninja** [comment]
> For node 12, you'll need leveldown@5.

@vweevers Speaking of which, we should probably add this to `.travis.yml` and `appveyor.yml`.

**Comment by ralphtheninja** [comment]
@vweevers Or is that taken care of by current? Ignore me.

**Comment by vweevers** [comment]
@ralphtheninja Yes, it is. In fact we do the prebuilds in node 12 now :)

**Comment by vweevers** [comment]
Except (good thing you asked, made me double check): AppVeyor is behind, looks like current means 11 there
