### ISSUE TITLE
Delete leveldb::Options in OpenWorker?

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#632]
4.x:

https://github.com/Level/leveldown/blob/0cb52da4ed397f5931a2fc0f7ccf59cdfe4c01a8/src/database_async.cc#L50-L52

5.x:

https://github.com/Level/leveldown/blob/6ee815a9d6a1570f0c3f01101427f3febceb2799/binding.cc#L788

@ralphtheninja?

**Comment by ralphtheninja** [comment]
It's not a pointer anymore https://github.com/Level/leveldown/blob/master/binding.cc#L794

**Comment by vweevers** [comment]
Thanks. Great, one difference less between `rocksdb` and `leveldown` :)
