### ISSUE TITLE
Replace or take over maintenance of du, delayed and readfiletree

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#633]

**Comment by rvagg** [comment]
fixed by #649, #648, #647, they've come out of retirement

**Comment by vweevers** [comment]
Great. Should you need help maintaining these now or in the future, I'm willing.

As for `delayed`, which we only use [here](https://github.com/Level/leveldown/blob/master/test/compression-test.js), we can replace that with an inline `setTimeout()` call, if we even still need a timeout.

**Comment by rvagg** [comment]
Ah, right, delayed@2.0.0 published, incoming via greenkeeper. Can be done without pretty easily but I always had a bit of a sweet spot for that package, especially its debouncer.

**Comment by vweevers** [comment]
Alright, we'll keep it, no need to refactor code that has worked for years.

I'm opening a PR though to fix a small bug I just found in that compression test.
