### ISSUE TITLE
Proposal: Bind and Expose Iterator Prev()

### ISSUE THREAD

**Issue by MeirionHughes** [Level/leveldown#646]
As suggested in https://github.com/Level/abstract-leveldown/issues/339 leveldb (appears) to allow iterators to go to the previous key. I propose this functionality is added to leveldown and abstract-leveldown as it means its potentially O(1) to find the previous entry on a seek key 'miss'.  

* [x] [check leveldb allows prev() to be called on an iterator](https://github.com/Level/leveldown/blob/master/deps/leveldb/leveldb-1.20/include/leveldb/iterator.h#L53)

* [ ] Review whether such function would have to be guarded behind a `canPrev()` method in abstract-leveldown. i.e. some db's can't do prev. 

* [ ] [Decide how to deal with the cache](https://github.com/Level/leveldown/blob/master/iterator.js#L25-L40). Simple solution would appear to be just wipe the cache if you if you `prev()`. But then you'd lose out if you continually do `prev()`. I think I can live with this; as if you really need to be going in the `previous` direction more than a few times, you should make a reverse iterator. 

* [ ] evaluate concurrency issues. [i.e. `_nexting' and error checking. ](https://github.com/Level/abstract-leveldown/blob/master/abstract-iterator.js)

**Comment by MeirionHughes** [comment]
The specific use-case for me for this proposal is that I'm trying to make an implicit secondary index kB→ kA for many prefixed-sets kA → V where it is likely to "miss" and needs to return the nearest, i.e. [kA-1, kA+1]. It is them expected the calling iterator would choose to do interpolation of the values.

This can technically be accomplished by having two iterators (one forward and one in reverse), but doing this per kB→ kA → [kA-1, kA+1] seems far more expensive than just a call to `prev()`.

**Comment by vweevers** [comment]
Unassigning myself because we typically only assign ourselves to say "I'm willing to work on this" and for me, that's not the case atm. There's other tasks I consider higher priority.

**Comment by MeirionHughes** [comment]
ah ok - sorry - should have pinged instead - was more a "do you foresee this being a major headache?" as you know the ecosystem.

**Comment by vweevers** [comment]
FWIW my only worry atm is that this will increase the internal complexity of `leveldown`, so I'd prefer to see some code there before we consider other `abstract-leveldown` implementations and the wider ecosystem.

**Comment by MeirionHughes** [comment]
yeah, Read and IteratorNext are a bit intimidating - I really don't want to change anything at all in those two methods.
