### ISSUE TITLE
UnhandledPromiseRejectionWarning: OpenError: IO error:LockFile 

### ISSUE THREAD

**Issue by songdangwei** [Level/leveldown#662]
(node:13460) UnhandledPromiseRejectionWarning: OpenError: IO error: LockFile E:\ethsample/data/LOCK:   һ          ʹ ô  ļ        ޷    ʡ 

    at \node_modules\levelup\lib\levelup.js:96:23
    at \node_modules\abstract-leveldown\abstract-leveldown.js:30:14
    at \node_modules\deferred-leveldown\deferred-leveldown.js:20:21
    at \node_modules\abstract-leveldown\abstract-leveldown.js:30:14
    at \node_modules\abstract-leveldown\abstract-leveldown.js:30:14
(node:13460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not h
andled with .catch(). (rejection id: 1)
(node:13460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Running this issue now, can't seem to find a lot of documentation about this.
I used nodejs level:5.0.1.   the LOCK file is empty.
let db = await level(defpath + "/data", {valueEncoding: "json"})

**Comment by vweevers** [comment]
https://github.com/Level/levelup/issues/667#issuecomment-520966922
