### ISSUE TITLE
Leveldown node 12 support

### ISSUE THREAD

**Issue by fainashalts** [Level/leveldown#665]
Is node 12 support planned for leveldown? As of now it does not appear I can use this package with node 12 due to its dependency on the `nan` package, and possibly others I am not aware of. Thanks for any info you can provide!

**Comment by peakji** [comment]
Which version of `leveldown` are you using? For node 12, you will need to use `leveldown>=5`.

**Comment by fainashalts** [comment]
Yes, it was a version issue. Thank you!
