### ISSUE TITLE
error when installing on osx 10.9

### ISSUE THREAD

**Issue by nickleefly** [Level/leveldown#69]
when I try to install `leveldown` on 10.9, there is error

I also tried compile from leveldb code, also an error there,
does this cause by osx update?
## leveldown log

```
$ npm install leveldown
npm http GET https://registry.npmjs.org/leveldown
npm http 304 https://registry.npmjs.org/leveldown
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> leveldown@0.9.1 install /Users/nick/dev-src/js/node_modules/leveldown
> node-gyp rebuild

  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o
In file included from ../deps/leveldb/leveldb-1.14.0/db/builder.cc:5:
In file included from ../deps/leveldb/leveldb-1.14.0/db/builder.h:8:
../deps/leveldb/leveldb-1.14.0/include/leveldb/status.h:16:10: fatal error:
      'string' file not found
#include <string>
         ^
1 error generated.
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nick/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/Users/nick/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nick/dev-src/js/node_modules/leveldown
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

```
## leveldb log

```
$ make
c++  -dynamiclib -install_name /Users/nick/dev-src/cpp/leveldb/libleveldb.dylib.1 -I. -I./include -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -fPIC db/builder.cc db/c.cc db/db_impl.cc db/db_iter.cc db/dbformat.cc db/filename.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/repair.cc db/table_cache.cc db/version_edit.cc db/version_set.cc db/write_batch.cc table/block.cc table/block_builder.cc table/filter_block.cc table/format.cc table/iterator.cc table/merger.cc table/table.cc table/table_builder.cc table/two_level_iterator.cc util/arena.cc util/bloom.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/env.cc util/env_posix.cc util/filter_policy.cc util/hash.cc util/histogram.cc util/logging.cc util/options.cc util/status.cc  port/port_posix.cc -o libleveldb.dylib.1.14
In file included from db/builder.cc:5:
In file included from ./db/builder.h:8:
./include/leveldb/status.h:16:10: fatal error: 'string' file not found
#include <string>
         ^
1 error generated.
make: *** [libleveldb.dylib.1.14] Error 1

```

**Comment by nutan110125** [comment]
Collecting plyvel
  Using cached https://files.pythonhosted.org/packages/b3/1d/05e3555abddb49b9a2f3aa1268bec4933bf377ffcad3c1b2630fcfa597eb/plyvel-1.0.5.tar.gz
Installing collected packages: plyvel
  Running setup.py install for plyvel ... error
    Complete output from command /Users/nutan_gupta/Desktop/myproject/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h3/xyrvg8_j6sn5s4tgq4hhgwbr0000gq/T/pip-install-dcyis5af/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/h3/xyrvg8_j6sn5s4tgq4hhgwbr0000gq/T/pip-record-w2xunpm5/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nutan_gupta/Desktop/myproject/myenv/include/site/python3.7/plyvel:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.7
    creating build/lib.macosx-10.13-x86_64-3.7/plyvel
    copying plyvel/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/plyvel
    copying plyvel/_version.py -> build/lib.macosx-10.13-x86_64-3.7/plyvel
    running build_ext
    building 'plyvel._plyvel' extension
    creating build/temp.macosx-10.13-x86_64-3.7
    creating build/temp.macosx-10.13-x86_64-3.7/plyvel
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/nutan_gupta/Desktop/myproject/myenv/include -I/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c plyvel/_plyvel.cpp -o build/temp.macosx-10.13-x86_64-3.7/plyvel/_plyvel.o -Wall -g -mmacosx-version-min=10.7 -stdlib=libc++
    plyvel/_plyvel.cpp:589:10: fatal error: 'leveldb/db.h' file not found
    #include "leveldb/db.h"
             ^~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/nutan_gupta/Desktop/myproject/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h3/xyrvg8_j6sn5s4tgq4hhgwbr0000gq/T/pip-install-dcyis5af/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/h3/xyrvg8_j6sn5s4tgq4hhgwbr0000gq/T/pip-record-w2xunpm5/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nutan_gupta/Desktop/myproject/myenv/include/site/python3.7/plyvel" failed with error code 1 in /private

**Comment by nutan110125** [comment]
i also  get this error

**Comment by vweevers** [comment]
@nutan110125 It looks like you're installing Plyvel? Open an issue in [wbolster/plyvel](https://github.com/wbolster/plyvel). Good luck!
