### ISSUE TITLE
unable to install leveldown

### ISSUE THREAD

**Issue by bpareek9694** [Level/leveldown#701]
Hello All,

We're unable to install leveldown

Error are below please check :-

`# npm install leveldow`

`leveldown.target.mk:105: recipe for target 'Release/obj.target/leveldown/binding.o' failed
make: *** [Release/obj.target/leveldown/binding.o] Error 1
make: Leaving directory '/root/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-173-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/leveldown
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm ERR! Linux 4.4.0-173-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "leveldown"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! leveldown@5.4.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@5.4.1 install script 'node-gyp-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2020-02-10T10_11_47_014Z-debug.log`

Guys Please Advice me how can i install level down in my server.

Thanks

**Comment by vweevers** [comment]
The minimum node version supported by `leveldown@5` is 8.6.0.

See https://github.com/Level/leveldown#supported-platforms

**Comment by ralphtheninja** [comment]
Also, it's not recommended to install npm modules as root.

**Comment by garbados** [comment]
Hi, I'm also not able to install leveldown. Here is the log output: https://gist.github.com/garbados/5ff56d301bf224fc21359bb4a41f115b

It seems like I'm missing some system dependency but of course I don't know which.

**Comment by vweevers** [comment]
@garbados For node >= 12, the minimum leveldown version is 5.0.0.

**Comment by garbados** [comment]
Welp, that would do it. No idea why we're using such an old version of leveldown.

**Comment by garbados** [comment]
Thanks for the rapid response :)
