### ISSUE TITLE
Pi Zero prebuilds

### ISSUE THREAD

**Issue by christianbundy** [Level/leveldown#703]
Hi! Would it be possible to add prebuilds for the Pi Zero (armv6)? It looks like it's as simple as adding a line to `package.json`, but I wanted to reach out and ask first before opening a PR. Thanks!

**Comment by ralphtheninja** [comment]
I haven't been around for a while so I think @vweevers is the go to guy. Iirc it would be a matter of adding a docker image for it in https://github.com/prebuild/docker-images (which is invoked by `prebuildify-cross`). That docker image also needs to be built and pushed to docker hub.

**Comment by christianbundy** [comment]
Thanks for the info! Looks like dockcross already supports it -- I'll try a docker build locally and push up a branch if I can get it working. :rocket:

**Comment by vweevers** [comment]
The steps are roughly:

- Add an image for armv6 to https://github.com/prebuild/docker-images, similar to https://github.com/prebuild/docker-images/blob/master/linux-armv7/Dockerfile, but `FROM dockcross/linux-armv6`. Send a PR and I'll add it to docker hub.
- Add a script to `package.json` here
- We can then make a prebuild for you to test.

Anyone opposed to increasing our package size? (I don't care)

**Comment by ralphtheninja** [comment]
I don't think it would mean that much increase in package size. I.e. I don't care :)

**Comment by vweevers** [comment]
Image is available, but `npx prebuildify-cross -i linux-armv6 -i linux-arm64 -t 8.14.0 --napi --strip` throws an error at the end, not being able to find `strip`:

```
Error: spawn /usr/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-strip ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by christianbundy** [comment]
wat

**Comment by vweevers** [comment]
We have to fix [`PREBUILD_STRIP_BIN`](https://github.com/prebuild/docker-images/blob/41f8f20343aecf8e8d6800643d4c797c4b71f0c3/linux-armv6/Dockerfile#L19) but what is the right path?

**Comment by christianbundy** [comment]
It looks like these two are byte-for-byte exactly the same file:

- `/usr/arm-linux-gnueabihf/bin/strip`
- `/usr/bin/arm-linux-gnueabihf-strip`

They're both:

```
GNU strip (crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11) 2.24.0.20131220
```

There's also `/usr/bin/x86_64-linux-gnu-strip`, which is:

```
GNU strip (GNU Binutils for Debian) 2.28
```

**Comment by vweevers** [comment]
Let's go with `/usr/arm-linux-gnueabihf/bin/strip`, I guess 🤷‍♂

**Comment by vweevers** [comment]
Will publish 5.5.0 in a few hours, requires 2FA but I don't have access to OTP generator atm.

**Comment by vweevers** [comment]
Published.

**Comment by christianbundy** [comment]
Thank you!
