### ISSUE TITLE
Fix double builds on AppVeyor

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#707]
Not sure why this keeps happening or how to prevent it. It's annoying when making a release and waiting for prebuilds to finish.

1. https://ci.appveyor.com/project/Level/leveldown/
2. https://ci.appveyor.com/project/Level/leveldown-d9l55/ (?)

**Comment by vweevers** [comment]
Is Travis for Windows stable yet? If so, let's switch.

**Comment by ralphtheninja** [comment]
Try deleting the second one? https://ci.appveyor.com/project/Level/leveldown-d9l55/settings/delete

**Comment by vweevers** [comment]
Deleted it. I'm still wondering how it got created though. Oh well.
