### ISSUE TITLE
If leveldown have s390x support?

### ISSUE THREAD

**Issue by elfahxh** [Level/leveldown#722]
If currently leveldown support s390x Platform?

**Comment by vweevers** [comment]
No, because it lacks `AtomicPointer` support required by LevelDB, see https://github.com/Level/leveldown/issues/306.

**Comment by kycfeel** [comment]
Hey. Any update on this? I'm also looking for a way to build it for the `s390x` machine.

Getting `error: #error Please implement AtomicPointer for this platform.` while on build.

**Comment by kycfeel** [comment]
Made a patch and PR for this. - https://github.com/Level/leveldown/pull/754
