### ISSUE TITLE
Pls make docs for get and put

### ISSUE THREAD

**Issue by rupamking1** [Level/leveldown#769]
I am not able to use put or get please write or make a docs for leveldown

````js
db.open((a1) => {
    p(a1)
    db.put('key', 'value', { sync: true }, (a2) => {
      p(a2)
      db.get('key', { sync: true }, (a3) => {
        p(a3)
      })
    })
})
````

**Comment by vweevers** [comment]
We can't help you unless you provide more information.

> I am not able to use put or get

What doesn't work, specifically?

> please write or make a docs for leveldown

What are you missing in the current [readme](https://github.com/Level/leveldown)?

> db.open(..)

I've edited your code example to make it more readable, but I can't guess what `p()` is.

**Comment by hanumanjiblog** [comment]
I watched your readme file and i tried this, but same problem.
`
db.open((a1) => {
    console.log(a1)  // output- undefined
    db.put('key', 'value', { sync: true }, (a2) => {
      console.log(a2)  // output- null
      db.get('key', { sync: true }, (a3) => {
        console.log(a3)  // output- null
      })
    })
})
`

**Comment by rupamking1** [comment]
I watched your readme file and i tried this, but same problem.
`db.open((a1) => { console.log(a1) // output- undefined db.put('key', 'value', { sync: true }, (a2) => { console.log(a2) // output- null db.get('key', { sync: true }, (a3) => { console.log(a3) // output- null }) }) })`

**Comment by vweevers** [comment]
The first argument passed to the callbacks is an error (if any). This is documented: https://github.com/Level/leveldown#dbgetkey-options-callback

You'll want:

```js
db.get('key', function (err, value) {
  if (err) throw err

  console.log(value)
})
```

**Comment by rupamking1** [comment]
Many many thank you for your help, you are really helpful good person 😇
