### ISSUE TITLE
Leveldown Stream

### ISSUE THREAD

**Issue by malaxmimdkm** [Level/leveldown#770]
db.createReadStream() or db.createKeyStream() or db.createValueStream()

Is Any similar function available on leveldown Package?

**Comment by vweevers** [comment]
Not directly, but you can use [iterator-stream](https://github.com/Level/iterator-stream#usage) to convert a leveldown iterator to a stream.

**Comment by malaxmimdkm** [comment]
Is kay value iterator possible with db.iterator() or iterator?

**Comment by vweevers** [comment]
Both `db.iterator()` and `iterator-stream` accept `keys` and `values` options, this is documented.

**Comment by malaxmimdkm** [comment]
Thanks for your answer, Please tell How to use Start and End or gt and lt in iterator?

**Comment by vweevers** [comment]
I would just be copying that from [documentation](https://github.com/Level/leveldown#dbiteratoroptions).

If you have more specific questions that are not covered by documentation, I'm happy to answer.

**Comment by malaxmimdkm** [comment]
why you close issue without any answer?

**Comment by vweevers** [comment]
Your question is vague and unspecific, so I can only assume it's a general question that's already by covered by docs. Please be mindful of the fact that I'm volunteering my time, and please read the documentation before asking questions. Thanks.
