### ISSUE TITLE
db.iterator()  gt & lt

### ISSUE THREAD

**Issue by malaxmimdkm** [Level/leveldown#771]
Please add gt & lt features in db.iterator(),
is this feature already available in db.iterator()?

**Comment by vweevers** [comment]
See https://github.com/Level/leveldown/issues/770#issuecomment-880015080.

Please do not open any more issues about the same question that is already answered. Thanks!

**Comment by malaxmimdkm** [comment]
I apologize to you for Opening this issue, Please don't mind 🥺
