### ISSUE TITLE
Inbuilt Encryption

### ISSUE THREAD

**Issue by omymy1** [Level/leveldown#772]
Please add In built-in encryption, I can use any string encryption package but that decrease leveldown performance. Please add this feature or is already available please leave a Comment.

**Comment by vweevers** [comment]
Unfortunately that's out of scope. We cannot add a specific choice of encryption algorithm to a relatively generic key-value store. In fact, any encryption is out of scope.

If you see opportunities for new integration points that could help implement (faster) encryption in userland, that can be discussed. I would however ask for a concrete and more detailed proposal. Until then, I'm closing this issue. Thanks!
