### ISSUE TITLE
Currency and Parallelism 

### ISSUE THREAD

**Issue by omymy1** [Level/leveldown#773]
Is Concurrency and Parallelism feature already available in Leveldown?

**Comment by vweevers** [comment]
Can you please elaborate?

**Comment by omymy1** [comment]
that means multiple put or get operation in same time that is concurrency, and multiple operation happened parallelly that is Parallelism.

**Comment by vweevers** [comment]
Yes, operations run concurrently. They're asynchronously executed in a thread pool. Which may effectively be parallel, given enough free threads. In addition, iterators and streams operate on a snapshot of the database, meaning they're unaffected by concurrent writes.
