### ISSUE TITLE
Snappy compression

### ISSUE THREAD

**Issue by kingrupam** [Level/leveldown#774]
1. If disable Snappy compression then will it make my database little bit faster?
because compress and compress make cost resources.

2. Will key and value both compressed or only value will compressed?

**Comment by vweevers** [comment]
> If disable Snappy compression then will it make my database little bit faster?

Yes, but just a little bit. Snappy is fast.

> Will key and value both compressed or only value will compressed?

LevelDB compresses blocks of data, at a higher level.

**Comment by kingrupam** [comment]
how much snappy compressed data, if total database size is hundred MB. that is my last question.

**Comment by vweevers** [comment]
Depends on the data, so it's best to test it yourself. For ballpark numbers see https://en.wikipedia.org/wiki/Snappy_(compression) and https://github.com/google/snappy.

**Comment by kingrupam** [comment]
Thanks For Your answer
