### ISSUE TITLE
Support more than 32bit ApproximateSize bindings

### ISSUE THREAD

**Issue by larskuhtz** [Level/leveldown#776]
Currently the binding for approximateSize stores the result as `uint32` (https://github.com/Level/leveldown/blob/e1c34634c11f4d3dd174c3f2e658fdae2cde1c15/binding.cc#L1036). This supports only databases of up to 4GB and returns wrong results for larger DBs.

It would be nice if approximateSize could either

1. support all of `Number.isSafeInteger()`,
2. support larger numbers by representing them as nearest float (it's "approximate" after all),
3. return `BitInt`, or
4. at least return an error if an invalid result is returned.

Not sure, which of the options would be best.

**Comment by vweevers** [comment]
I prefer option 1. Brings us into petabyte or exabyte territory, without a breaking change.

**Comment by larskuhtz** [comment]
With option (1.), how should the case be handled when then database returns a value that is to big? Throw an error, return `-1`, or just return whatever `napi_create_int64` gives (essentially using option 2. as fallback)?

Currently, it just overflows, which isn't ideal.

**Comment by vweevers** [comment]
> With option (1.), how should the case be handled when then database returns a value that is to big? Throw an error, return `-1`, or just return whatever napi_create_int64 gives (essentially using option 2. as fallback)?

Return whatever `napi_create_int64` gives. Because as you pointed out, the db size already is approximate. And if you have a database that big, I'm not sure LevelDB is the right fit anyway.

**Comment by larskuhtz** [comment]
cf. #777
