### ISSUE TITLE
support custom  comparison function

### ISSUE THREAD

**Issue by GopherJ** [Level/leveldown#780]
I use leveldb to make a queue, but leveldb's default key ordering is a bit strange. Like the following:

![image](https://user-images.githubusercontent.com/33961674/128712524-40897dcf-ec86-4c21-849e-c183cc7952de.png)

seek method doesn't go to `8` but go directly to  `10`

**Comment by vweevers** [comment]
That's expected, because LevelDB (and all level modules) use [lexicographic order](https://en.wikipedia.org/wiki/Lexicographic_order).
