### ISSUE TITLE
Two Oparation

### ISSUE THREAD

**Issue by hanumanjiblog** [Level/leveldown#789]
If two put operation occurs at a same time on same kay, so what happened?
Is atomicity available in Leveldown or Level?

**Comment by vweevers** [comment]
Atomicity is guaranteed for a single `put()` and for a `batch()`. However, there's no Isolation. So of two concurrent `put()` calls, either can win.

**Comment by hanumanjiblog** [comment]
Please implement isolation 🙏
If two Put operation happened then compare both and Forward the Put that comes first.

**Comment by vweevers** [comment]
Not gonna happen, that's out of scope. We might at some point expose snapshots, which would allow transactions to be implemented in userland.
