### ISSUE TITLE
Compiling legacy on arm

### ISSUE THREAD

**Issue by mcpalmer1980** [Level/leveldown#791]
Pymunk has unfortunately broken compatibility with projects made for version 4 and 5. In order to keep those old projects working on modern arm devices I recommend updating the setup.py for 4.0 and 5.7 to compile for arm64 devices. I am getting an error compiling them on the chroot provided by the 351elec community for retro portable consoles. After a little experimenting I have failed to make it work.

```
root@rk3326-dev:/pymunk-5.7.0# python3 setup.py build_ext --inplace
running build_ext
cc -std=gnu99 -ffast-math -DCHIPMUNK_FFI -g -DCP_USE_CGPOINTS=0 -DNDEBUG -fPIC -O3 -m64 -Ichipmunk_src/include -c chipmunk_src/src/cpSpaceComponent.c -o chipmunk_src/src/cpSpaceComponent.o
cc: error: unrecognized command line option ‘-m64’
error: command 'cc' failed with exit status 1
root@rk3326-dev:/pymunk-5.7.0# 
```

**Comment by vweevers** [comment]
How is this related to `leveldown`?
