### ISSUE TITLE
Question: iterate old entries?

### ISSUE THREAD

**Issue by kumavis** [Level/leveldown#792]
Is it possible to iterate over old values that are still in the database? (entries for a single key where the sequence number is behind the latest entry's sequence number)

I found this python utility was able to pull out old entries https://github.com/obsidianforensics/hindsight/tree/6b754e216b9cbc522ea4c6e4614012ab5fd75872/pyhindsight/lib/ccl_chrome_indexeddb

**Comment by vweevers** [comment]
> Is it possible to iterate over old values that are still in the database?

Not with the API that's exposed here.

> I found this python utility was able to pull out old entries

Is it reading entries that were deleted through the IndexedDB API though, or really from LevelDB?

**Comment by kumavis** [comment]
> Is it reading entries that were deleted through the IndexedDB API though, or really from LevelDB?

it is reading leveldb entries that were overwritten. i believe its doing this by manually reading and parsing the leveldb files

**Comment by vweevers** [comment]
Closing because I believe it's out of scope for `leveldown`.
