### ISSUE TITLE
Question: db.put() callback order

### ISSUE THREAD

**Issue by redboltz** [Level/leveldown#797]
When I call db.put as follows, cb1 is called before cb2 is called?

```js
db.put(key1, val1, cb1)
db.put(key2, val2, cb2)
```

Or calling order is unspecified (e.g. depends on backend levelDB mechanism) ?

**Comment by vweevers** [comment]
The callbacks will be called in no particular order, because the two `put()` calls are asynchronous. Two so-called "async workers" are started that work independently and in parallel.

**Comment by redboltz** [comment]
Thank for your prompt answer! I understand.
