### ISSUE TITLE
Operation ordering guarantee

### ISSUE THREAD

**Issue by ronag** [Level/leveldown#799]
Haven't been able to find a definitive answer on this. Does level down guarantee that writes are always visible for reads, in order.

e.g. is the following code guaranteed to always work?

```js
db.put(key, val, (err) => { 
  /* assume no err */ 
})
db.get(key, (err, val2) => {
  /* assume no err */
  assert.strictEqual(val, val2)
})
```

Or do I need to do something like:

```js
const pending = new Map()
pending.set(key, val)
db.put(key, val, (err) => { 
  /* assume no err */ 
  pending.delete(key)
})
db.get(key, (err, val2) => {
  /* assume no err */
  val2 = pending.get(key) ?? val2
  assert.strictEqual(val, val2)
})
```

**Comment by vweevers** [comment]
> e.g. is the following code guaranteed to always work?

No, because each operation (put, get, del, etc) starts an async worker that is independent of the others. We make no guarantee about the order of these. Node.js _might_ but if it does that should be considered a side-effect rather than by design.

**Comment by ronag** [comment]
Thanks for the answer!
