### ISSUE TITLE
store and manage state

### ISSUE THREAD

**Issue by rvagg** [Level/leveldown#8]
`db.open()` is the only valid operation when a database is not open. `db.open()` must finish before other operations are permitted. `db.close()` must prevent any other operations executing until it's complete at which point you can only run `db.open()` again.

ugh.

**Comment by vweevers** [comment]
It seems to me we no longer need this, because `abstract-leveldown` tracks state.

Would there still be a benefit to (also) doing it in c++ code?

**Comment by vweevers** [comment]
Done in [`classic-level`](https://github.com/Level/classic-level).
