### ISSUE TITLE
benchmarks broken

### ISSUE THREAD

**Issue by juliangruber** [Level/leveldown#81]
* [x] They miss the `optimist` dependency
* [x] `db-bench.js` misses `./random-data`
* [x] `write-random.js` misses `../../lmdb/`
* [x] `write-sorted.js` works

**Comment by ralphtheninja** [comment]
@juliangruber Why are we benchmarking `lmdb` at all in `leveldown` repository?

**Comment by ralphtheninja** [comment]
`write-sorted.js` uses `leveldown` and then perhaps `write-random.js` should also use `leveldown`.

**Comment by juliangruber** [comment]
> write-sorted.js uses leveldown and then perhaps write-random.js should also use leveldown.

agreed
