### ISSUE TITLE
node-gyp rebuild error (as part of PouchDB)

### ISSUE THREAD

**Issue by DrYSG** [Level/leveldown#86]
I got this error on a Windows7 machine with the latest version of node-gyp for 64 bit windows machines.

G:\wwwroot\NodeWork\node_modules\pouchdb\node_modules\level\node_modules\leveldown>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
npm http GET http://registry.npmjs.org/pouchdb
npm http 200 http://registry.npmjs.org/pouchdb
npm http GET http://registry.npmjs.org/pouchdb/-/pouchdb-1.0.0.tgz
npm http 200 http://registry.npmjs.org/pouchdb/-/pouchdb-1.0.0.tgz
npm http GET http://registry.npmjs.org/pouchdb-mapreduce/0.2.0
npm http GET http://registry.npmjs.org/level
npm http 200 http://registry.npmjs.org/pouchdb-mapreduce/0.2.0
npm http 200 http://registry.npmjs.org/level
npm http GET http://registry.npmjs.org/pouchdb-mapreduce/-/pouchdb-mapreduce-0.2.0.tgz
npm http GET http://registry.npmjs.org/level/-/level-0.18.0.tgz
npm http 200 http://registry.npmjs.org/pouchdb-mapreduce/-/pouchdb-mapreduce-0.2.0.tgz
npm http 200 http://registry.npmjs.org/level/-/level-0.18.0.tgz
npm http GET http://registry.npmjs.org/request
npm http 200 http://registry.npmjs.org/request
npm http GET http://registry.npmjs.org/request/-/request-2.28.0.tgz
npm http 200 http://registry.npmjs.org/request/-/request-2.28.0.tgz
npm http GET http://registry.npmjs.org/pouchdb-collate/0.1.0
npm http GET http://registry.npmjs.org/level-packager
npm http GET http://registry.npmjs.org/tunnel-agent
npm http GET http://registry.npmjs.org/aws-sign2
npm http GET http://registry.npmjs.org/oauth-sign
npm http GET http://registry.npmjs.org/json-stringify-safe
npm http GET http://registry.npmjs.org/http-signature
npm http GET http://registry.npmjs.org/node-uuid
npm http 200 http://registry.npmjs.org/pouchdb-collate/0.1.0
npm http GET http://registry.npmjs.org/qs
npm http 200 http://registry.npmjs.org/aws-sign2
npm http 200 http://registry.npmjs.org/oauth-sign
npm http 200 http://registry.npmjs.org/tunnel-agent
npm http 200 http://registry.npmjs.org/json-stringify-safe
npm http 200 http://registry.npmjs.org/level-packager
npm http GET http://registry.npmjs.org/leveldown
npm http GET http://registry.npmjs.org/form-data
npm http GET http://registry.npmjs.org/tough-cookie
npm http GET http://registry.npmjs.org/mime
npm http 200 http://registry.npmjs.org/http-signature
npm http 200 http://registry.npmjs.org/node-uuid
npm http 200 http://registry.npmjs.org/form-data
npm http 200 http://registry.npmjs.org/qs
npm http 200 http://registry.npmjs.org/mime
npm http 200 http://registry.npmjs.org/tough-cookie
npm http GET http://registry.npmjs.org/forever-agent
npm http GET http://registry.npmjs.org/pouchdb-collate/-/pouchdb-collate-0.1.0.tgz
npm http 200 http://registry.npmjs.org/forever-agent
npm http GET http://registry.npmjs.org/level-packager/-/level-packager-0.18.0.tgz
npm http 200 http://registry.npmjs.org/pouchdb-collate/-/pouchdb-collate-0.1.0.tgz
npm http 200 http://registry.npmjs.org/leveldown
npm http 200 http://registry.npmjs.org/level-packager/-/level-packager-0.18.0.tgz
npm http GET http://registry.npmjs.org/leveldown/-/leveldown-0.10.2.tgz
npm http GET http://registry.npmjs.org/hawk
npm http 200 http://registry.npmjs.org/leveldown/-/leveldown-0.10.2.tgz
npm http 200 http://registry.npmjs.org/hawk
npm http GET http://registry.npmjs.org/combined-stream
npm http 200 http://registry.npmjs.org/combined-stream
npm http GET http://registry.npmjs.org/punycode
npm http 200 http://registry.npmjs.org/punycode
npm http GET http://registry.npmjs.org/async
npm http 200 http://registry.npmjs.org/async
npm http GET http://registry.npmjs.org/ctype/0.5.2
npm http GET http://registry.npmjs.org/asn1/0.1.11
npm http GET http://registry.npmjs.org/assert-plus/0.1.2
npm http 200 http://registry.npmjs.org/ctype/0.5.2
npm http 200 http://registry.npmjs.org/asn1/0.1.11
npm http GET http://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz
npm http 200 http://registry.npmjs.org/assert-plus/0.1.2
npm http GET http://registry.npmjs.org/assert-plus/-/assert-plus-0.1.2.tgz
npm http 200 http://registry.npmjs.org/assert-plus/-/assert-plus-0.1.2.tgz
npm http 200 http://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz
npm http GET http://registry.npmjs.org/ctype/-/ctype-0.5.2.tgz
npm http 200 http://registry.npmjs.org/ctype/-/ctype-0.5.2.tgz
npm http GET http://registry.npmjs.org/sntp
npm http GET http://registry.npmjs.org/boom
npm http GET http://registry.npmjs.org/cryptiles
npm http GET http://registry.npmjs.org/hoek
npm http 200 http://registry.npmjs.org/cryptiles
npm http 200 http://registry.npmjs.org/boom
npm http 200 http://registry.npmjs.org/sntp
npm http 200 http://registry.npmjs.org/hoek
npm http GET http://registry.npmjs.org/delayed-stream/0.0.5
npm http 200 http://registry.npmjs.org/delayed-stream/0.0.5
npm http GET http://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tgz
npm http 200 http://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tgz
npm http GET http://registry.npmjs.org/bindings
npm http GET http://registry.npmjs.org/nan
npm http GET http://registry.npmjs.org/levelup
npm http 200 http://registry.npmjs.org/bindings
npm http 200 http://registry.npmjs.org/nan
npm http GET http://registry.npmjs.org/nan/-/nan-0.6.0.tgz
npm http 200 http://registry.npmjs.org/levelup
npm http GET http://registry.npmjs.org/levelup/-/levelup-0.18.2.tgz
npm http 200 http://registry.npmjs.org/nan/-/nan-0.6.0.tgz
npm http 200 http://registry.npmjs.org/levelup/-/levelup-0.18.2.tgz
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 527, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 503, in gyp_main
    options.circular_check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1798, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 400, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 337, in _DetectVisualStudioVersions
    path = _RegistryGetValue(keys[index], 'InstallDir')
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 175, in _RegistryGetValue
    text = _RegistryQuery(key, value)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 157, in _RegistryQuery
    text = _RegistryQueryBase('Sysnative', key, value)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 128, in _RegistryQueryBase
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 703, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python27\lib\subprocess.py", line 829, in _get_handles
    p2cread = _subprocess.GetStdHandle(_subprocess.STD_INPUT_HANDLE)
WindowsError: [Error 6] The handle is invalid
gypnpm http GET http://registry.npmjs.org/xtend
npm http GET http://registry.npmjs.org/concat-stream
npm http GET http://registry.npmjs.org/errno
npm http GET http://registry.npmjs.org/deferred-leveldown
npm http GET http://registry.npmjs.org/semver
npm http GET http://registry.npmjs.org/bops
npm http GET http://registry.npmjs.org/readable-stream
npm http GET http://registry.npmjs.org/prr
npm http 200 http://registry.npmjs.org/xtend
npm http 200 http://registry.npmjs.org/concat-stream
npm http 200 http://registry.npmjs.org/errno
npm http 200 http://registry.npmjs.org/deferred-leveldown
npm http GET http://registry.npmjs.org/deferred-leveldown/-/deferred-leveldown-0.1.0.tgz
npm http 200 http://registry.npmjs.org/prr
npm http 200 http://registry.npmjs.org/semver
npm http 200 http://registry.npmjs.org/deferred-leveldown/-/deferred-leveldown-0.1.0.tgz
npm http 200 http://registry.npmjs.org/bops
npm http GET http://registry.npmjs.org/bops/-/bops-0.1.1.tgz
npm http 200 http://registry.npmjs.org/readable-stream
npm http 200 http://registry.npmjs.org/bops/-/bops-0.1.1.tgz
npm http GET http://registry.npmjs.org/bops
npm http 200 http://registry.npmjs.org/bops
npm http GET http://registry.npmjs.org/abstract-leveldown
npm http 200 http://registry.npmjs.org/abstract-leveldown
npm http GET http://registry.npmjs.org/object-keys
npm http 200 http://registry.npmjs.org/object-keys
npm http GET http://registry.npmjs.org/base64-js/0.0.2
npm http 200 http://registry.npmjs.org/base64-js/0.0.2
npm http GET http://registry.npmjs.org/base64-js/-/base64-js-0.0.2.tgz
npm http 200 http://registry.npmjs.org/base64-js/-/base64-js-0.0.2.tgz
npm http GET http://registry.npmjs.org/to-utf8/0.0.1
npm http 200 http://registry.npmjs.org/to-utf8/0.0.1
npm http GET http://registry.npmjs.org/to-utf8/-/to-utf8-0.0.1.tgz
npm http 200 http://registry.npmjs.org/to-utf8/-/to-utf8-0.0.1.tgz
npm ERR! leveldown@0.10.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@0.10.2 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pouchdb" "--save"
npm ERR! cwd G:\wwwroot\NodeWork
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm

**Comment by ralphtheninja** [comment]
@DrYSG Please re-open if this is still an issue for you. Thanks!
