### ISSUE TITLE
Installation on os x 10.7.5 ( xcode 4.6.3 ) fails

### ISSUE THREAD

**Issue by MrRhino** [Level/leveldown#92]
When executing the following command:
npm install leveldown

I get these error messages:

make: **\* [Release/leveldb.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/leveldown
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! leveldown@0.10.2 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by cdaringe** [comment]
thanks @rvagg.  i was able to repeat your steps and confirm that all was well with leveldown@latest (builds and tests OK).  this lead me to scrap my global version, reinstall (which perhaps was done with a different node build?), and return to happiness. :+1:
