### ISSUE TITLE
node-pre-gyp

### ISSUE THREAD

**Issue by rvagg** [Level/leveldown#95]
@maxogden @mafintosh I think you guys have been working on this and I don't want to go duplicating effort here. I'm mainly interested in shipping binaries of windows builds but I'm sure OSX users would appreciate it too. Linux is too tricky a target IMO because of the massive variability in libc + arch, although perhaps node-pre-gyp has some way of taking that into account?

**Comment by mafintosh** [comment]
bumping this. we have used https://github.com/mafintosh/leveldown-prebuilt for experimentation with this and are quite liking it. @ralphtheninja @rvagg @juliangruber i can send a pr that starts using node-pre-gyp with a build fallback, meaning that if not prebuild isn't available it'll just fallback to building leveldown from source (like now)?

**Comment by mcollina** [comment]
+1, shorter install times are awesome!
Il giorno sab 9 mag 2015 alle 13:15 Mathias Buus <notifications@github.com>
ha scritto:

**Comment by ralphtheninja** [comment]
@mafintosh Do it! :)

**Comment by juliangruber** [comment]
> meaning that if not prebuild isn't available it'll just fallback to building leveldown from source (like now)?

you mean it would try `require('leveldown-prebuilt')` and fall back to building? or should it do something like node-sass does (iirc) to install binaries globally

**Comment by No9** [comment]
Would love to see this as it does impede adoption in some scenarios

**Comment by mafintosh** [comment]
@juliangruber no i would basically take the small changes we added in level-prebuilt (its a fork of leveldown) and merge them in here. it uses node-pre-gyp instead of node-gyp which checks if there is a static build available at a url for your platform before trying to build it from source.

**Comment by ralphtheninja** [comment]
I'm especially thrilled about this because of windows support. I don't use it myself but windows users are going to love this.

**Comment by juliangruber** [comment]
ok, I so agree to this. my joyent box takes ages to build leveldown, and to have the prebuilt functionality available to the masses instaling plain leveldown is awesome

**Comment by ralphtheninja** [comment]
@mafintosh If your hands are full I could make sure to bring this into leveldown. Any pointers on where I should look?

**Comment by mafintosh** [comment]
@ralphtheninja that would be great. checkout https://github.com/mafintosh/leveldown-prebuilt which is my fork of leveldown that adds prebuilts

**Comment by ralphtheninja** [comment]
@mafintosh So essentially that fork is pure leveldown + the prebuilt things. Nothing else?

**Comment by mafintosh** [comment]
@ralphtheninja yea

**Comment by ralphtheninja** [comment]
@mafintosh https://github.com/Level/leveldown/pull/188 would be great if you could check that this looks ok

**Comment by ralphtheninja** [comment]
This is done.
